POST http://127.0.0.1:8080/api/login/verify-email/start
Content-Type: application/json

{
  "email": "test@example.com"
}

###
POST http://127.0.0.1:8080/api/login/reset-password/start
Content-Type: application/json

{
  "email": "test@example.com"
}
