edition = "2023";

package xyz.city_ideas.v1.ranks.v1;

import "google/protobuf/empty.proto";
import "xyz/city_ideas/v1/ranks/v1/domain.proto";
import "xyz/city_ideas/v1/types.proto";

option go_package = "github.com/aesterial/cityideas/backend/internal/api/v1/ranks/v1;v1";

service RankService {
  rpc Permissions(google.protobuf.Empty) returns (xyz.city_ideas.v1.ranks.v1.Permissions);
  rpc Create(xyz.city_ideas.v1.ranks.v1.CreateRequest) returns (xyz.city_ideas.v1.ranks.v1.Rank);
  rpc Rank(xyz.city_ideas.v1.RequestWithValue) returns (xyz.city_ideas.v1.ranks.v1.Rank);
  rpc List(xyz.city_ideas.v1.RequestWithLimitAndOffset) returns (xyz.city_ideas.v1.ranks.v1.ListResponse);
  rpc Edit(xyz.city_ideas.v1.ranks.v1.Rank) returns (xyz.city_ideas.v1.ranks.v1.Rank);
  rpc Delete(xyz.city_ideas.v1.RequestWithValue) returns (google.protobuf.Empty);
  rpc Assign(xyz.city_ideas.v1.ranks.v1.AssignRankRequest) returns (google.protobuf.Empty);
  rpc Revoke(xyz.city_ideas.v1.ranks.v1.RevokeRankRequest) returns (google.protobuf.Empty);
}