// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/city_ideas/v1/actions/v1/domain.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Owner       *string                `protobuf:"bytes,2,opt,name=owner"`
	xxx_hidden_Purpose     *string                `protobuf:"bytes,3,opt,name=purpose"`
	xxx_hidden_Hash        *string                `protobuf:"bytes,4,opt,name=hash"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt"`
	xxx_hidden_ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt"`
	xxx_hidden_Used        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=used"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Action) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Action) GetOwner() string {
	if x != nil {
		if x.xxx_hidden_Owner != nil {
			return *x.xxx_hidden_Owner
		}
		return ""
	}
	return ""
}

func (x *Action) GetPurpose() string {
	if x != nil {
		if x.xxx_hidden_Purpose != nil {
			return *x.xxx_hidden_Purpose
		}
		return ""
	}
	return ""
}

func (x *Action) GetHash() string {
	if x != nil {
		if x.xxx_hidden_Hash != nil {
			return *x.xxx_hidden_Hash
		}
		return ""
	}
	return ""
}

func (x *Action) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Action) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *Action) GetUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Used
	}
	return nil
}

func (x *Action) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *Action) SetOwner(v string) {
	x.xxx_hidden_Owner = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *Action) SetPurpose(v string) {
	x.xxx_hidden_Purpose = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *Action) SetHash(v string) {
	x.xxx_hidden_Hash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *Action) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Action) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *Action) SetUsed(v *timestamppb.Timestamp) {
	x.xxx_hidden_Used = v
}

func (x *Action) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Action) HasOwner() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Action) HasPurpose() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Action) HasHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Action) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Action) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *Action) HasUsed() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Used != nil
}

func (x *Action) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Action) ClearOwner() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Owner = nil
}

func (x *Action) ClearPurpose() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Purpose = nil
}

func (x *Action) ClearHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Hash = nil
}

func (x *Action) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Action) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

func (x *Action) ClearUsed() {
	x.xxx_hidden_Used = nil
}

type Action_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        *string
	Owner     *string
	Purpose   *string
	Hash      *string
	CreatedAt *timestamppb.Timestamp
	ExpiresAt *timestamppb.Timestamp
	Used      *timestamppb.Timestamp
}

func (b0 Action_builder) Build() *Action {
	m0 := &Action{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = b.Id
	}
	if b.Owner != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Owner = b.Owner
	}
	if b.Purpose != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Purpose = b.Purpose
	}
	if b.Hash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Hash = b.Hash
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	x.xxx_hidden_Used = b.Used
	return m0
}

type CreateActionRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Purpose     *string                `protobuf:"bytes,1,opt,name=purpose"`
	xxx_hidden_User        *string                `protobuf:"bytes,2,opt,name=user"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateActionRequest) Reset() {
	*x = CreateActionRequest{}
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActionRequest) ProtoMessage() {}

func (x *CreateActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateActionRequest) GetPurpose() string {
	if x != nil {
		if x.xxx_hidden_Purpose != nil {
			return *x.xxx_hidden_Purpose
		}
		return ""
	}
	return ""
}

func (x *CreateActionRequest) GetUser() string {
	if x != nil {
		if x.xxx_hidden_User != nil {
			return *x.xxx_hidden_User
		}
		return ""
	}
	return ""
}

func (x *CreateActionRequest) SetPurpose(v string) {
	x.xxx_hidden_Purpose = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateActionRequest) SetUser(v string) {
	x.xxx_hidden_User = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CreateActionRequest) HasPurpose() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateActionRequest) HasUser() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateActionRequest) ClearPurpose() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Purpose = nil
}

func (x *CreateActionRequest) ClearUser() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_User = nil
}

type CreateActionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Purpose *string
	User    *string
}

func (b0 CreateActionRequest_builder) Build() *CreateActionRequest {
	m0 := &CreateActionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Purpose != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Purpose = b.Purpose
	}
	if b.User != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_User = b.User
	}
	return m0
}

type CreateActionResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Action *Action                `protobuf:"bytes,1,opt,name=action"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateActionResponse) Reset() {
	*x = CreateActionResponse{}
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActionResponse) ProtoMessage() {}

func (x *CreateActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateActionResponse) GetAction() *Action {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return nil
}

func (x *CreateActionResponse) SetAction(v *Action) {
	x.xxx_hidden_Action = v
}

func (x *CreateActionResponse) HasAction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Action != nil
}

func (x *CreateActionResponse) ClearAction() {
	x.xxx_hidden_Action = nil
}

type CreateActionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Action *Action
}

func (b0 CreateActionResponse_builder) Build() *CreateActionResponse {
	m0 := &CreateActionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Action = b.Action
	return m0
}

type UseActionRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Purpose     *string                `protobuf:"bytes,1,opt,name=purpose"`
	xxx_hidden_Hash        *string                `protobuf:"bytes,2,opt,name=hash"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UseActionRequest) Reset() {
	*x = UseActionRequest{}
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseActionRequest) ProtoMessage() {}

func (x *UseActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UseActionRequest) GetPurpose() string {
	if x != nil {
		if x.xxx_hidden_Purpose != nil {
			return *x.xxx_hidden_Purpose
		}
		return ""
	}
	return ""
}

func (x *UseActionRequest) GetHash() string {
	if x != nil {
		if x.xxx_hidden_Hash != nil {
			return *x.xxx_hidden_Hash
		}
		return ""
	}
	return ""
}

func (x *UseActionRequest) SetPurpose(v string) {
	x.xxx_hidden_Purpose = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UseActionRequest) SetHash(v string) {
	x.xxx_hidden_Hash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *UseActionRequest) HasPurpose() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UseActionRequest) HasHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UseActionRequest) ClearPurpose() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Purpose = nil
}

func (x *UseActionRequest) ClearHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Hash = nil
}

type UseActionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Purpose *string
	Hash    *string
}

func (b0 UseActionRequest_builder) Build() *UseActionRequest {
	m0 := &UseActionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Purpose != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Purpose = b.Purpose
	}
	if b.Hash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Hash = b.Hash
	}
	return m0
}

type FindActionRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Purpose     *string                `protobuf:"bytes,1,opt,name=purpose"`
	xxx_hidden_Hash        *string                `protobuf:"bytes,2,opt,name=hash"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FindActionRequest) Reset() {
	*x = FindActionRequest{}
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindActionRequest) ProtoMessage() {}

func (x *FindActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FindActionRequest) GetPurpose() string {
	if x != nil {
		if x.xxx_hidden_Purpose != nil {
			return *x.xxx_hidden_Purpose
		}
		return ""
	}
	return ""
}

func (x *FindActionRequest) GetHash() string {
	if x != nil {
		if x.xxx_hidden_Hash != nil {
			return *x.xxx_hidden_Hash
		}
		return ""
	}
	return ""
}

func (x *FindActionRequest) SetPurpose(v string) {
	x.xxx_hidden_Purpose = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *FindActionRequest) SetHash(v string) {
	x.xxx_hidden_Hash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *FindActionRequest) HasPurpose() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FindActionRequest) HasHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FindActionRequest) ClearPurpose() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Purpose = nil
}

func (x *FindActionRequest) ClearHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Hash = nil
}

type FindActionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Purpose *string
	Hash    *string
}

func (b0 FindActionRequest_builder) Build() *FindActionRequest {
	m0 := &FindActionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Purpose != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Purpose = b.Purpose
	}
	if b.Hash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Hash = b.Hash
	}
	return m0
}

type FindActionResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Action *Action                `protobuf:"bytes,1,opt,name=action"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FindActionResponse) Reset() {
	*x = FindActionResponse{}
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindActionResponse) ProtoMessage() {}

func (x *FindActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FindActionResponse) GetAction() *Action {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return nil
}

func (x *FindActionResponse) SetAction(v *Action) {
	x.xxx_hidden_Action = v
}

func (x *FindActionResponse) HasAction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Action != nil
}

func (x *FindActionResponse) ClearAction() {
	x.xxx_hidden_Action = nil
}

type FindActionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Action *Action
}

func (b0 FindActionResponse_builder) Build() *FindActionResponse {
	m0 := &FindActionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Action = b.Action
	return m0
}

type GetActionsByOwnerRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User        *string                `protobuf:"bytes,1,opt,name=user"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetActionsByOwnerRequest) Reset() {
	*x = GetActionsByOwnerRequest{}
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionsByOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionsByOwnerRequest) ProtoMessage() {}

func (x *GetActionsByOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetActionsByOwnerRequest) GetUser() string {
	if x != nil {
		if x.xxx_hidden_User != nil {
			return *x.xxx_hidden_User
		}
		return ""
	}
	return ""
}

func (x *GetActionsByOwnerRequest) SetUser(v string) {
	x.xxx_hidden_User = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetActionsByOwnerRequest) HasUser() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetActionsByOwnerRequest) ClearUser() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_User = nil
}

type GetActionsByOwnerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User *string
}

func (b0 GetActionsByOwnerRequest_builder) Build() *GetActionsByOwnerRequest {
	m0 := &GetActionsByOwnerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.User != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_User = b.User
	}
	return m0
}

type GetActionsByOwnerResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Actions *[]*Action             `protobuf:"bytes,1,rep,name=actions"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetActionsByOwnerResponse) Reset() {
	*x = GetActionsByOwnerResponse{}
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionsByOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionsByOwnerResponse) ProtoMessage() {}

func (x *GetActionsByOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetActionsByOwnerResponse) GetActions() []*Action {
	if x != nil {
		if x.xxx_hidden_Actions != nil {
			return *x.xxx_hidden_Actions
		}
	}
	return nil
}

func (x *GetActionsByOwnerResponse) SetActions(v []*Action) {
	x.xxx_hidden_Actions = &v
}

type GetActionsByOwnerResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Actions []*Action
}

func (b0 GetActionsByOwnerResponse_builder) Build() *GetActionsByOwnerResponse {
	m0 := &GetActionsByOwnerResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Actions = &b.Actions
	return m0
}

type CheckActionRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Purpose     *string                `protobuf:"bytes,1,opt,name=purpose"`
	xxx_hidden_Hash        *string                `protobuf:"bytes,2,opt,name=hash"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CheckActionRequest) Reset() {
	*x = CheckActionRequest{}
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckActionRequest) ProtoMessage() {}

func (x *CheckActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CheckActionRequest) GetPurpose() string {
	if x != nil {
		if x.xxx_hidden_Purpose != nil {
			return *x.xxx_hidden_Purpose
		}
		return ""
	}
	return ""
}

func (x *CheckActionRequest) GetHash() string {
	if x != nil {
		if x.xxx_hidden_Hash != nil {
			return *x.xxx_hidden_Hash
		}
		return ""
	}
	return ""
}

func (x *CheckActionRequest) SetPurpose(v string) {
	x.xxx_hidden_Purpose = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CheckActionRequest) SetHash(v string) {
	x.xxx_hidden_Hash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CheckActionRequest) HasPurpose() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CheckActionRequest) HasHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CheckActionRequest) ClearPurpose() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Purpose = nil
}

func (x *CheckActionRequest) ClearHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Hash = nil
}

type CheckActionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Purpose *string
	Hash    *string
}

func (b0 CheckActionRequest_builder) Build() *CheckActionRequest {
	m0 := &CheckActionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Purpose != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Purpose = b.Purpose
	}
	if b.Hash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Hash = b.Hash
	}
	return m0
}

var File_xyz_city_ideas_v1_actions_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_actions_v1_domain_proto_rawDesc = "" +
	"\n" +
	")xyz/city_ideas/v1/actions/v1/domain.proto\x12\x1cxyz.city_ideas.v1.actions.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x02\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12.\n" +
	"\x04used\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x04used\"C\n" +
	"\x13CreateActionRequest\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"T\n" +
	"\x14CreateActionResponse\x12<\n" +
	"\x06action\x18\x01 \x01(\v2$.xyz.city_ideas.v1.actions.v1.ActionR\x06action\"@\n" +
	"\x10UseActionRequest\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"A\n" +
	"\x11FindActionRequest\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"R\n" +
	"\x12FindActionResponse\x12<\n" +
	"\x06action\x18\x01 \x01(\v2$.xyz.city_ideas.v1.actions.v1.ActionR\x06action\".\n" +
	"\x18GetActionsByOwnerRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\"[\n" +
	"\x19GetActionsByOwnerResponse\x12>\n" +
	"\aactions\x18\x01 \x03(\v2$.xyz.city_ideas.v1.actions.v1.ActionR\aactions\"B\n" +
	"\x12CheckActionRequest\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hashBFZDgithub.com/aesterial/cityideas/backend/internal/api/v1/actions/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_xyz_city_ideas_v1_actions_v1_domain_proto_goTypes = []any{
	(*Action)(nil),                    // 0: xyz.city_ideas.v1.actions.v1.Action
	(*CreateActionRequest)(nil),       // 1: xyz.city_ideas.v1.actions.v1.CreateActionRequest
	(*CreateActionResponse)(nil),      // 2: xyz.city_ideas.v1.actions.v1.CreateActionResponse
	(*UseActionRequest)(nil),          // 3: xyz.city_ideas.v1.actions.v1.UseActionRequest
	(*FindActionRequest)(nil),         // 4: xyz.city_ideas.v1.actions.v1.FindActionRequest
	(*FindActionResponse)(nil),        // 5: xyz.city_ideas.v1.actions.v1.FindActionResponse
	(*GetActionsByOwnerRequest)(nil),  // 6: xyz.city_ideas.v1.actions.v1.GetActionsByOwnerRequest
	(*GetActionsByOwnerResponse)(nil), // 7: xyz.city_ideas.v1.actions.v1.GetActionsByOwnerResponse
	(*CheckActionRequest)(nil),        // 8: xyz.city_ideas.v1.actions.v1.CheckActionRequest
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_xyz_city_ideas_v1_actions_v1_domain_proto_depIdxs = []int32{
	9, // 0: xyz.city_ideas.v1.actions.v1.Action.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: xyz.city_ideas.v1.actions.v1.Action.expires_at:type_name -> google.protobuf.Timestamp
	9, // 2: xyz.city_ideas.v1.actions.v1.Action.used:type_name -> google.protobuf.Timestamp
	0, // 3: xyz.city_ideas.v1.actions.v1.CreateActionResponse.action:type_name -> xyz.city_ideas.v1.actions.v1.Action
	0, // 4: xyz.city_ideas.v1.actions.v1.FindActionResponse.action:type_name -> xyz.city_ideas.v1.actions.v1.Action
	0, // 5: xyz.city_ideas.v1.actions.v1.GetActionsByOwnerResponse.actions:type_name -> xyz.city_ideas.v1.actions.v1.Action
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_actions_v1_domain_proto_init() }
func file_xyz_city_ideas_v1_actions_v1_domain_proto_init() {
	if File_xyz_city_ideas_v1_actions_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_actions_v1_domain_proto_rawDesc), len(file_xyz_city_ideas_v1_actions_v1_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_city_ideas_v1_actions_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_actions_v1_domain_proto_depIdxs,
		MessageInfos:      file_xyz_city_ideas_v1_actions_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_city_ideas_v1_actions_v1_domain_proto = out.File
	file_xyz_city_ideas_v1_actions_v1_domain_proto_goTypes = nil
	file_xyz_city_ideas_v1_actions_v1_domain_proto_depIdxs = nil
}
