edition = "2023";

package xyz.city_ideas.v1.cities.v1;

import "google/protobuf/empty.proto";
import "xyz/city_ideas/v1/cities/v1/domain.proto";
import "xyz/city_ideas/v1/types.proto";

option go_package = "github.com/aesterial/cityideas/backend/internal/api/v1/cities/v1;v1";

service CitiesService {
  rpc List(google.protobuf.Empty) returns (xyz.city_ideas.v1.cities.v1.ListResponse);
  rpc Create(xyz.city_ideas.v1.cities.v1.CreateCityRequest) returns (xyz.city_ideas.v1.cities.v1.City);
  rpc Delete(xyz.city_ideas.v1.RequestWithValue) returns (google.protobuf.Empty);
}
