// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/city_ideas/v1/statistics/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xyz_city_ideas_v1_statistics_v1_service_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_statistics_v1_service_proto_rawDesc = "" +
	"\n" +
	"-xyz/city_ideas/v1/statistics/v1/service.proto\x12\x1fxyz.city_ideas.v1.statistics.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a,xyz/city_ideas/v1/statistics/v1/domain.proto2\x8b\x04\n" +
	"\x10StatisticService\x12I\n" +
	"\x06Global\x12\x16.google.protobuf.Empty\x1a'.xyz.city_ideas.v1.statistics.v1.Global\x12f\n" +
	"\fProjectVotes\x12..xyz.city_ideas.v1.statistics.v1.RequestByCity\x1a&.xyz.city_ideas.v1.statistics.v1.Graph\x12i\n" +
	"\x0fProjectCreation\x12..xyz.city_ideas.v1.statistics.v1.RequestByCity\x1a&.xyz.city_ideas.v1.statistics.v1.Graph\x12k\n" +
	"\x11ProjectDiscussion\x12..xyz.city_ideas.v1.statistics.v1.RequestByCity\x1a&.xyz.city_ideas.v1.statistics.v1.Graph\x12l\n" +
	"\x11QuestionsActivity\x12/.xyz.city_ideas.v1.statistics.v1.SeparatorValue\x1a&.xyz.city_ideas.v1.statistics.v1.GraphBIZGgithub.com/aesterial/cityideas/backend/internal/api/v1/statistics/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_statistics_v1_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),  // 0: google.protobuf.Empty
	(*RequestByCity)(nil),  // 1: xyz.city_ideas.v1.statistics.v1.RequestByCity
	(*SeparatorValue)(nil), // 2: xyz.city_ideas.v1.statistics.v1.SeparatorValue
	(*Global)(nil),         // 3: xyz.city_ideas.v1.statistics.v1.Global
	(*Graph)(nil),          // 4: xyz.city_ideas.v1.statistics.v1.Graph
}
var file_xyz_city_ideas_v1_statistics_v1_service_proto_depIdxs = []int32{
	0, // 0: xyz.city_ideas.v1.statistics.v1.StatisticService.Global:input_type -> google.protobuf.Empty
	1, // 1: xyz.city_ideas.v1.statistics.v1.StatisticService.ProjectVotes:input_type -> xyz.city_ideas.v1.statistics.v1.RequestByCity
	1, // 2: xyz.city_ideas.v1.statistics.v1.StatisticService.ProjectCreation:input_type -> xyz.city_ideas.v1.statistics.v1.RequestByCity
	1, // 3: xyz.city_ideas.v1.statistics.v1.StatisticService.ProjectDiscussion:input_type -> xyz.city_ideas.v1.statistics.v1.RequestByCity
	2, // 4: xyz.city_ideas.v1.statistics.v1.StatisticService.QuestionsActivity:input_type -> xyz.city_ideas.v1.statistics.v1.SeparatorValue
	3, // 5: xyz.city_ideas.v1.statistics.v1.StatisticService.Global:output_type -> xyz.city_ideas.v1.statistics.v1.Global
	4, // 6: xyz.city_ideas.v1.statistics.v1.StatisticService.ProjectVotes:output_type -> xyz.city_ideas.v1.statistics.v1.Graph
	4, // 7: xyz.city_ideas.v1.statistics.v1.StatisticService.ProjectCreation:output_type -> xyz.city_ideas.v1.statistics.v1.Graph
	4, // 8: xyz.city_ideas.v1.statistics.v1.StatisticService.ProjectDiscussion:output_type -> xyz.city_ideas.v1.statistics.v1.Graph
	4, // 9: xyz.city_ideas.v1.statistics.v1.StatisticService.QuestionsActivity:output_type -> xyz.city_ideas.v1.statistics.v1.Graph
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_statistics_v1_service_proto_init() }
func file_xyz_city_ideas_v1_statistics_v1_service_proto_init() {
	if File_xyz_city_ideas_v1_statistics_v1_service_proto != nil {
		return
	}
	file_xyz_city_ideas_v1_statistics_v1_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_statistics_v1_service_proto_rawDesc), len(file_xyz_city_ideas_v1_statistics_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_city_ideas_v1_statistics_v1_service_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_statistics_v1_service_proto_depIdxs,
	}.Build()
	File_xyz_city_ideas_v1_statistics_v1_service_proto = out.File
	file_xyz_city_ideas_v1_statistics_v1_service_proto_goTypes = nil
	file_xyz_city_ideas_v1_statistics_v1_service_proto_depIdxs = nil
}
