// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: xyz/city_ideas/v1/statistics/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatisticService_Global_FullMethodName            = "/xyz.city_ideas.v1.statistics.v1.StatisticService/Global"
	StatisticService_ProjectVotes_FullMethodName      = "/xyz.city_ideas.v1.statistics.v1.StatisticService/ProjectVotes"
	StatisticService_ProjectCreation_FullMethodName   = "/xyz.city_ideas.v1.statistics.v1.StatisticService/ProjectCreation"
	StatisticService_ProjectDiscussion_FullMethodName = "/xyz.city_ideas.v1.statistics.v1.StatisticService/ProjectDiscussion"
	StatisticService_QuestionsActivity_FullMethodName = "/xyz.city_ideas.v1.statistics.v1.StatisticService/QuestionsActivity"
)

// StatisticServiceClient is the client API for StatisticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticServiceClient interface {
	Global(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Global, error)
	ProjectVotes(ctx context.Context, in *RequestByCity, opts ...grpc.CallOption) (*Graph, error)
	ProjectCreation(ctx context.Context, in *RequestByCity, opts ...grpc.CallOption) (*Graph, error)
	ProjectDiscussion(ctx context.Context, in *RequestByCity, opts ...grpc.CallOption) (*Graph, error)
	QuestionsActivity(ctx context.Context, in *SeparatorValue, opts ...grpc.CallOption) (*Graph, error)
}

type statisticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticServiceClient(cc grpc.ClientConnInterface) StatisticServiceClient {
	return &statisticServiceClient{cc}
}

func (c *statisticServiceClient) Global(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Global, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Global)
	err := c.cc.Invoke(ctx, StatisticService_Global_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticServiceClient) ProjectVotes(ctx context.Context, in *RequestByCity, opts ...grpc.CallOption) (*Graph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Graph)
	err := c.cc.Invoke(ctx, StatisticService_ProjectVotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticServiceClient) ProjectCreation(ctx context.Context, in *RequestByCity, opts ...grpc.CallOption) (*Graph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Graph)
	err := c.cc.Invoke(ctx, StatisticService_ProjectCreation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticServiceClient) ProjectDiscussion(ctx context.Context, in *RequestByCity, opts ...grpc.CallOption) (*Graph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Graph)
	err := c.cc.Invoke(ctx, StatisticService_ProjectDiscussion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticServiceClient) QuestionsActivity(ctx context.Context, in *SeparatorValue, opts ...grpc.CallOption) (*Graph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Graph)
	err := c.cc.Invoke(ctx, StatisticService_QuestionsActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticServiceServer is the server API for StatisticService service.
// All implementations should embed UnimplementedStatisticServiceServer
// for forward compatibility.
type StatisticServiceServer interface {
	Global(context.Context, *emptypb.Empty) (*Global, error)
	ProjectVotes(context.Context, *RequestByCity) (*Graph, error)
	ProjectCreation(context.Context, *RequestByCity) (*Graph, error)
	ProjectDiscussion(context.Context, *RequestByCity) (*Graph, error)
	QuestionsActivity(context.Context, *SeparatorValue) (*Graph, error)
}

// UnimplementedStatisticServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatisticServiceServer struct{}

func (UnimplementedStatisticServiceServer) Global(context.Context, *emptypb.Empty) (*Global, error) {
	return nil, status.Error(codes.Unimplemented, "method Global not implemented")
}
func (UnimplementedStatisticServiceServer) ProjectVotes(context.Context, *RequestByCity) (*Graph, error) {
	return nil, status.Error(codes.Unimplemented, "method ProjectVotes not implemented")
}
func (UnimplementedStatisticServiceServer) ProjectCreation(context.Context, *RequestByCity) (*Graph, error) {
	return nil, status.Error(codes.Unimplemented, "method ProjectCreation not implemented")
}
func (UnimplementedStatisticServiceServer) ProjectDiscussion(context.Context, *RequestByCity) (*Graph, error) {
	return nil, status.Error(codes.Unimplemented, "method ProjectDiscussion not implemented")
}
func (UnimplementedStatisticServiceServer) QuestionsActivity(context.Context, *SeparatorValue) (*Graph, error) {
	return nil, status.Error(codes.Unimplemented, "method QuestionsActivity not implemented")
}
func (UnimplementedStatisticServiceServer) testEmbeddedByValue() {}

// UnsafeStatisticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticServiceServer will
// result in compilation errors.
type UnsafeStatisticServiceServer interface {
	mustEmbedUnimplementedStatisticServiceServer()
}

func RegisterStatisticServiceServer(s grpc.ServiceRegistrar, srv StatisticServiceServer) {
	// If the following call panics, it indicates UnimplementedStatisticServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatisticService_ServiceDesc, srv)
}

func _StatisticService_Global_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticServiceServer).Global(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticService_Global_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticServiceServer).Global(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticService_ProjectVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByCity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticServiceServer).ProjectVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticService_ProjectVotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticServiceServer).ProjectVotes(ctx, req.(*RequestByCity))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticService_ProjectCreation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByCity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticServiceServer).ProjectCreation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticService_ProjectCreation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticServiceServer).ProjectCreation(ctx, req.(*RequestByCity))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticService_ProjectDiscussion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByCity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticServiceServer).ProjectDiscussion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticService_ProjectDiscussion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticServiceServer).ProjectDiscussion(ctx, req.(*RequestByCity))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticService_QuestionsActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeparatorValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticServiceServer).QuestionsActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticService_QuestionsActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticServiceServer).QuestionsActivity(ctx, req.(*SeparatorValue))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticService_ServiceDesc is the grpc.ServiceDesc for StatisticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz.city_ideas.v1.statistics.v1.StatisticService",
	HandlerType: (*StatisticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Global",
			Handler:    _StatisticService_Global_Handler,
		},
		{
			MethodName: "ProjectVotes",
			Handler:    _StatisticService_ProjectVotes_Handler,
		},
		{
			MethodName: "ProjectCreation",
			Handler:    _StatisticService_ProjectCreation_Handler,
		},
		{
			MethodName: "ProjectDiscussion",
			Handler:    _StatisticService_ProjectDiscussion_Handler,
		},
		{
			MethodName: "QuestionsActivity",
			Handler:    _StatisticService_QuestionsActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xyz/city_ideas/v1/statistics/v1/service.proto",
}
