// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/city_ideas/v1/ranks/v1/domain.proto

package v1

import (
	_ "github.com/aesterial/cityideas/backend/internal/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Description *string                `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_Color       int64                  `protobuf:"varint,3,opt,name=color"`
	xxx_hidden_Weight      int32                  `protobuf:"varint,4,opt,name=weight"`
	xxx_hidden_Perms       []string               `protobuf:"bytes,5,rep,name=perms"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_xyz_city_ideas_v1_ranks_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_ranks_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *CreateRequest) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *CreateRequest) GetColor() int64 {
	if x != nil {
		return x.xxx_hidden_Color
	}
	return 0
}

func (x *CreateRequest) GetWeight() int32 {
	if x != nil {
		return x.xxx_hidden_Weight
	}
	return 0
}

func (x *CreateRequest) GetPerms() []string {
	if x != nil {
		return x.xxx_hidden_Perms
	}
	return nil
}

func (x *CreateRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *CreateRequest) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *CreateRequest) SetColor(v int64) {
	x.xxx_hidden_Color = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *CreateRequest) SetWeight(v int32) {
	x.xxx_hidden_Weight = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *CreateRequest) SetPerms(v []string) {
	x.xxx_hidden_Perms = v
}

func (x *CreateRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateRequest) HasColor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateRequest) HasWeight() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *CreateRequest) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Description = nil
}

func (x *CreateRequest) ClearColor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Color = 0
}

func (x *CreateRequest) ClearWeight() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Weight = 0
}

type CreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        *string
	Description *string
	Color       *int64
	Weight      *int32
	Perms       []string
}

func (b0 CreateRequest_builder) Build() *CreateRequest {
	m0 := &CreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Description = b.Description
	}
	if b.Color != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Color = *b.Color
	}
	if b.Weight != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Weight = *b.Weight
	}
	x.xxx_hidden_Perms = b.Perms
	return m0
}

type Rank struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Description *string                `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_Color       int64                  `protobuf:"varint,4,opt,name=color"`
	xxx_hidden_Weight      int32                  `protobuf:"varint,5,opt,name=weight"`
	xxx_hidden_Permissions []string               `protobuf:"bytes,6,rep,name=permissions"`
	xxx_hidden_At          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=at"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Rank) Reset() {
	*x = Rank{}
	mi := &file_xyz_city_ideas_v1_ranks_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank) ProtoMessage() {}

func (x *Rank) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_ranks_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Rank) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Rank) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Rank) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *Rank) GetColor() int64 {
	if x != nil {
		return x.xxx_hidden_Color
	}
	return 0
}

func (x *Rank) GetWeight() int32 {
	if x != nil {
		return x.xxx_hidden_Weight
	}
	return 0
}

func (x *Rank) GetPermissions() []string {
	if x != nil {
		return x.xxx_hidden_Permissions
	}
	return nil
}

func (x *Rank) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_At
	}
	return nil
}

func (x *Rank) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *Rank) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *Rank) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *Rank) SetColor(v int64) {
	x.xxx_hidden_Color = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *Rank) SetWeight(v int32) {
	x.xxx_hidden_Weight = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *Rank) SetPermissions(v []string) {
	x.xxx_hidden_Permissions = v
}

func (x *Rank) SetAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_At = v
}

func (x *Rank) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Rank) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Rank) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Rank) HasColor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Rank) HasWeight() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Rank) HasAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_At != nil
}

func (x *Rank) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Rank) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Rank) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *Rank) ClearColor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Color = 0
}

func (x *Rank) ClearWeight() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Weight = 0
}

func (x *Rank) ClearAt() {
	x.xxx_hidden_At = nil
}

type Rank_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          *string
	Name        *string
	Description *string
	Color       *int64
	Weight      *int32
	Permissions []string
	At          *timestamppb.Timestamp
}

func (b0 Rank_builder) Build() *Rank {
	m0 := &Rank{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Name = b.Name
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Description = b.Description
	}
	if b.Color != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Color = *b.Color
	}
	if b.Weight != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Weight = *b.Weight
	}
	x.xxx_hidden_Permissions = b.Permissions
	x.xxx_hidden_At = b.At
	return m0
}

type Permissions struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Perms []string               `protobuf:"bytes,1,rep,name=perms"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	mi := &file_xyz_city_ideas_v1_ranks_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_ranks_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Permissions) GetPerms() []string {
	if x != nil {
		return x.xxx_hidden_Perms
	}
	return nil
}

func (x *Permissions) SetPerms(v []string) {
	x.xxx_hidden_Perms = v
}

type Permissions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Perms []string
}

func (b0 Permissions_builder) Build() *Permissions {
	m0 := &Permissions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Perms = b.Perms
	return m0
}

type ListResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_List *[]*Rank               `protobuf:"bytes,1,rep,name=list"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_xyz_city_ideas_v1_ranks_v1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_ranks_v1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListResponse) GetList() []*Rank {
	if x != nil {
		if x.xxx_hidden_List != nil {
			return *x.xxx_hidden_List
		}
	}
	return nil
}

func (x *ListResponse) SetList(v []*Rank) {
	x.xxx_hidden_List = &v
}

type ListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	List []*Rank
}

func (b0 ListResponse_builder) Build() *ListResponse {
	m0 := &ListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_List = &b.List
	return m0
}

var File_xyz_city_ideas_v1_ranks_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_ranks_v1_domain_proto_rawDesc = "" +
	"\n" +
	"'xyz/city_ideas/v1/ranks/v1/domain.proto\x12\x1axyz.city_ideas.v1.ranks.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dxyz/city_ideas/v1/types.proto\"\x89\x01\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05color\x18\x03 \x01(\x03R\x05color\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12\x14\n" +
	"\x05perms\x18\x05 \x03(\tR\x05perms\"\xc8\x01\n" +
	"\x04Rank\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05color\x18\x04 \x01(\x03R\x05color\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12 \n" +
	"\vpermissions\x18\x06 \x03(\tR\vpermissions\x12*\n" +
	"\x02at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"#\n" +
	"\vPermissions\x12\x14\n" +
	"\x05perms\x18\x01 \x03(\tR\x05perms\"D\n" +
	"\fListResponse\x124\n" +
	"\x04list\x18\x01 \x03(\v2 .xyz.city_ideas.v1.ranks.v1.RankR\x04listBDZBgithub.com/aesterial/cityideas/backend/internal/api/v1/ranks/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_ranks_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xyz_city_ideas_v1_ranks_v1_domain_proto_goTypes = []any{
	(*CreateRequest)(nil),         // 0: xyz.city_ideas.v1.ranks.v1.CreateRequest
	(*Rank)(nil),                  // 1: xyz.city_ideas.v1.ranks.v1.Rank
	(*Permissions)(nil),           // 2: xyz.city_ideas.v1.ranks.v1.Permissions
	(*ListResponse)(nil),          // 3: xyz.city_ideas.v1.ranks.v1.ListResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_xyz_city_ideas_v1_ranks_v1_domain_proto_depIdxs = []int32{
	4, // 0: xyz.city_ideas.v1.ranks.v1.Rank.at:type_name -> google.protobuf.Timestamp
	1, // 1: xyz.city_ideas.v1.ranks.v1.ListResponse.list:type_name -> xyz.city_ideas.v1.ranks.v1.Rank
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_ranks_v1_domain_proto_init() }
func file_xyz_city_ideas_v1_ranks_v1_domain_proto_init() {
	if File_xyz_city_ideas_v1_ranks_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_ranks_v1_domain_proto_rawDesc), len(file_xyz_city_ideas_v1_ranks_v1_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_city_ideas_v1_ranks_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_ranks_v1_domain_proto_depIdxs,
		MessageInfos:      file_xyz_city_ideas_v1_ranks_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_city_ideas_v1_ranks_v1_domain_proto = out.File
	file_xyz_city_ideas_v1_ranks_v1_domain_proto_goTypes = nil
	file_xyz_city_ideas_v1_ranks_v1_domain_proto_depIdxs = nil
}
