// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/city_ideas/v1/storage/v1/domain.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Purpose int32

const (
	Purpose_PURPOSE_UNSPECIFIED   Purpose = 0
	Purpose_PURPOSE_AVATAR        Purpose = 1
	Purpose_PURPOSE_PROJECT_IMAGE Purpose = 2
)

// Enum value maps for Purpose.
var (
	Purpose_name = map[int32]string{
		0: "PURPOSE_UNSPECIFIED",
		1: "PURPOSE_AVATAR",
		2: "PURPOSE_PROJECT_IMAGE",
	}
	Purpose_value = map[string]int32{
		"PURPOSE_UNSPECIFIED":   0,
		"PURPOSE_AVATAR":        1,
		"PURPOSE_PROJECT_IMAGE": 2,
	}
)

func (x Purpose) Enum() *Purpose {
	p := new(Purpose)
	*p = x
	return p
}

func (x Purpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Purpose) Descriptor() protoreflect.EnumDescriptor {
	return file_xyz_city_ideas_v1_storage_v1_domain_proto_enumTypes[0].Descriptor()
}

func (Purpose) Type() protoreflect.EnumType {
	return &file_xyz_city_ideas_v1_storage_v1_domain_proto_enumTypes[0]
}

func (x Purpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type File struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Url         *string                `protobuf:"bytes,2,opt,name=url"`
	xxx_hidden_ContentType *string                `protobuf:"bytes,3,opt,name=content_type,json=contentType"`
	xxx_hidden_Size        int64                  `protobuf:"varint,4,opt,name=size"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_xyz_city_ideas_v1_storage_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_storage_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *File) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *File) GetUrl() string {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
		return ""
	}
	return ""
}

func (x *File) GetContentType() string {
	if x != nil {
		if x.xxx_hidden_ContentType != nil {
			return *x.xxx_hidden_ContentType
		}
		return ""
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *File) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *File) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *File) SetContentType(v string) {
	x.xxx_hidden_ContentType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *File) SetSize(v int64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *File) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *File) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *File) HasContentType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *File) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *File) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *File) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Url = nil
}

func (x *File) ClearContentType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ContentType = nil
}

func (x *File) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Size = 0
}

type File_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          *string
	Url         *string
	ContentType *string
	Size        *int64
}

func (b0 File_builder) Build() *File {
	m0 := &File{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = b.Id
	}
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Url = b.Url
	}
	if b.ContentType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ContentType = b.ContentType
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Size = *b.Size
	}
	return m0
}

var File_xyz_city_ideas_v1_storage_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_storage_v1_domain_proto_rawDesc = "" +
	"\n" +
	")xyz/city_ideas/v1/storage/v1/domain.proto\x12\x1cxyz.city_ideas.v1.storage.v1\"_\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size*Q\n" +
	"\aPurpose\x12\x17\n" +
	"\x13PURPOSE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePURPOSE_AVATAR\x10\x01\x12\x19\n" +
	"\x15PURPOSE_PROJECT_IMAGE\x10\x02BMZKgithub.com/aesterial/cityideas/backend/internal/api/v1/storage/v1;storagepbb\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_storage_v1_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xyz_city_ideas_v1_storage_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xyz_city_ideas_v1_storage_v1_domain_proto_goTypes = []any{
	(Purpose)(0), // 0: xyz.city_ideas.v1.storage.v1.Purpose
	(*File)(nil), // 1: xyz.city_ideas.v1.storage.v1.File
}
var file_xyz_city_ideas_v1_storage_v1_domain_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_storage_v1_domain_proto_init() }
func file_xyz_city_ideas_v1_storage_v1_domain_proto_init() {
	if File_xyz_city_ideas_v1_storage_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_storage_v1_domain_proto_rawDesc), len(file_xyz_city_ideas_v1_storage_v1_domain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_city_ideas_v1_storage_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_storage_v1_domain_proto_depIdxs,
		EnumInfos:         file_xyz_city_ideas_v1_storage_v1_domain_proto_enumTypes,
		MessageInfos:      file_xyz_city_ideas_v1_storage_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_city_ideas_v1_storage_v1_domain_proto = out.File
	file_xyz_city_ideas_v1_storage_v1_domain_proto_goTypes = nil
	file_xyz_city_ideas_v1_storage_v1_domain_proto_depIdxs = nil
}
