// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/city_ideas/v1/sessions/v1/domain.proto

package v1

import (
	v1 "github.com/aesterial/cityideas/backend/internal/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Session struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Mfa         bool                   `protobuf:"varint,2,opt,name=mfa"`
	xxx_hidden_Device      v1.Device              `protobuf:"varint,3,opt,name=device,enum=xyz.city_ideas.v1.Device"`
	xxx_hidden_Hash        *string                `protobuf:"bytes,4,opt,name=hash"`
	xxx_hidden_At          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=at"`
	xxx_hidden_Seen        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=seen"`
	xxx_hidden_Expired     bool                   `protobuf:"varint,7,opt,name=expired"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_xyz_city_ideas_v1_sessions_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_sessions_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Session) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Session) GetMfa() bool {
	if x != nil {
		return x.xxx_hidden_Mfa
	}
	return false
}

func (x *Session) GetDevice() v1.Device {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Device
		}
	}
	return v1.Device(0)
}

func (x *Session) GetHash() string {
	if x != nil {
		if x.xxx_hidden_Hash != nil {
			return *x.xxx_hidden_Hash
		}
		return ""
	}
	return ""
}

func (x *Session) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_At
	}
	return nil
}

func (x *Session) GetSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Seen
	}
	return nil
}

func (x *Session) GetExpired() bool {
	if x != nil {
		return x.xxx_hidden_Expired
	}
	return false
}

func (x *Session) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *Session) SetMfa(v bool) {
	x.xxx_hidden_Mfa = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *Session) SetDevice(v v1.Device) {
	x.xxx_hidden_Device = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *Session) SetHash(v string) {
	x.xxx_hidden_Hash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *Session) SetAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_At = v
}

func (x *Session) SetSeen(v *timestamppb.Timestamp) {
	x.xxx_hidden_Seen = v
}

func (x *Session) SetExpired(v bool) {
	x.xxx_hidden_Expired = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *Session) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Session) HasMfa() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Session) HasDevice() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Session) HasHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Session) HasAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_At != nil
}

func (x *Session) HasSeen() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Seen != nil
}

func (x *Session) HasExpired() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Session) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Session) ClearMfa() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Mfa = false
}

func (x *Session) ClearDevice() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Device = v1.Device_DEVICE_UNSPECIFIED
}

func (x *Session) ClearHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Hash = nil
}

func (x *Session) ClearAt() {
	x.xxx_hidden_At = nil
}

func (x *Session) ClearSeen() {
	x.xxx_hidden_Seen = nil
}

func (x *Session) ClearExpired() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Expired = false
}

type Session_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Mfa     *bool
	Device  *v1.Device
	Hash    *string
	At      *timestamppb.Timestamp
	Seen    *timestamppb.Timestamp
	Expired *bool
}

func (b0 Session_builder) Build() *Session {
	m0 := &Session{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = b.Id
	}
	if b.Mfa != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Mfa = *b.Mfa
	}
	if b.Device != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Device = *b.Device
	}
	if b.Hash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Hash = b.Hash
	}
	x.xxx_hidden_At = b.At
	x.xxx_hidden_Seen = b.Seen
	if b.Expired != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_Expired = *b.Expired
	}
	return m0
}

type ListResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_List *[]*Session            `protobuf:"bytes,1,rep,name=list"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_xyz_city_ideas_v1_sessions_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_sessions_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListResponse) GetList() []*Session {
	if x != nil {
		if x.xxx_hidden_List != nil {
			return *x.xxx_hidden_List
		}
	}
	return nil
}

func (x *ListResponse) SetList(v []*Session) {
	x.xxx_hidden_List = &v
}

type ListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	List []*Session
}

func (b0 ListResponse_builder) Build() *ListResponse {
	m0 := &ListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_List = &b.List
	return m0
}

var File_xyz_city_ideas_v1_sessions_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_sessions_v1_domain_proto_rawDesc = "" +
	"\n" +
	"*xyz/city_ideas/v1/sessions/v1/domain.proto\x12\x1dxyz.city_ideas.v1.sessions.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dxyz/city_ideas/v1/types.proto\"\xe8\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03mfa\x18\x02 \x01(\bR\x03mfa\x121\n" +
	"\x06device\x18\x03 \x01(\x0e2\x19.xyz.city_ideas.v1.DeviceR\x06device\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12*\n" +
	"\x02at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12.\n" +
	"\x04seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04seen\x12\x18\n" +
	"\aexpired\x18\a \x01(\bR\aexpired\"J\n" +
	"\fListResponse\x12:\n" +
	"\x04list\x18\x01 \x03(\v2&.xyz.city_ideas.v1.sessions.v1.SessionR\x04listBGZEgithub.com/aesterial/cityideas/backend/internal/api/v1/sessions/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_sessions_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xyz_city_ideas_v1_sessions_v1_domain_proto_goTypes = []any{
	(*Session)(nil),               // 0: xyz.city_ideas.v1.sessions.v1.Session
	(*ListResponse)(nil),          // 1: xyz.city_ideas.v1.sessions.v1.ListResponse
	(v1.Device)(0),                // 2: xyz.city_ideas.v1.Device
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_xyz_city_ideas_v1_sessions_v1_domain_proto_depIdxs = []int32{
	2, // 0: xyz.city_ideas.v1.sessions.v1.Session.device:type_name -> xyz.city_ideas.v1.Device
	3, // 1: xyz.city_ideas.v1.sessions.v1.Session.at:type_name -> google.protobuf.Timestamp
	3, // 2: xyz.city_ideas.v1.sessions.v1.Session.seen:type_name -> google.protobuf.Timestamp
	0, // 3: xyz.city_ideas.v1.sessions.v1.ListResponse.list:type_name -> xyz.city_ideas.v1.sessions.v1.Session
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_sessions_v1_domain_proto_init() }
func file_xyz_city_ideas_v1_sessions_v1_domain_proto_init() {
	if File_xyz_city_ideas_v1_sessions_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_sessions_v1_domain_proto_rawDesc), len(file_xyz_city_ideas_v1_sessions_v1_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_city_ideas_v1_sessions_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_sessions_v1_domain_proto_depIdxs,
		MessageInfos:      file_xyz_city_ideas_v1_sessions_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_city_ideas_v1_sessions_v1_domain_proto = out.File
	file_xyz_city_ideas_v1_sessions_v1_domain_proto_goTypes = nil
	file_xyz_city_ideas_v1_sessions_v1_domain_proto_depIdxs = nil
}
