// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz.city_ideas.v1/user/v1/domain.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserPreferences struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Description *string                `protobuf:"bytes,1,opt,name=description"`
	xxx_hidden_DisplayName *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName"`
	xxx_hidden_Avatar      *string                `protobuf:"bytes,3,opt,name=avatar"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserPreferences) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *UserPreferences) GetDisplayName() string {
	if x != nil {
		if x.xxx_hidden_DisplayName != nil {
			return *x.xxx_hidden_DisplayName
		}
		return ""
	}
	return ""
}

func (x *UserPreferences) GetAvatar() string {
	if x != nil {
		if x.xxx_hidden_Avatar != nil {
			return *x.xxx_hidden_Avatar
		}
		return ""
	}
	return ""
}

func (x *UserPreferences) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *UserPreferences) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *UserPreferences) SetAvatar(v string) {
	x.xxx_hidden_Avatar = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *UserPreferences) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserPreferences) HasDisplayName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserPreferences) HasAvatar() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UserPreferences) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Description = nil
}

func (x *UserPreferences) ClearDisplayName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DisplayName = nil
}

func (x *UserPreferences) ClearAvatar() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Avatar = nil
}

type UserPreferences_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Description *string
	DisplayName *string
	Avatar      *string
}

func (b0 UserPreferences_builder) Build() *UserPreferences {
	m0 := &UserPreferences{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Description = b.Description
	}
	if b.DisplayName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_DisplayName = b.DisplayName
	}
	if b.Avatar != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Avatar = b.Avatar
	}
	return m0
}

type UserRank struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Color       int64                  `protobuf:"varint,2,opt,name=color"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserRank) Reset() {
	*x = UserRank{}
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRank) ProtoMessage() {}

func (x *UserRank) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserRank) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *UserRank) GetColor() int64 {
	if x != nil {
		return x.xxx_hidden_Color
	}
	return 0
}

func (x *UserRank) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UserRank) SetColor(v int64) {
	x.xxx_hidden_Color = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *UserRank) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserRank) HasColor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserRank) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *UserRank) ClearColor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Color = 0
}

type UserRank_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name  *string
	Color *int64
}

func (b0 UserRank_builder) Build() *UserRank {
	m0 := &UserRank{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.Color != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Color = *b.Color
	}
	return m0
}

type PublicUser struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Username    *string                `protobuf:"bytes,2,opt,name=username"`
	xxx_hidden_Joined      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=joined"`
	xxx_hidden_Prefs       *UserPreferences       `protobuf:"bytes,4,opt,name=prefs"`
	xxx_hidden_Rank        *UserRank              `protobuf:"bytes,5,opt,name=rank"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PublicUser) Reset() {
	*x = PublicUser{}
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicUser) ProtoMessage() {}

func (x *PublicUser) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicUser) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *PublicUser) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *PublicUser) GetJoined() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Joined
	}
	return nil
}

func (x *PublicUser) GetPrefs() *UserPreferences {
	if x != nil {
		return x.xxx_hidden_Prefs
	}
	return nil
}

func (x *PublicUser) GetRank() *UserRank {
	if x != nil {
		return x.xxx_hidden_Rank
	}
	return nil
}

func (x *PublicUser) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *PublicUser) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *PublicUser) SetJoined(v *timestamppb.Timestamp) {
	x.xxx_hidden_Joined = v
}

func (x *PublicUser) SetPrefs(v *UserPreferences) {
	x.xxx_hidden_Prefs = v
}

func (x *PublicUser) SetRank(v *UserRank) {
	x.xxx_hidden_Rank = v
}

func (x *PublicUser) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PublicUser) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PublicUser) HasJoined() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Joined != nil
}

func (x *PublicUser) HasPrefs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Prefs != nil
}

func (x *PublicUser) HasRank() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Rank != nil
}

func (x *PublicUser) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *PublicUser) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Username = nil
}

func (x *PublicUser) ClearJoined() {
	x.xxx_hidden_Joined = nil
}

func (x *PublicUser) ClearPrefs() {
	x.xxx_hidden_Prefs = nil
}

func (x *PublicUser) ClearRank() {
	x.xxx_hidden_Rank = nil
}

type PublicUser_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       *string
	Username *string
	Joined   *timestamppb.Timestamp
	Prefs    *UserPreferences
	Rank     *UserRank
}

func (b0 PublicUser_builder) Build() *PublicUser {
	m0 := &PublicUser{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Username = b.Username
	}
	x.xxx_hidden_Joined = b.Joined
	x.xxx_hidden_Prefs = b.Prefs
	x.xxx_hidden_Rank = b.Rank
	return m0
}

type PrivateUser struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Info        *PublicUser            `protobuf:"bytes,1,opt,name=info"`
	xxx_hidden_SessionLive int32                  `protobuf:"varint,2,opt,name=session_live,json=sessionLive"`
	xxx_hidden_Email       *string                `protobuf:"bytes,3,opt,name=email"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PrivateUser) Reset() {
	*x = PrivateUser{}
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateUser) ProtoMessage() {}

func (x *PrivateUser) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrivateUser) GetInfo() *PublicUser {
	if x != nil {
		return x.xxx_hidden_Info
	}
	return nil
}

func (x *PrivateUser) GetSessionLive() int32 {
	if x != nil {
		return x.xxx_hidden_SessionLive
	}
	return 0
}

func (x *PrivateUser) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *PrivateUser) SetInfo(v *PublicUser) {
	x.xxx_hidden_Info = v
}

func (x *PrivateUser) SetSessionLive(v int32) {
	x.xxx_hidden_SessionLive = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *PrivateUser) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *PrivateUser) HasInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Info != nil
}

func (x *PrivateUser) HasSessionLive() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PrivateUser) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PrivateUser) ClearInfo() {
	x.xxx_hidden_Info = nil
}

func (x *PrivateUser) ClearSessionLive() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SessionLive = 0
}

func (x *PrivateUser) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Email = nil
}

type PrivateUser_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Info        *PublicUser
	SessionLive *int32
	Email       *string
}

func (b0 PrivateUser_builder) Build() *PrivateUser {
	m0 := &PrivateUser{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Info = b.Info
	if b.SessionLive != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_SessionLive = *b.SessionLive
	}
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Email = b.Email
	}
	return m0
}

var File_xyz_city_ideas_v1_user_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_user_v1_domain_proto_rawDesc = "" +
	"\n" +
	"&xyz.city_ideas.v1/user/v1/domain.proto\x12\x19xyz.city_ideas.v1.user.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"n\n" +
	"\x0fUserPreferences\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"4\n" +
	"\bUserRank\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x02 \x01(\x03R\x05color\"\xe7\x01\n" +
	"\n" +
	"PublicUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x122\n" +
	"\x06joined\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06joined\x12@\n" +
	"\x05prefs\x18\x04 \x01(\v2*.xyz.city_ideas.v1.user.v1.UserPreferencesR\x05prefs\x127\n" +
	"\x04rank\x18\x05 \x01(\v2#.xyz.city_ideas.v1.user.v1.UserRankR\x04rank\"\x81\x01\n" +
	"\vPrivateUser\x129\n" +
	"\x04info\x18\x01 \x01(\v2%.xyz.city_ideas.v1.user.v1.PublicUserR\x04info\x12!\n" +
	"\fsession_live\x18\x02 \x01(\x05R\vsessionLive\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05emailBCZAgithub.com/aesterial/cityideas/backend/internal/api/v1/user/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xyz_city_ideas_v1_user_v1_domain_proto_goTypes = []any{
	(*UserPreferences)(nil),       // 0: xyz.city_ideas.v1.user.v1.UserPreferences
	(*UserRank)(nil),              // 1: xyz.city_ideas.v1.user.v1.UserRank
	(*PublicUser)(nil),            // 2: xyz.city_ideas.v1.user.v1.PublicUser
	(*PrivateUser)(nil),           // 3: xyz.city_ideas.v1.user.v1.PrivateUser
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_xyz_city_ideas_v1_user_v1_domain_proto_depIdxs = []int32{
	4, // 0: xyz.city_ideas.v1.user.v1.PublicUser.joined:type_name -> google.protobuf.Timestamp
	0, // 1: xyz.city_ideas.v1.user.v1.PublicUser.prefs:type_name -> xyz.city_ideas.v1.user.v1.UserPreferences
	1, // 2: xyz.city_ideas.v1.user.v1.PublicUser.rank:type_name -> xyz.city_ideas.v1.user.v1.UserRank
	2, // 3: xyz.city_ideas.v1.user.v1.PrivateUser.info:type_name -> xyz.city_ideas.v1.user.v1.PublicUser
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_user_v1_domain_proto_init() }
func file_xyz_city_ideas_v1_user_v1_domain_proto_init() {
	if File_xyz_city_ideas_v1_user_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_user_v1_domain_proto_rawDesc), len(file_xyz_city_ideas_v1_user_v1_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_city_ideas_v1_user_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_user_v1_domain_proto_depIdxs,
		MessageInfos:      file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_city_ideas_v1_user_v1_domain_proto = out.File
	file_xyz_city_ideas_v1_user_v1_domain_proto_goTypes = nil
	file_xyz_city_ideas_v1_user_v1_domain_proto_depIdxs = nil
}
