// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/city_ideas/v1/user/v1/domain.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Languages int32

const (
	Languages_LANGUAGES_UNSPECIFIED Languages = 0
	Languages_LANGUAGES_RUSSIAN     Languages = 1
	Languages_LANGUAGES_ENGLISH     Languages = 2
)

// Enum value maps for Languages.
var (
	Languages_name = map[int32]string{
		0: "LANGUAGES_UNSPECIFIED",
		1: "LANGUAGES_RUSSIAN",
		2: "LANGUAGES_ENGLISH",
	}
	Languages_value = map[string]int32{
		"LANGUAGES_UNSPECIFIED": 0,
		"LANGUAGES_RUSSIAN":     1,
		"LANGUAGES_ENGLISH":     2,
	}
)

func (x Languages) Enum() *Languages {
	p := new(Languages)
	*p = x
	return p
}

func (x Languages) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Languages) Descriptor() protoreflect.EnumDescriptor {
	return file_xyz_city_ideas_v1_user_v1_domain_proto_enumTypes[0].Descriptor()
}

func (Languages) Type() protoreflect.EnumType {
	return &file_xyz_city_ideas_v1_user_v1_domain_proto_enumTypes[0]
}

func (x Languages) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type UserPreferences struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Description *string                `protobuf:"bytes,1,opt,name=description"`
	xxx_hidden_DisplayName *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName"`
	xxx_hidden_Avatar      *string                `protobuf:"bytes,3,opt,name=avatar"`
	xxx_hidden_Lang        Languages              `protobuf:"varint,4,opt,name=lang,enum=xyz.city_ideas.v1.user.v1.Languages"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserPreferences) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *UserPreferences) GetDisplayName() string {
	if x != nil {
		if x.xxx_hidden_DisplayName != nil {
			return *x.xxx_hidden_DisplayName
		}
		return ""
	}
	return ""
}

func (x *UserPreferences) GetAvatar() string {
	if x != nil {
		if x.xxx_hidden_Avatar != nil {
			return *x.xxx_hidden_Avatar
		}
		return ""
	}
	return ""
}

func (x *UserPreferences) GetLang() Languages {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_Lang
		}
	}
	return Languages_LANGUAGES_UNSPECIFIED
}

func (x *UserPreferences) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *UserPreferences) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *UserPreferences) SetAvatar(v string) {
	x.xxx_hidden_Avatar = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *UserPreferences) SetLang(v Languages) {
	x.xxx_hidden_Lang = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *UserPreferences) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserPreferences) HasDisplayName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserPreferences) HasAvatar() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UserPreferences) HasLang() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UserPreferences) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Description = nil
}

func (x *UserPreferences) ClearDisplayName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DisplayName = nil
}

func (x *UserPreferences) ClearAvatar() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Avatar = nil
}

func (x *UserPreferences) ClearLang() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Lang = Languages_LANGUAGES_UNSPECIFIED
}

type UserPreferences_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Description *string
	DisplayName *string
	Avatar      *string
	Lang        *Languages
}

func (b0 UserPreferences_builder) Build() *UserPreferences {
	m0 := &UserPreferences{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Description = b.Description
	}
	if b.DisplayName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_DisplayName = b.DisplayName
	}
	if b.Avatar != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Avatar = b.Avatar
	}
	if b.Lang != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Lang = *b.Lang
	}
	return m0
}

type UserRank struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Color       int64                  `protobuf:"varint,2,opt,name=color"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserRank) Reset() {
	*x = UserRank{}
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRank) ProtoMessage() {}

func (x *UserRank) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserRank) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *UserRank) GetColor() int64 {
	if x != nil {
		return x.xxx_hidden_Color
	}
	return 0
}

func (x *UserRank) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UserRank) SetColor(v int64) {
	x.xxx_hidden_Color = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *UserRank) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserRank) HasColor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserRank) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *UserRank) ClearColor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Color = 0
}

type UserRank_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name  *string
	Color *int64
}

func (b0 UserRank_builder) Build() *UserRank {
	m0 := &UserRank{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.Color != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Color = *b.Color
	}
	return m0
}

type PublicUser struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Username    *string                `protobuf:"bytes,2,opt,name=username"`
	xxx_hidden_Joined      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=joined"`
	xxx_hidden_Prefs       *UserPreferences       `protobuf:"bytes,4,opt,name=prefs"`
	xxx_hidden_Rank        *UserRank              `protobuf:"bytes,5,opt,name=rank"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PublicUser) Reset() {
	*x = PublicUser{}
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicUser) ProtoMessage() {}

func (x *PublicUser) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicUser) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *PublicUser) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *PublicUser) GetJoined() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Joined
	}
	return nil
}

func (x *PublicUser) GetPrefs() *UserPreferences {
	if x != nil {
		return x.xxx_hidden_Prefs
	}
	return nil
}

func (x *PublicUser) GetRank() *UserRank {
	if x != nil {
		return x.xxx_hidden_Rank
	}
	return nil
}

func (x *PublicUser) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *PublicUser) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *PublicUser) SetJoined(v *timestamppb.Timestamp) {
	x.xxx_hidden_Joined = v
}

func (x *PublicUser) SetPrefs(v *UserPreferences) {
	x.xxx_hidden_Prefs = v
}

func (x *PublicUser) SetRank(v *UserRank) {
	x.xxx_hidden_Rank = v
}

func (x *PublicUser) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PublicUser) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PublicUser) HasJoined() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Joined != nil
}

func (x *PublicUser) HasPrefs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Prefs != nil
}

func (x *PublicUser) HasRank() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Rank != nil
}

func (x *PublicUser) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *PublicUser) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Username = nil
}

func (x *PublicUser) ClearJoined() {
	x.xxx_hidden_Joined = nil
}

func (x *PublicUser) ClearPrefs() {
	x.xxx_hidden_Prefs = nil
}

func (x *PublicUser) ClearRank() {
	x.xxx_hidden_Rank = nil
}

type PublicUser_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       *string
	Username *string
	Joined   *timestamppb.Timestamp
	Prefs    *UserPreferences
	Rank     *UserRank
}

func (b0 PublicUser_builder) Build() *PublicUser {
	m0 := &PublicUser{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Username = b.Username
	}
	x.xxx_hidden_Joined = b.Joined
	x.xxx_hidden_Prefs = b.Prefs
	x.xxx_hidden_Rank = b.Rank
	return m0
}

type PrivateUser struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Public      *PublicUser            `protobuf:"bytes,1,opt,name=public"`
	xxx_hidden_SessionLive int32                  `protobuf:"varint,2,opt,name=session_live,json=sessionLive"`
	xxx_hidden_Email       *string                `protobuf:"bytes,3,opt,name=email"`
	xxx_hidden_Permissions []string               `protobuf:"bytes,4,rep,name=permissions"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PrivateUser) Reset() {
	*x = PrivateUser{}
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateUser) ProtoMessage() {}

func (x *PrivateUser) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrivateUser) GetPublic() *PublicUser {
	if x != nil {
		return x.xxx_hidden_Public
	}
	return nil
}

func (x *PrivateUser) GetSessionLive() int32 {
	if x != nil {
		return x.xxx_hidden_SessionLive
	}
	return 0
}

func (x *PrivateUser) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *PrivateUser) GetPermissions() []string {
	if x != nil {
		return x.xxx_hidden_Permissions
	}
	return nil
}

func (x *PrivateUser) SetPublic(v *PublicUser) {
	x.xxx_hidden_Public = v
}

func (x *PrivateUser) SetSessionLive(v int32) {
	x.xxx_hidden_SessionLive = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *PrivateUser) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *PrivateUser) SetPermissions(v []string) {
	x.xxx_hidden_Permissions = v
}

func (x *PrivateUser) HasPublic() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Public != nil
}

func (x *PrivateUser) HasSessionLive() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PrivateUser) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PrivateUser) ClearPublic() {
	x.xxx_hidden_Public = nil
}

func (x *PrivateUser) ClearSessionLive() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SessionLive = 0
}

func (x *PrivateUser) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Email = nil
}

type PrivateUser_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Public      *PublicUser
	SessionLive *int32
	Email       *string
	Permissions []string
}

func (b0 PrivateUser_builder) Build() *PrivateUser {
	m0 := &PrivateUser{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Public = b.Public
	if b.SessionLive != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_SessionLive = *b.SessionLive
	}
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Email = b.Email
	}
	x.xxx_hidden_Permissions = b.Permissions
	return m0
}

type UpdatePreferencesRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DisplayName     *string                `protobuf:"bytes,1,opt,name=display_name,json=displayName"`
	xxx_hidden_Description     *string                `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_AvatarHash      *string                `protobuf:"bytes,3,opt,name=avatar_hash,json=avatarHash"`
	xxx_hidden_SessionLiveTime int32                  `protobuf:"varint,4,opt,name=session_live_time,json=sessionLiveTime"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdatePreferencesRequest) GetDisplayName() string {
	if x != nil {
		if x.xxx_hidden_DisplayName != nil {
			return *x.xxx_hidden_DisplayName
		}
		return ""
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetAvatarHash() string {
	if x != nil {
		if x.xxx_hidden_AvatarHash != nil {
			return *x.xxx_hidden_AvatarHash
		}
		return ""
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetSessionLiveTime() int32 {
	if x != nil {
		return x.xxx_hidden_SessionLiveTime
	}
	return 0
}

func (x *UpdatePreferencesRequest) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *UpdatePreferencesRequest) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *UpdatePreferencesRequest) SetAvatarHash(v string) {
	x.xxx_hidden_AvatarHash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *UpdatePreferencesRequest) SetSessionLiveTime(v int32) {
	x.xxx_hidden_SessionLiveTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *UpdatePreferencesRequest) HasDisplayName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdatePreferencesRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdatePreferencesRequest) HasAvatarHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdatePreferencesRequest) HasSessionLiveTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UpdatePreferencesRequest) ClearDisplayName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DisplayName = nil
}

func (x *UpdatePreferencesRequest) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Description = nil
}

func (x *UpdatePreferencesRequest) ClearAvatarHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_AvatarHash = nil
}

func (x *UpdatePreferencesRequest) ClearSessionLiveTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_SessionLiveTime = 0
}

type UpdatePreferencesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DisplayName     *string
	Description     *string
	AvatarHash      *string
	SessionLiveTime *int32
}

func (b0 UpdatePreferencesRequest_builder) Build() *UpdatePreferencesRequest {
	m0 := &UpdatePreferencesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DisplayName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_DisplayName = b.DisplayName
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Description = b.Description
	}
	if b.AvatarHash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_AvatarHash = b.AvatarHash
	}
	if b.SessionLiveTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_SessionLiveTime = *b.SessionLiveTime
	}
	return m0
}

type ListResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_List *[]*PublicUser         `protobuf:"bytes,1,rep,name=list"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListResponse) GetList() []*PublicUser {
	if x != nil {
		if x.xxx_hidden_List != nil {
			return *x.xxx_hidden_List
		}
	}
	return nil
}

func (x *ListResponse) SetList(v []*PublicUser) {
	x.xxx_hidden_List = &v
}

type ListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	List []*PublicUser
}

func (b0 ListResponse_builder) Build() *ListResponse {
	m0 := &ListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_List = &b.List
	return m0
}

var File_xyz_city_ideas_v1_user_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_user_v1_domain_proto_rawDesc = "" +
	"\n" +
	"&xyz/city_ideas/v1/user/v1/domain.proto\x12\x19xyz.city_ideas.v1.user.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x01\n" +
	"\x0fUserPreferences\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x128\n" +
	"\x04lang\x18\x04 \x01(\x0e2$.xyz.city_ideas.v1.user.v1.LanguagesR\x04lang\"4\n" +
	"\bUserRank\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x02 \x01(\x03R\x05color\"\xe7\x01\n" +
	"\n" +
	"PublicUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x122\n" +
	"\x06joined\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06joined\x12@\n" +
	"\x05prefs\x18\x04 \x01(\v2*.xyz.city_ideas.v1.user.v1.UserPreferencesR\x05prefs\x127\n" +
	"\x04rank\x18\x05 \x01(\v2#.xyz.city_ideas.v1.user.v1.UserRankR\x04rank\"\xa7\x01\n" +
	"\vPrivateUser\x12=\n" +
	"\x06public\x18\x01 \x01(\v2%.xyz.city_ideas.v1.user.v1.PublicUserR\x06public\x12!\n" +
	"\fsession_live\x18\x02 \x01(\x05R\vsessionLive\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\"\xac\x01\n" +
	"\x18UpdatePreferencesRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vavatar_hash\x18\x03 \x01(\tR\n" +
	"avatarHash\x12*\n" +
	"\x11session_live_time\x18\x04 \x01(\x05R\x0fsessionLiveTime\"I\n" +
	"\fListResponse\x129\n" +
	"\x04list\x18\x01 \x03(\v2%.xyz.city_ideas.v1.user.v1.PublicUserR\x04list*T\n" +
	"\tLanguages\x12\x19\n" +
	"\x15LANGUAGES_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LANGUAGES_RUSSIAN\x10\x01\x12\x15\n" +
	"\x11LANGUAGES_ENGLISH\x10\x02BCZAgithub.com/aesterial/cityideas/backend/internal/api/v1/user/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_user_v1_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_xyz_city_ideas_v1_user_v1_domain_proto_goTypes = []any{
	(Languages)(0),                   // 0: xyz.city_ideas.v1.user.v1.Languages
	(*UserPreferences)(nil),          // 1: xyz.city_ideas.v1.user.v1.UserPreferences
	(*UserRank)(nil),                 // 2: xyz.city_ideas.v1.user.v1.UserRank
	(*PublicUser)(nil),               // 3: xyz.city_ideas.v1.user.v1.PublicUser
	(*PrivateUser)(nil),              // 4: xyz.city_ideas.v1.user.v1.PrivateUser
	(*UpdatePreferencesRequest)(nil), // 5: xyz.city_ideas.v1.user.v1.UpdatePreferencesRequest
	(*ListResponse)(nil),             // 6: xyz.city_ideas.v1.user.v1.ListResponse
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_xyz_city_ideas_v1_user_v1_domain_proto_depIdxs = []int32{
	0, // 0: xyz.city_ideas.v1.user.v1.UserPreferences.lang:type_name -> xyz.city_ideas.v1.user.v1.Languages
	7, // 1: xyz.city_ideas.v1.user.v1.PublicUser.joined:type_name -> google.protobuf.Timestamp
	1, // 2: xyz.city_ideas.v1.user.v1.PublicUser.prefs:type_name -> xyz.city_ideas.v1.user.v1.UserPreferences
	2, // 3: xyz.city_ideas.v1.user.v1.PublicUser.rank:type_name -> xyz.city_ideas.v1.user.v1.UserRank
	3, // 4: xyz.city_ideas.v1.user.v1.PrivateUser.public:type_name -> xyz.city_ideas.v1.user.v1.PublicUser
	3, // 5: xyz.city_ideas.v1.user.v1.ListResponse.list:type_name -> xyz.city_ideas.v1.user.v1.PublicUser
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_user_v1_domain_proto_init() }
func file_xyz_city_ideas_v1_user_v1_domain_proto_init() {
	if File_xyz_city_ideas_v1_user_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_user_v1_domain_proto_rawDesc), len(file_xyz_city_ideas_v1_user_v1_domain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_city_ideas_v1_user_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_user_v1_domain_proto_depIdxs,
		EnumInfos:         file_xyz_city_ideas_v1_user_v1_domain_proto_enumTypes,
		MessageInfos:      file_xyz_city_ideas_v1_user_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_city_ideas_v1_user_v1_domain_proto = out.File
	file_xyz_city_ideas_v1_user_v1_domain_proto_goTypes = nil
	file_xyz_city_ideas_v1_user_v1_domain_proto_depIdxs = nil
}
