// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz.city_ideas.v1/user/v1/service.proto

package v1

import (
	v1 "github.com/aesterial/cityideas/backend/internal/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xyz_city_ideas_v1_user_v1_service_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_user_v1_service_proto_rawDesc = "" +
	"\n" +
	"'xyz.city_ideas.v1/user/v1/service.proto\x12\x19xyz.city_ideas.v1.user.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dxyz.city_ideas.v1/types.proto\x1a&xyz.city_ideas.v1/user/v1/domain.proto2\xa9\x01\n" +
	"\vUserService\x12R\n" +
	"\x04Info\x12#.xyz.city_ideas.v1.RequestWithValue\x1a%.xyz.city_ideas.v1.user.v1.PublicUser\x12F\n" +
	"\x04Self\x12\x16.google.protobuf.Empty\x1a&.xyz.city_ideas.v1.user.v1.PrivateUserBCZAgithub.com/aesterial/cityideas/backend/internal/api/v1/user/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_user_v1_service_proto_goTypes = []any{
	(*v1.RequestWithValue)(nil), // 0: xyz.city_ideas.v1.RequestWithValue
	(*emptypb.Empty)(nil),       // 1: google.protobuf.Empty
	(*PublicUser)(nil),          // 2: xyz.city_ideas.v1.user.v1.PublicUser
	(*PrivateUser)(nil),         // 3: xyz.city_ideas.v1.user.v1.PrivateUser
}
var file_xyz_city_ideas_v1_user_v1_service_proto_depIdxs = []int32{
	0, // 0: xyz.city_ideas.v1.user.v1.UserService.Info:input_type -> xyz.city_ideas.v1.RequestWithValue
	1, // 1: xyz.city_ideas.v1.user.v1.UserService.Self:input_type -> google.protobuf.Empty
	2, // 2: xyz.city_ideas.v1.user.v1.UserService.Info:output_type -> xyz.city_ideas.v1.user.v1.PublicUser
	3, // 3: xyz.city_ideas.v1.user.v1.UserService.Self:output_type -> xyz.city_ideas.v1.user.v1.PrivateUser
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_user_v1_service_proto_init() }
func file_xyz_city_ideas_v1_user_v1_service_proto_init() {
	if File_xyz_city_ideas_v1_user_v1_service_proto != nil {
		return
	}
	file_xyz_city_ideas_v1_user_v1_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_user_v1_service_proto_rawDesc), len(file_xyz_city_ideas_v1_user_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_city_ideas_v1_user_v1_service_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_user_v1_service_proto_depIdxs,
	}.Build()
	File_xyz_city_ideas_v1_user_v1_service_proto = out.File
	file_xyz_city_ideas_v1_user_v1_service_proto_goTypes = nil
	file_xyz_city_ideas_v1_user_v1_service_proto_depIdxs = nil
}
