// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/city_ideas/v1/login/v1/domain.proto

package v1

import (
	v1 "github.com/aesterial/cityideas/backend/internal/api/v1/user/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reset int32

const (
	Reset_RESET_UNSPECIFIED Reset = 0
	Reset_RESET_EMAIL       Reset = 1
	Reset_RESET_RECOVERY    Reset = 2
)

// Enum value maps for Reset.
var (
	Reset_name = map[int32]string{
		0: "RESET_UNSPECIFIED",
		1: "RESET_EMAIL",
		2: "RESET_RECOVERY",
	}
	Reset_value = map[string]int32{
		"RESET_UNSPECIFIED": 0,
		"RESET_EMAIL":       1,
		"RESET_RECOVERY":    2,
	}
)

func (x Reset) Enum() *Reset {
	p := new(Reset)
	*p = x
	return p
}

func (x Reset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reset) Descriptor() protoreflect.EnumDescriptor {
	return file_xyz_city_ideas_v1_login_v1_domain_proto_enumTypes[0].Descriptor()
}

func (Reset) Type() protoreflect.EnumType {
	return &file_xyz_city_ideas_v1_login_v1_domain_proto_enumTypes[0]
}

func (x Reset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type RegisterRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Username    *string                `protobuf:"bytes,1,opt,name=username"`
	xxx_hidden_Email       *string                `protobuf:"bytes,2,opt,name=email"`
	xxx_hidden_Password    *string                `protobuf:"bytes,3,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RegisterRequest) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RegisterRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *RegisterRequest) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterRequest) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RegisterRequest) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Username = nil
}

func (x *RegisterRequest) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Email = nil
}

func (x *RegisterRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Password = nil
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Username *string
	Email    *string
	Password *string
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Username = b.Username
	}
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Email = b.Email
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type AuthorizeRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserMail    *string                `protobuf:"bytes,1,opt,name=user_mail,json=userMail"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthorizeRequest) GetUserMail() string {
	if x != nil {
		if x.xxx_hidden_UserMail != nil {
			return *x.xxx_hidden_UserMail
		}
		return ""
	}
	return ""
}

func (x *AuthorizeRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *AuthorizeRequest) SetUserMail(v string) {
	x.xxx_hidden_UserMail = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AuthorizeRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AuthorizeRequest) HasUserMail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthorizeRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuthorizeRequest) ClearUserMail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_UserMail = nil
}

func (x *AuthorizeRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type AuthorizeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserMail *string
	Password *string
}

func (b0 AuthorizeRequest_builder) Build() *AuthorizeRequest {
	m0 := &AuthorizeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.UserMail != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_UserMail = b.UserMail
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type LoginResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Info *v1.PrivateUser        `protobuf:"bytes,1,opt,name=info"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetInfo() *v1.PrivateUser {
	if x != nil {
		return x.xxx_hidden_Info
	}
	return nil
}

func (x *LoginResponse) SetInfo(v *v1.PrivateUser) {
	x.xxx_hidden_Info = v
}

func (x *LoginResponse) HasInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Info != nil
}

func (x *LoginResponse) ClearInfo() {
	x.xxx_hidden_Info = nil
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Info *v1.PrivateUser
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Info = b.Info
	return m0
}

type CreateTotpResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Qr          *string                `protobuf:"bytes,1,opt,name=qr"`
	xxx_hidden_Url         *string                `protobuf:"bytes,2,opt,name=url"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateTotpResponse) Reset() {
	*x = CreateTotpResponse{}
	mi := &file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTotpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTotpResponse) ProtoMessage() {}

func (x *CreateTotpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateTotpResponse) GetQr() string {
	if x != nil {
		if x.xxx_hidden_Qr != nil {
			return *x.xxx_hidden_Qr
		}
		return ""
	}
	return ""
}

func (x *CreateTotpResponse) GetUrl() string {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
		return ""
	}
	return ""
}

func (x *CreateTotpResponse) SetQr(v string) {
	x.xxx_hidden_Qr = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateTotpResponse) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CreateTotpResponse) HasQr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateTotpResponse) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateTotpResponse) ClearQr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Qr = nil
}

func (x *CreateTotpResponse) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Url = nil
}

type CreateTotpResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Qr  *string
	Url *string
}

func (b0 CreateTotpResponse_builder) Build() *CreateTotpResponse {
	m0 := &CreateTotpResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Qr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Qr = b.Qr
	}
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Url = b.Url
	}
	return m0
}

type ConfirmTotpResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Codes []string               `protobuf:"bytes,1,rep,name=codes"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfirmTotpResponse) Reset() {
	*x = ConfirmTotpResponse{}
	mi := &file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTotpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTotpResponse) ProtoMessage() {}

func (x *ConfirmTotpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfirmTotpResponse) GetCodes() []string {
	if x != nil {
		return x.xxx_hidden_Codes
	}
	return nil
}

func (x *ConfirmTotpResponse) SetCodes(v []string) {
	x.xxx_hidden_Codes = v
}

type ConfirmTotpResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Codes []string
}

func (b0 ConfirmTotpResponse_builder) Build() *ConfirmTotpResponse {
	m0 := &ConfirmTotpResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Codes = b.Codes
	return m0
}

type ResetTotpRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind        Reset                  `protobuf:"varint,1,opt,name=kind,enum=xyz.city_ideas.v1.login.v1.Reset"`
	xxx_hidden_Code        *string                `protobuf:"bytes,2,opt,name=code"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResetTotpRequest) Reset() {
	*x = ResetTotpRequest{}
	mi := &file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetTotpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetTotpRequest) ProtoMessage() {}

func (x *ResetTotpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResetTotpRequest) GetKind() Reset {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Kind
		}
	}
	return Reset_RESET_UNSPECIFIED
}

func (x *ResetTotpRequest) GetCode() string {
	if x != nil {
		if x.xxx_hidden_Code != nil {
			return *x.xxx_hidden_Code
		}
		return ""
	}
	return ""
}

func (x *ResetTotpRequest) SetKind(v Reset) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ResetTotpRequest) SetCode(v string) {
	x.xxx_hidden_Code = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ResetTotpRequest) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ResetTotpRequest) HasCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ResetTotpRequest) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Kind = Reset_RESET_UNSPECIFIED
}

func (x *ResetTotpRequest) ClearCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Code = nil
}

type ResetTotpRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Kind *Reset
	Code *string
}

func (b0 ResetTotpRequest_builder) Build() *ResetTotpRequest {
	m0 := &ResetTotpRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Kind = *b.Kind
	}
	if b.Code != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Code = b.Code
	}
	return m0
}

var File_xyz_city_ideas_v1_login_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_login_v1_domain_proto_rawDesc = "" +
	"\n" +
	"'xyz/city_ideas/v1/login/v1/domain.proto\x12\x1axyz.city_ideas.v1.login.v1\x1a&xyz/city_ideas/v1/user/v1/domain.proto\"_\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"K\n" +
	"\x10AuthorizeRequest\x12\x1b\n" +
	"\tuser_mail\x18\x01 \x01(\tR\buserMail\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"K\n" +
	"\rLoginResponse\x12:\n" +
	"\x04info\x18\x01 \x01(\v2&.xyz.city_ideas.v1.user.v1.PrivateUserR\x04info\"6\n" +
	"\x12CreateTotpResponse\x12\x0e\n" +
	"\x02qr\x18\x01 \x01(\tR\x02qr\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"+\n" +
	"\x13ConfirmTotpResponse\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"]\n" +
	"\x10ResetTotpRequest\x125\n" +
	"\x04kind\x18\x01 \x01(\x0e2!.xyz.city_ideas.v1.login.v1.ResetR\x04kind\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code*C\n" +
	"\x05Reset\x12\x15\n" +
	"\x11RESET_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vRESET_EMAIL\x10\x01\x12\x12\n" +
	"\x0eRESET_RECOVERY\x10\x02BDZBgithub.com/aesterial/cityideas/backend/internal/api/v1/login/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_login_v1_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_xyz_city_ideas_v1_login_v1_domain_proto_goTypes = []any{
	(Reset)(0),                  // 0: xyz.city_ideas.v1.login.v1.Reset
	(*RegisterRequest)(nil),     // 1: xyz.city_ideas.v1.login.v1.RegisterRequest
	(*AuthorizeRequest)(nil),    // 2: xyz.city_ideas.v1.login.v1.AuthorizeRequest
	(*LoginResponse)(nil),       // 3: xyz.city_ideas.v1.login.v1.LoginResponse
	(*CreateTotpResponse)(nil),  // 4: xyz.city_ideas.v1.login.v1.CreateTotpResponse
	(*ConfirmTotpResponse)(nil), // 5: xyz.city_ideas.v1.login.v1.ConfirmTotpResponse
	(*ResetTotpRequest)(nil),    // 6: xyz.city_ideas.v1.login.v1.ResetTotpRequest
	(*v1.PrivateUser)(nil),      // 7: xyz.city_ideas.v1.user.v1.PrivateUser
}
var file_xyz_city_ideas_v1_login_v1_domain_proto_depIdxs = []int32{
	7, // 0: xyz.city_ideas.v1.login.v1.LoginResponse.info:type_name -> xyz.city_ideas.v1.user.v1.PrivateUser
	0, // 1: xyz.city_ideas.v1.login.v1.ResetTotpRequest.kind:type_name -> xyz.city_ideas.v1.login.v1.Reset
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_login_v1_domain_proto_init() }
func file_xyz_city_ideas_v1_login_v1_domain_proto_init() {
	if File_xyz_city_ideas_v1_login_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_login_v1_domain_proto_rawDesc), len(file_xyz_city_ideas_v1_login_v1_domain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_city_ideas_v1_login_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_login_v1_domain_proto_depIdxs,
		EnumInfos:         file_xyz_city_ideas_v1_login_v1_domain_proto_enumTypes,
		MessageInfos:      file_xyz_city_ideas_v1_login_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_city_ideas_v1_login_v1_domain_proto = out.File
	file_xyz_city_ideas_v1_login_v1_domain_proto_goTypes = nil
	file_xyz_city_ideas_v1_login_v1_domain_proto_depIdxs = nil
}
