// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/city_ideas/v1/login/v1/service.proto

package v1

import (
	v1 "github.com/aesterial/cityideas/backend/internal/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xyz_city_ideas_v1_login_v1_service_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_login_v1_service_proto_rawDesc = "" +
	"\n" +
	"(xyz/city_ideas/v1/login/v1/service.proto\x12\x1axyz.city_ideas.v1.login.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a'xyz/city_ideas/v1/login/v1/domain.proto\x1a\x1dxyz/city_ideas/v1/types.proto2\xfc\a\n" +
	"\fLoginService\x12b\n" +
	"\bRegister\x12+.xyz.city_ideas.v1.login.v1.RegisterRequest\x1a).xyz.city_ideas.v1.login.v1.LoginResponse\x12d\n" +
	"\tAuthorize\x12,.xyz.city_ideas.v1.login.v1.AuthorizeRequest\x1a).xyz.city_ideas.v1.login.v1.LoginResponse\x128\n" +
	"\x06Logout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\n" +
	"CreateTotp\x12\x16.google.protobuf.Empty\x1a..xyz.city_ideas.v1.login.v1.CreateTotpResponse\x12c\n" +
	"\vConfirmTotp\x12#.xyz.city_ideas.v1.RequestWithValue\x1a/.xyz.city_ideas.v1.login.v1.ConfirmTotpResponse\x12H\n" +
	"\tCheckTotp\x12#.xyz.city_ideas.v1.RequestWithValue\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\tResetTotp\x12,.xyz.city_ideas.v1.login.v1.ResetTotpRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\aVkStart\x12*.xyz.city_ideas.v1.login.v1.VkStartRequest\x1a#.xyz.city_ideas.v1.RequestWithValue\x12k\n" +
	"\n" +
	"VkCallback\x12-.xyz.city_ideas.v1.login.v1.VkCallbackRequest\x1a..xyz.city_ideas.v1.login.v1.VkCallbackResponse\x12Z\n" +
	"\aTgStart\x12*.xyz.city_ideas.v1.login.v1.TgStartRequest\x1a#.xyz.city_ideas.v1.RequestWithValue\x12k\n" +
	"\n" +
	"TgCallback\x12-.xyz.city_ideas.v1.login.v1.TgCallbackRequest\x1a..xyz.city_ideas.v1.login.v1.VkCallbackResponseBDZBgithub.com/aesterial/cityideas/backend/internal/api/v1/login/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_login_v1_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),     // 0: xyz.city_ideas.v1.login.v1.RegisterRequest
	(*AuthorizeRequest)(nil),    // 1: xyz.city_ideas.v1.login.v1.AuthorizeRequest
	(*emptypb.Empty)(nil),       // 2: google.protobuf.Empty
	(*v1.RequestWithValue)(nil), // 3: xyz.city_ideas.v1.RequestWithValue
	(*ResetTotpRequest)(nil),    // 4: xyz.city_ideas.v1.login.v1.ResetTotpRequest
	(*VkStartRequest)(nil),      // 5: xyz.city_ideas.v1.login.v1.VkStartRequest
	(*VkCallbackRequest)(nil),   // 6: xyz.city_ideas.v1.login.v1.VkCallbackRequest
	(*TgStartRequest)(nil),      // 7: xyz.city_ideas.v1.login.v1.TgStartRequest
	(*TgCallbackRequest)(nil),   // 8: xyz.city_ideas.v1.login.v1.TgCallbackRequest
	(*LoginResponse)(nil),       // 9: xyz.city_ideas.v1.login.v1.LoginResponse
	(*CreateTotpResponse)(nil),  // 10: xyz.city_ideas.v1.login.v1.CreateTotpResponse
	(*ConfirmTotpResponse)(nil), // 11: xyz.city_ideas.v1.login.v1.ConfirmTotpResponse
	(*VkCallbackResponse)(nil),  // 12: xyz.city_ideas.v1.login.v1.VkCallbackResponse
}
var file_xyz_city_ideas_v1_login_v1_service_proto_depIdxs = []int32{
	0,  // 0: xyz.city_ideas.v1.login.v1.LoginService.Register:input_type -> xyz.city_ideas.v1.login.v1.RegisterRequest
	1,  // 1: xyz.city_ideas.v1.login.v1.LoginService.Authorize:input_type -> xyz.city_ideas.v1.login.v1.AuthorizeRequest
	2,  // 2: xyz.city_ideas.v1.login.v1.LoginService.Logout:input_type -> google.protobuf.Empty
	2,  // 3: xyz.city_ideas.v1.login.v1.LoginService.CreateTotp:input_type -> google.protobuf.Empty
	3,  // 4: xyz.city_ideas.v1.login.v1.LoginService.ConfirmTotp:input_type -> xyz.city_ideas.v1.RequestWithValue
	3,  // 5: xyz.city_ideas.v1.login.v1.LoginService.CheckTotp:input_type -> xyz.city_ideas.v1.RequestWithValue
	4,  // 6: xyz.city_ideas.v1.login.v1.LoginService.ResetTotp:input_type -> xyz.city_ideas.v1.login.v1.ResetTotpRequest
	5,  // 7: xyz.city_ideas.v1.login.v1.LoginService.VkStart:input_type -> xyz.city_ideas.v1.login.v1.VkStartRequest
	6,  // 8: xyz.city_ideas.v1.login.v1.LoginService.VkCallback:input_type -> xyz.city_ideas.v1.login.v1.VkCallbackRequest
	7,  // 9: xyz.city_ideas.v1.login.v1.LoginService.TgStart:input_type -> xyz.city_ideas.v1.login.v1.TgStartRequest
	8,  // 10: xyz.city_ideas.v1.login.v1.LoginService.TgCallback:input_type -> xyz.city_ideas.v1.login.v1.TgCallbackRequest
	9,  // 11: xyz.city_ideas.v1.login.v1.LoginService.Register:output_type -> xyz.city_ideas.v1.login.v1.LoginResponse
	9,  // 12: xyz.city_ideas.v1.login.v1.LoginService.Authorize:output_type -> xyz.city_ideas.v1.login.v1.LoginResponse
	2,  // 13: xyz.city_ideas.v1.login.v1.LoginService.Logout:output_type -> google.protobuf.Empty
	10, // 14: xyz.city_ideas.v1.login.v1.LoginService.CreateTotp:output_type -> xyz.city_ideas.v1.login.v1.CreateTotpResponse
	11, // 15: xyz.city_ideas.v1.login.v1.LoginService.ConfirmTotp:output_type -> xyz.city_ideas.v1.login.v1.ConfirmTotpResponse
	2,  // 16: xyz.city_ideas.v1.login.v1.LoginService.CheckTotp:output_type -> google.protobuf.Empty
	2,  // 17: xyz.city_ideas.v1.login.v1.LoginService.ResetTotp:output_type -> google.protobuf.Empty
	3,  // 18: xyz.city_ideas.v1.login.v1.LoginService.VkStart:output_type -> xyz.city_ideas.v1.RequestWithValue
	12, // 19: xyz.city_ideas.v1.login.v1.LoginService.VkCallback:output_type -> xyz.city_ideas.v1.login.v1.VkCallbackResponse
	3,  // 20: xyz.city_ideas.v1.login.v1.LoginService.TgStart:output_type -> xyz.city_ideas.v1.RequestWithValue
	12, // 21: xyz.city_ideas.v1.login.v1.LoginService.TgCallback:output_type -> xyz.city_ideas.v1.login.v1.VkCallbackResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_login_v1_service_proto_init() }
func file_xyz_city_ideas_v1_login_v1_service_proto_init() {
	if File_xyz_city_ideas_v1_login_v1_service_proto != nil {
		return
	}
	file_xyz_city_ideas_v1_login_v1_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_login_v1_service_proto_rawDesc), len(file_xyz_city_ideas_v1_login_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_city_ideas_v1_login_v1_service_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_login_v1_service_proto_depIdxs,
	}.Build()
	File_xyz_city_ideas_v1_login_v1_service_proto = out.File
	file_xyz_city_ideas_v1_login_v1_service_proto_goTypes = nil
	file_xyz_city_ideas_v1_login_v1_service_proto_depIdxs = nil
}
