// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/city_ideas/v1/projects/v1/domain.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED  Status = 0
	Status_STATUS_CANCELLED    Status = 1
	Status_STATUS_LISTING      Status = 2
	Status_STATUS_REVIEWING    Status = 3
	Status_STATUS_IMPLEMENTING Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_CANCELLED",
		2: "STATUS_LISTING",
		3: "STATUS_REVIEWING",
		4: "STATUS_IMPLEMENTING",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":  0,
		"STATUS_CANCELLED":    1,
		"STATUS_LISTING":      2,
		"STATUS_REVIEWING":    3,
		"STATUS_IMPLEMENTING": 4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_xyz_city_ideas_v1_projects_v1_domain_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_xyz_city_ideas_v1_projects_v1_domain_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Project struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Author      *string                `protobuf:"bytes,2,opt,name=author"`
	xxx_hidden_Title       *string                `protobuf:"bytes,3,opt,name=title"`
	xxx_hidden_Description *string                `protobuf:"bytes,4,opt,name=description"`
	xxx_hidden_Category    *string                `protobuf:"bytes,5,opt,name=category"`
	xxx_hidden_Status      Status                 `protobuf:"varint,6,opt,name=status,enum=xyz.city_ideas.v1.projects.v1.Status"`
	xxx_hidden_ImplLink    *string                `protobuf:"bytes,7,opt,name=impl_link,json=implLink"`
	xxx_hidden_Likes       int32                  `protobuf:"varint,8,opt,name=likes"`
	xxx_hidden_At          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=at"`
	xxx_hidden_Updated     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated"`
	xxx_hidden_Deleted     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=deleted"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Project) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Project) GetAuthor() string {
	if x != nil {
		if x.xxx_hidden_Author != nil {
			return *x.xxx_hidden_Author
		}
		return ""
	}
	return ""
}

func (x *Project) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *Project) GetCategory() string {
	if x != nil {
		if x.xxx_hidden_Category != nil {
			return *x.xxx_hidden_Category
		}
		return ""
	}
	return ""
}

func (x *Project) GetStatus() Status {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_Status
		}
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Project) GetImplLink() string {
	if x != nil {
		if x.xxx_hidden_ImplLink != nil {
			return *x.xxx_hidden_ImplLink
		}
		return ""
	}
	return ""
}

func (x *Project) GetLikes() int32 {
	if x != nil {
		return x.xxx_hidden_Likes
	}
	return 0
}

func (x *Project) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_At
	}
	return nil
}

func (x *Project) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Updated
	}
	return nil
}

func (x *Project) GetDeleted() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return nil
}

func (x *Project) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 11)
}

func (x *Project) SetAuthor(v string) {
	x.xxx_hidden_Author = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 11)
}

func (x *Project) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *Project) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *Project) SetCategory(v string) {
	x.xxx_hidden_Category = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 11)
}

func (x *Project) SetStatus(v Status) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 11)
}

func (x *Project) SetImplLink(v string) {
	x.xxx_hidden_ImplLink = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 11)
}

func (x *Project) SetLikes(v int32) {
	x.xxx_hidden_Likes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 11)
}

func (x *Project) SetAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_At = v
}

func (x *Project) SetUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Updated = v
}

func (x *Project) SetDeleted(v *timestamppb.Timestamp) {
	x.xxx_hidden_Deleted = v
}

func (x *Project) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Project) HasAuthor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Project) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Project) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Project) HasCategory() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Project) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Project) HasImplLink() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Project) HasLikes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Project) HasAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_At != nil
}

func (x *Project) HasUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Updated != nil
}

func (x *Project) HasDeleted() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Deleted != nil
}

func (x *Project) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Project) ClearAuthor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Author = nil
}

func (x *Project) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Title = nil
}

func (x *Project) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Description = nil
}

func (x *Project) ClearCategory() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Category = nil
}

func (x *Project) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Status = Status_STATUS_UNSPECIFIED
}

func (x *Project) ClearImplLink() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ImplLink = nil
}

func (x *Project) ClearLikes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Likes = 0
}

func (x *Project) ClearAt() {
	x.xxx_hidden_At = nil
}

func (x *Project) ClearUpdated() {
	x.xxx_hidden_Updated = nil
}

func (x *Project) ClearDeleted() {
	x.xxx_hidden_Deleted = nil
}

type Project_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          *string
	Author      *string
	Title       *string
	Description *string
	Category    *string
	Status      *Status
	ImplLink    *string
	Likes       *int32
	At          *timestamppb.Timestamp
	Updated     *timestamppb.Timestamp
	Deleted     *timestamppb.Timestamp
}

func (b0 Project_builder) Build() *Project {
	m0 := &Project{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 11)
		x.xxx_hidden_Id = b.Id
	}
	if b.Author != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 11)
		x.xxx_hidden_Author = b.Author
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_Description = b.Description
	}
	if b.Category != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 11)
		x.xxx_hidden_Category = b.Category
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 11)
		x.xxx_hidden_Status = *b.Status
	}
	if b.ImplLink != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 11)
		x.xxx_hidden_ImplLink = b.ImplLink
	}
	if b.Likes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 11)
		x.xxx_hidden_Likes = *b.Likes
	}
	x.xxx_hidden_At = b.At
	x.xxx_hidden_Updated = b.Updated
	x.xxx_hidden_Deleted = b.Deleted
	return m0
}

type Message struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Author      *string                `protobuf:"bytes,2,opt,name=author"`
	xxx_hidden_Parent      *string                `protobuf:"bytes,3,opt,name=parent"`
	xxx_hidden_Content     *string                `protobuf:"bytes,4,opt,name=content"`
	xxx_hidden_At          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=at"`
	xxx_hidden_Deleted     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Message) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Message) GetAuthor() string {
	if x != nil {
		if x.xxx_hidden_Author != nil {
			return *x.xxx_hidden_Author
		}
		return ""
	}
	return ""
}

func (x *Message) GetParent() string {
	if x != nil {
		if x.xxx_hidden_Parent != nil {
			return *x.xxx_hidden_Parent
		}
		return ""
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		if x.xxx_hidden_Content != nil {
			return *x.xxx_hidden_Content
		}
		return ""
	}
	return ""
}

func (x *Message) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_At
	}
	return nil
}

func (x *Message) GetDeleted() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return nil
}

func (x *Message) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *Message) SetAuthor(v string) {
	x.xxx_hidden_Author = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *Message) SetParent(v string) {
	x.xxx_hidden_Parent = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *Message) SetContent(v string) {
	x.xxx_hidden_Content = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *Message) SetAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_At = v
}

func (x *Message) SetDeleted(v *timestamppb.Timestamp) {
	x.xxx_hidden_Deleted = v
}

func (x *Message) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Message) HasAuthor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Message) HasParent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Message) HasContent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Message) HasAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_At != nil
}

func (x *Message) HasDeleted() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Deleted != nil
}

func (x *Message) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Message) ClearAuthor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Author = nil
}

func (x *Message) ClearParent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Parent = nil
}

func (x *Message) ClearContent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Content = nil
}

func (x *Message) ClearAt() {
	x.xxx_hidden_At = nil
}

func (x *Message) ClearDeleted() {
	x.xxx_hidden_Deleted = nil
}

type Message_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Author  *string
	Parent  *string
	Content *string
	At      *timestamppb.Timestamp
	Deleted *timestamppb.Timestamp
}

func (b0 Message_builder) Build() *Message {
	m0 := &Message{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Author != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Author = b.Author
	}
	if b.Parent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Parent = b.Parent
	}
	if b.Content != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Content = b.Content
	}
	x.xxx_hidden_At = b.At
	x.xxx_hidden_Deleted = b.Deleted
	return m0
}

type Submission struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Project     *string                `protobuf:"bytes,2,opt,name=project"`
	xxx_hidden_Approved    bool                   `protobuf:"varint,3,opt,name=approved"`
	xxx_hidden_Reason      *string                `protobuf:"bytes,4,opt,name=reason"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Submission) Reset() {
	*x = Submission{}
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Submission) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Submission) GetProject() string {
	if x != nil {
		if x.xxx_hidden_Project != nil {
			return *x.xxx_hidden_Project
		}
		return ""
	}
	return ""
}

func (x *Submission) GetApproved() bool {
	if x != nil {
		return x.xxx_hidden_Approved
	}
	return false
}

func (x *Submission) GetReason() string {
	if x != nil {
		if x.xxx_hidden_Reason != nil {
			return *x.xxx_hidden_Reason
		}
		return ""
	}
	return ""
}

func (x *Submission) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Submission) SetProject(v string) {
	x.xxx_hidden_Project = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Submission) SetApproved(v bool) {
	x.xxx_hidden_Approved = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Submission) SetReason(v string) {
	x.xxx_hidden_Reason = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Submission) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Submission) HasProject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Submission) HasApproved() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Submission) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Submission) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Submission) ClearProject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Project = nil
}

func (x *Submission) ClearApproved() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Approved = false
}

func (x *Submission) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Reason = nil
}

type Submission_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       *string
	Project  *string
	Approved *bool
	Reason   *string
}

func (b0 Submission_builder) Build() *Submission {
	m0 := &Submission{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = b.Id
	}
	if b.Project != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Project = b.Project
	}
	if b.Approved != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Approved = *b.Approved
	}
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Reason = b.Reason
	}
	return m0
}

type ProjectsListResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_List *[]*Project            `protobuf:"bytes,1,rep,name=list"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProjectsListResponse) Reset() {
	*x = ProjectsListResponse{}
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectsListResponse) ProtoMessage() {}

func (x *ProjectsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProjectsListResponse) GetList() []*Project {
	if x != nil {
		if x.xxx_hidden_List != nil {
			return *x.xxx_hidden_List
		}
	}
	return nil
}

func (x *ProjectsListResponse) SetList(v []*Project) {
	x.xxx_hidden_List = &v
}

type ProjectsListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	List []*Project
}

func (b0 ProjectsListResponse_builder) Build() *ProjectsListResponse {
	m0 := &ProjectsListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_List = &b.List
	return m0
}

type SubmissionsListResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_List *[]*Submission         `protobuf:"bytes,1,rep,name=list"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmissionsListResponse) Reset() {
	*x = SubmissionsListResponse{}
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionsListResponse) ProtoMessage() {}

func (x *SubmissionsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SubmissionsListResponse) GetList() []*Submission {
	if x != nil {
		if x.xxx_hidden_List != nil {
			return *x.xxx_hidden_List
		}
	}
	return nil
}

func (x *SubmissionsListResponse) SetList(v []*Submission) {
	x.xxx_hidden_List = &v
}

type SubmissionsListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	List []*Submission
}

func (b0 SubmissionsListResponse_builder) Build() *SubmissionsListResponse {
	m0 := &SubmissionsListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_List = &b.List
	return m0
}

type MessagesListResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_List *[]*Message            `protobuf:"bytes,1,rep,name=list"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessagesListResponse) Reset() {
	*x = MessagesListResponse{}
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesListResponse) ProtoMessage() {}

func (x *MessagesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MessagesListResponse) GetList() []*Message {
	if x != nil {
		if x.xxx_hidden_List != nil {
			return *x.xxx_hidden_List
		}
	}
	return nil
}

func (x *MessagesListResponse) SetList(v []*Message) {
	x.xxx_hidden_List = &v
}

type MessagesListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	List []*Message
}

func (b0 MessagesListResponse_builder) Build() *MessagesListResponse {
	m0 := &MessagesListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_List = &b.List
	return m0
}

type CreateProjectRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title       *string                `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Description *string                `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_Category    *string                `protobuf:"bytes,3,opt,name=category"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateProjectRequest) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *CreateProjectRequest) GetCategory() string {
	if x != nil {
		if x.xxx_hidden_Category != nil {
			return *x.xxx_hidden_Category
		}
		return ""
	}
	return ""
}

func (x *CreateProjectRequest) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *CreateProjectRequest) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CreateProjectRequest) SetCategory(v string) {
	x.xxx_hidden_Category = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CreateProjectRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateProjectRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateProjectRequest) HasCategory() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateProjectRequest) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Title = nil
}

func (x *CreateProjectRequest) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Description = nil
}

func (x *CreateProjectRequest) ClearCategory() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Category = nil
}

type CreateProjectRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title       *string
	Description *string
	Category    *string
}

func (b0 CreateProjectRequest_builder) Build() *CreateProjectRequest {
	m0 := &CreateProjectRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Description = b.Description
	}
	if b.Category != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Category = b.Category
	}
	return m0
}

type CreateMessageRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Project     *string                `protobuf:"bytes,1,opt,name=project"`
	xxx_hidden_Parent      *string                `protobuf:"bytes,2,opt,name=parent"`
	xxx_hidden_Content     *string                `protobuf:"bytes,3,opt,name=content"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateMessageRequest) GetProject() string {
	if x != nil {
		if x.xxx_hidden_Project != nil {
			return *x.xxx_hidden_Project
		}
		return ""
	}
	return ""
}

func (x *CreateMessageRequest) GetParent() string {
	if x != nil {
		if x.xxx_hidden_Parent != nil {
			return *x.xxx_hidden_Parent
		}
		return ""
	}
	return ""
}

func (x *CreateMessageRequest) GetContent() string {
	if x != nil {
		if x.xxx_hidden_Content != nil {
			return *x.xxx_hidden_Content
		}
		return ""
	}
	return ""
}

func (x *CreateMessageRequest) SetProject(v string) {
	x.xxx_hidden_Project = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *CreateMessageRequest) SetParent(v string) {
	x.xxx_hidden_Parent = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CreateMessageRequest) SetContent(v string) {
	x.xxx_hidden_Content = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CreateMessageRequest) HasProject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateMessageRequest) HasParent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateMessageRequest) HasContent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateMessageRequest) ClearProject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Project = nil
}

func (x *CreateMessageRequest) ClearParent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Parent = nil
}

func (x *CreateMessageRequest) ClearContent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Content = nil
}

type CreateMessageRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Project *string
	Parent  *string
	Content *string
}

func (b0 CreateMessageRequest_builder) Build() *CreateMessageRequest {
	m0 := &CreateMessageRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Project != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Project = b.Project
	}
	if b.Parent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Parent = b.Parent
	}
	if b.Content != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Content = b.Content
	}
	return m0
}

var File_xyz_city_ideas_v1_projects_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_projects_v1_domain_proto_rawDesc = "" +
	"\n" +
	"*xyz/city_ideas/v1/projects/v1/domain.proto\x12\x1dxyz.city_ideas.v1.projects.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x03\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12=\n" +
	"\x06status\x18\x06 \x01(\x0e2%.xyz.city_ideas.v1.projects.v1.StatusR\x06status\x12\x1b\n" +
	"\timpl_link\x18\a \x01(\tR\bimplLink\x12\x14\n" +
	"\x05likes\x18\b \x01(\x05R\x05likes\x12*\n" +
	"\x02at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x124\n" +
	"\aupdated\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aupdated\x124\n" +
	"\adeleted\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\adeleted\"\xc5\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12*\n" +
	"\x02at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x124\n" +
	"\adeleted\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\adeleted\"j\n" +
	"\n" +
	"Submission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"R\n" +
	"\x14ProjectsListResponse\x12:\n" +
	"\x04list\x18\x01 \x03(\v2&.xyz.city_ideas.v1.projects.v1.ProjectR\x04list\"X\n" +
	"\x17SubmissionsListResponse\x12=\n" +
	"\x04list\x18\x01 \x03(\v2).xyz.city_ideas.v1.projects.v1.SubmissionR\x04list\"R\n" +
	"\x14MessagesListResponse\x12:\n" +
	"\x04list\x18\x01 \x03(\v2&.xyz.city_ideas.v1.projects.v1.MessageR\x04list\"j\n" +
	"\x14CreateProjectRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"b\n" +
	"\x14CreateMessageRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\tR\x06parent\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent*y\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x01\x12\x12\n" +
	"\x0eSTATUS_LISTING\x10\x02\x12\x14\n" +
	"\x10STATUS_REVIEWING\x10\x03\x12\x17\n" +
	"\x13STATUS_IMPLEMENTING\x10\x04BGZEgithub.com/aesterial/cityideas/backend/internal/api/v1/projects/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_projects_v1_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_xyz_city_ideas_v1_projects_v1_domain_proto_goTypes = []any{
	(Status)(0),                     // 0: xyz.city_ideas.v1.projects.v1.Status
	(*Project)(nil),                 // 1: xyz.city_ideas.v1.projects.v1.Project
	(*Message)(nil),                 // 2: xyz.city_ideas.v1.projects.v1.Message
	(*Submission)(nil),              // 3: xyz.city_ideas.v1.projects.v1.Submission
	(*ProjectsListResponse)(nil),    // 4: xyz.city_ideas.v1.projects.v1.ProjectsListResponse
	(*SubmissionsListResponse)(nil), // 5: xyz.city_ideas.v1.projects.v1.SubmissionsListResponse
	(*MessagesListResponse)(nil),    // 6: xyz.city_ideas.v1.projects.v1.MessagesListResponse
	(*CreateProjectRequest)(nil),    // 7: xyz.city_ideas.v1.projects.v1.CreateProjectRequest
	(*CreateMessageRequest)(nil),    // 8: xyz.city_ideas.v1.projects.v1.CreateMessageRequest
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_xyz_city_ideas_v1_projects_v1_domain_proto_depIdxs = []int32{
	0, // 0: xyz.city_ideas.v1.projects.v1.Project.status:type_name -> xyz.city_ideas.v1.projects.v1.Status
	9, // 1: xyz.city_ideas.v1.projects.v1.Project.at:type_name -> google.protobuf.Timestamp
	9, // 2: xyz.city_ideas.v1.projects.v1.Project.updated:type_name -> google.protobuf.Timestamp
	9, // 3: xyz.city_ideas.v1.projects.v1.Project.deleted:type_name -> google.protobuf.Timestamp
	9, // 4: xyz.city_ideas.v1.projects.v1.Message.at:type_name -> google.protobuf.Timestamp
	9, // 5: xyz.city_ideas.v1.projects.v1.Message.deleted:type_name -> google.protobuf.Timestamp
	1, // 6: xyz.city_ideas.v1.projects.v1.ProjectsListResponse.list:type_name -> xyz.city_ideas.v1.projects.v1.Project
	3, // 7: xyz.city_ideas.v1.projects.v1.SubmissionsListResponse.list:type_name -> xyz.city_ideas.v1.projects.v1.Submission
	2, // 8: xyz.city_ideas.v1.projects.v1.MessagesListResponse.list:type_name -> xyz.city_ideas.v1.projects.v1.Message
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_projects_v1_domain_proto_init() }
func file_xyz_city_ideas_v1_projects_v1_domain_proto_init() {
	if File_xyz_city_ideas_v1_projects_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_projects_v1_domain_proto_rawDesc), len(file_xyz_city_ideas_v1_projects_v1_domain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_city_ideas_v1_projects_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_projects_v1_domain_proto_depIdxs,
		EnumInfos:         file_xyz_city_ideas_v1_projects_v1_domain_proto_enumTypes,
		MessageInfos:      file_xyz_city_ideas_v1_projects_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_city_ideas_v1_projects_v1_domain_proto = out.File
	file_xyz_city_ideas_v1_projects_v1_domain_proto_goTypes = nil
	file_xyz_city_ideas_v1_projects_v1_domain_proto_depIdxs = nil
}
