edition = "2023";

package xyz.city_ideas.v1.login.v1;

import "xyz/city_ideas/v1/user/v1/domain.proto";

option go_package = "github.com/aesterial/cityideas/backend/internal/api/v1/login/v1;v1";

enum Reset {
  RESET_UNSPECIFIED = 0;
  RESET_EMAIL = 1;
  RESET_RECOVERY = 2;
}

message RegisterRequest {
  string username = 1;
  string email = 2;
  string password = 3;
}

message AuthorizeRequest {
  string user_mail = 1;
  string password = 2;
}

message LoginResponse {
  xyz.city_ideas.v1.user.v1.PrivateUser info = 1;
}

message CreateTotpResponse {
  string qr = 1;
  string url = 2;
}

message ConfirmTotpResponse {
  repeated string codes = 1;
}

message ResetTotpRequest {
  Reset kind = 1;
  string code = 2;
}

message VkStartRequest {
  CallbackType type = 1;
}

message VkCallbackRequest {
  string state = 1;
  string code = 2;
}

enum CallbackType {
  CallbackType_UNSPECIFIED = 0;
  CallbackType_REGISTER = 1;
  CallbackType_AUTH = 2;
  CallbackType_LINK = 3;
}

message VkCallbackResponse {
  CallbackType type = 1;
  message RegisterInfo {
    string username = 1;
    string email = 2;
    string description = 3;
    string display_name = 4;
    string avatarUrl = 5;
  }
  RegisterInfo register = 2;
  xyz.city_ideas.v1.user.v1.PrivateUser auth = 3;
}

message TgStartRequest {
  CallbackType type = 1;
}

message TgCallbackRequest {
  string tg_auth_result = 1;
}
