edition = "2023";

package xyz.city_ideas.v1.tickets.v1;

import "xyz/city_ideas/v1/tickets/v1/domain.proto";

option go_package = "github.com/aesterial/cityideas/backend/internal/api/v1/tickets/v1;v1";

import "google/protobuf/empty.proto";
import "xyz/city_ideas/v1/types.proto";

service TicketService {
  rpc CreateTicket(xyz.city_ideas.v1.tickets.v1.CreateTicketRequest) returns (xyz.city_ideas.v1.tickets.v1.Ticket);
  rpc Info(xyz.city_ideas.v1.RequestWithValue) returns (xyz.city_ideas.v1.tickets.v1.Ticket);
  rpc SelfTickets(xyz.city_ideas.v1.RequestWithLimitAndOffset) returns (xyz.city_ideas.v1.tickets.v1.TicketListResponse);
  rpc TicketsList(xyz.city_ideas.v1.RequestWithLimitAndOffset) returns (xyz.city_ideas.v1.tickets.v1.TicketListResponse);
  rpc Accept(xyz.city_ideas.v1.RequestWithValue) returns (google.protobuf.Empty);
  rpc Close(xyz.city_ideas.v1.RequestWithValues) returns (google.protobuf.Empty);
  rpc CreateMessage(xyz.city_ideas.v1.RequestWithValues) returns (xyz.city_ideas.v1.tickets.v1.Message);
  rpc Messages(xyz.city_ideas.v1.RequestWithLimitAndOffsetAndValue) returns (xyz.city_ideas.v1.tickets.v1.MessageListResponse);
}
