// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeviceT string

const (
	DeviceTDesktop DeviceT = "desktop"
	DeviceTMobile  DeviceT = "mobile"
	DeviceTTablet  DeviceT = "tablet"
)

func (e *DeviceT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceT(s)
	case string:
		*e = DeviceT(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceT: %T", src)
	}
	return nil
}

type NullDeviceT struct {
	DeviceT DeviceT `json:"device_t"`
	Valid   bool    `json:"valid"` // Valid is true if DeviceT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceT) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceT), nil
}

func (e DeviceT) Valid() bool {
	switch e {
	case DeviceTDesktop,
		DeviceTMobile,
		DeviceTTablet:
		return true
	}
	return false
}

func AllDeviceTValues() []DeviceT {
	return []DeviceT{
		DeviceTDesktop,
		DeviceTMobile,
		DeviceTTablet,
	}
}

type MaintenancesStatus string

const (
	MaintenancesStatusExpected  MaintenancesStatus = "expected"
	MaintenancesStatusRunning   MaintenancesStatus = "running"
	MaintenancesStatusCompleted MaintenancesStatus = "completed"
)

func (e *MaintenancesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaintenancesStatus(s)
	case string:
		*e = MaintenancesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MaintenancesStatus: %T", src)
	}
	return nil
}

type NullMaintenancesStatus struct {
	MaintenancesStatus MaintenancesStatus `json:"maintenances_status"`
	Valid              bool               `json:"valid"` // Valid is true if MaintenancesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaintenancesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MaintenancesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaintenancesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaintenancesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaintenancesStatus), nil
}

func (e MaintenancesStatus) Valid() bool {
	switch e {
	case MaintenancesStatusExpected,
		MaintenancesStatusRunning,
		MaintenancesStatusCompleted:
		return true
	}
	return false
}

func AllMaintenancesStatusValues() []MaintenancesStatus {
	return []MaintenancesStatus{
		MaintenancesStatusExpected,
		MaintenancesStatusRunning,
		MaintenancesStatusCompleted,
	}
}

type MaintenancesType string

const (
	MaintenancesTypeEmergency MaintenancesType = "emergency"
	MaintenancesTypePlanned   MaintenancesType = "planned"
)

func (e *MaintenancesType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaintenancesType(s)
	case string:
		*e = MaintenancesType(s)
	default:
		return fmt.Errorf("unsupported scan type for MaintenancesType: %T", src)
	}
	return nil
}

type NullMaintenancesType struct {
	MaintenancesType MaintenancesType `json:"maintenances_type"`
	Valid            bool             `json:"valid"` // Valid is true if MaintenancesType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaintenancesType) Scan(value interface{}) error {
	if value == nil {
		ns.MaintenancesType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaintenancesType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaintenancesType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaintenancesType), nil
}

func (e MaintenancesType) Valid() bool {
	switch e {
	case MaintenancesTypeEmergency,
		MaintenancesTypePlanned:
		return true
	}
	return false
}

func AllMaintenancesTypeValues() []MaintenancesType {
	return []MaintenancesType{
		MaintenancesTypeEmergency,
		MaintenancesTypePlanned,
	}
}

type OauthService string

const (
	OauthServiceVk OauthService = "vk"
	OauthServiceTg OauthService = "tg"
)

func (e *OauthService) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthService(s)
	case string:
		*e = OauthService(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthService: %T", src)
	}
	return nil
}

type NullOauthService struct {
	OauthService OauthService `json:"oauth_service"`
	Valid        bool         `json:"valid"` // Valid is true if OauthService is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthService) Scan(value interface{}) error {
	if value == nil {
		ns.OauthService, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthService.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthService) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthService), nil
}

func (e OauthService) Valid() bool {
	switch e {
	case OauthServiceVk,
		OauthServiceTg:
		return true
	}
	return false
}

func AllOauthServiceValues() []OauthService {
	return []OauthService{
		OauthServiceVk,
		OauthServiceTg,
	}
}

type PreferencesLanguages string

const (
	PreferencesLanguagesRussian PreferencesLanguages = "russian"
	PreferencesLanguagesEnglish PreferencesLanguages = "english"
)

func (e *PreferencesLanguages) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PreferencesLanguages(s)
	case string:
		*e = PreferencesLanguages(s)
	default:
		return fmt.Errorf("unsupported scan type for PreferencesLanguages: %T", src)
	}
	return nil
}

type NullPreferencesLanguages struct {
	PreferencesLanguages PreferencesLanguages `json:"preferences_languages"`
	Valid                bool                 `json:"valid"` // Valid is true if PreferencesLanguages is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPreferencesLanguages) Scan(value interface{}) error {
	if value == nil {
		ns.PreferencesLanguages, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PreferencesLanguages.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPreferencesLanguages) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PreferencesLanguages), nil
}

func (e PreferencesLanguages) Valid() bool {
	switch e {
	case PreferencesLanguagesRussian,
		PreferencesLanguagesEnglish:
		return true
	}
	return false
}

func AllPreferencesLanguagesValues() []PreferencesLanguages {
	return []PreferencesLanguages{
		PreferencesLanguagesRussian,
		PreferencesLanguagesEnglish,
	}
}

type ProjectsStatus string

const (
	ProjectsStatusCancelled    ProjectsStatus = "cancelled"
	ProjectsStatusListing      ProjectsStatus = "listing"
	ProjectsStatusReviewing    ProjectsStatus = "reviewing"
	ProjectsStatusImplementing ProjectsStatus = "implementing"
	ProjectsStatusImplemented  ProjectsStatus = "implemented"
)

func (e *ProjectsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectsStatus(s)
	case string:
		*e = ProjectsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectsStatus: %T", src)
	}
	return nil
}

type NullProjectsStatus struct {
	ProjectsStatus ProjectsStatus `json:"projects_status"`
	Valid          bool           `json:"valid"` // Valid is true if ProjectsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectsStatus), nil
}

func (e ProjectsStatus) Valid() bool {
	switch e {
	case ProjectsStatusCancelled,
		ProjectsStatusListing,
		ProjectsStatusReviewing,
		ProjectsStatusImplementing,
		ProjectsStatusImplemented:
		return true
	}
	return false
}

func AllProjectsStatusValues() []ProjectsStatus {
	return []ProjectsStatus{
		ProjectsStatusCancelled,
		ProjectsStatusListing,
		ProjectsStatusReviewing,
		ProjectsStatusImplementing,
		ProjectsStatusImplemented,
	}
}

type TicketsCaller string

const (
	TicketsCallerUser   TicketsCaller = "user"
	TicketsCallerStaff  TicketsCaller = "staff"
	TicketsCallerSystem TicketsCaller = "system"
)

func (e *TicketsCaller) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketsCaller(s)
	case string:
		*e = TicketsCaller(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketsCaller: %T", src)
	}
	return nil
}

type NullTicketsCaller struct {
	TicketsCaller TicketsCaller `json:"tickets_caller"`
	Valid         bool          `json:"valid"` // Valid is true if TicketsCaller is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketsCaller) Scan(value interface{}) error {
	if value == nil {
		ns.TicketsCaller, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketsCaller.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketsCaller) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketsCaller), nil
}

func (e TicketsCaller) Valid() bool {
	switch e {
	case TicketsCallerUser,
		TicketsCallerStaff,
		TicketsCallerSystem:
		return true
	}
	return false
}

func AllTicketsCallerValues() []TicketsCaller {
	return []TicketsCaller{
		TicketsCallerUser,
		TicketsCallerStaff,
		TicketsCallerSystem,
	}
}

type TicketsStatus string

const (
	TicketsStatusClosed  TicketsStatus = "closed"
	TicketsStatusWaiting TicketsStatus = "waiting"
	TicketsStatusInwork  TicketsStatus = "in work"
)

func (e *TicketsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketsStatus(s)
	case string:
		*e = TicketsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketsStatus: %T", src)
	}
	return nil
}

type NullTicketsStatus struct {
	TicketsStatus TicketsStatus `json:"tickets_status"`
	Valid         bool          `json:"valid"` // Valid is true if TicketsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketsStatus), nil
}

func (e TicketsStatus) Valid() bool {
	switch e {
	case TicketsStatusClosed,
		TicketsStatusWaiting,
		TicketsStatusInwork:
		return true
	}
	return false
}

func AllTicketsStatusValues() []TicketsStatus {
	return []TicketsStatus{
		TicketsStatusClosed,
		TicketsStatusWaiting,
		TicketsStatusInwork,
	}
}

type BannedEmail struct {
	Address string             `json:"address"`
	Reason  string             `json:"reason"`
	At      pgtype.Timestamptz `json:"at"`
}

type Maintenance struct {
	ID           pgtype.UUID        `json:"id"`
	Description  string             `json:"description"`
	Status       MaintenancesStatus `json:"status"`
	Type         MaintenancesType   `json:"type"`
	PlannedStart pgtype.Timestamptz `json:"planned_start"`
	PlannedEnd   pgtype.Timestamptz `json:"planned_end"`
	ActualStart  pgtype.Timestamptz `json:"actual_start"`
	ActualEnd    pgtype.Timestamptz `json:"actual_end"`
	Caller       pgtype.UUID        `json:"caller"`
	Created      pgtype.Timestamptz `json:"created"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	Author      pgtype.UUID        `json:"author"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Category    string             `json:"category"`
	Status      ProjectsStatus     `json:"status"`
	ImplLink    pgtype.Text        `json:"impl_link"`
	At          pgtype.Timestamptz `json:"at"`
	Updated     pgtype.Timestamptz `json:"updated"`
	Deleted     pgtype.Timestamptz `json:"deleted"`
}

type ProjectLike struct {
	Project pgtype.UUID        `json:"project"`
	Author  pgtype.UUID        `json:"author"`
	At      pgtype.Timestamptz `json:"at"`
}

type ProjectLocation struct {
	ID   pgtype.UUID `json:"id"`
	City string      `json:"city"`
	Lat  float64     `json:"lat"`
	Lot  float64     `json:"lot"`
}

type ProjectMessage struct {
	ID      pgtype.UUID        `json:"id"`
	Linked  pgtype.UUID        `json:"linked"`
	Author  pgtype.UUID        `json:"author"`
	Parent  pgtype.UUID        `json:"parent"`
	Content string             `json:"content"`
	At      pgtype.Timestamptz `json:"at"`
	Deleted pgtype.Timestamptz `json:"deleted"`
}

type Rank struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Color       int64              `json:"color"`
	Weight      int32              `json:"weight"`
	Permissions []byte             `json:"permissions"`
	AddedAt     pgtype.Timestamptz `json:"added_at"`
}

type Session struct {
	ID      pgtype.UUID        `json:"id"`
	Owner   pgtype.UUID        `json:"owner"`
	At      pgtype.Timestamptz `json:"at"`
	SeenAt  pgtype.Timestamptz `json:"seen_at"`
	Expires pgtype.Timestamptz `json:"expires"`
	Mfa     bool               `json:"mfa"`
	Device  DeviceT            `json:"device"`
	Hash    string             `json:"hash"`
}

type Submission struct {
	ID       pgtype.UUID `json:"id"`
	Linked   pgtype.UUID `json:"linked"`
	Approved bool        `json:"approved"`
	Reason   pgtype.Text `json:"reason"`
}

type Ticket struct {
	ID       pgtype.UUID        `json:"id"`
	Author   pgtype.UUID        `json:"author"`
	Acceptor pgtype.UUID        `json:"acceptor"`
	Status   TicketsStatus      `json:"status"`
	Topic    string             `json:"topic"`
	Title    string             `json:"title"`
	Created  pgtype.Timestamptz `json:"created"`
	Accepted pgtype.Timestamptz `json:"accepted"`
	Closed   pgtype.Timestamptz `json:"closed"`
	Closer   pgtype.UUID        `json:"closer"`
	Caller   NullTicketsCaller  `json:"caller"`
	Reason   pgtype.Text        `json:"reason"`
}

type TicketsMessage struct {
	ID      pgtype.UUID        `json:"id"`
	Ticket  pgtype.UUID        `json:"ticket"`
	Author  pgtype.UUID        `json:"author"`
	Content string             `json:"content"`
	Created pgtype.Timestamptz `json:"created"`
}

type User struct {
	Uid      pgtype.UUID        `json:"uid"`
	Username string             `json:"username"`
	Email    string             `json:"email"`
	Joined   pgtype.Timestamptz `json:"joined"`
}

type UsersBan struct {
	ID       pgtype.UUID        `json:"id"`
	Executor pgtype.UUID        `json:"executor"`
	Target   pgtype.UUID        `json:"target"`
	Reason   string             `json:"reason"`
	At       pgtype.Timestamptz `json:"at"`
	Expires  pgtype.Timestamptz `json:"expires"`
}

type UsersOauth struct {
	Owner   pgtype.UUID        `json:"owner"`
	Service OauthService       `json:"service"`
	ID      string             `json:"id"`
	At      pgtype.Timestamptz `json:"at"`
}

type UsersPreference struct {
	Owner       pgtype.UUID          `json:"owner"`
	DisplayName string               `json:"display_name"`
	Description string               `json:"description"`
	AvatarHash  pgtype.Text          `json:"avatar_hash"`
	SessionLive int32                `json:"session_live"`
	Language    PreferencesLanguages `json:"language"`
}

type UsersRank struct {
	Owner   pgtype.UUID        `json:"owner"`
	Rank    pgtype.UUID        `json:"rank"`
	At      pgtype.Timestamptz `json:"at"`
	Expires pgtype.Timestamptz `json:"expires"`
}

type UsersSecurity struct {
	Owner              pgtype.UUID        `json:"owner"`
	Password           string             `json:"password"`
	EmailVerified      bool               `json:"email_verified"`
	TotpEnabled        bool               `json:"totp_enabled"`
	TotpSecret         pgtype.Text        `json:"totp_secret"`
	TotpConfirmed      pgtype.Timestamptz `json:"totp_confirmed"`
	TotpPending        pgtype.Text        `json:"totp_pending"`
	TotpPendingCreated pgtype.Timestamptz `json:"totp_pending_created"`
	TotpLastStep       pgtype.Int8        `json:"totp_last_step"`
}

type UsersSecurityCode struct {
	Owner    pgtype.UUID        `json:"owner"`
	Selector string             `json:"selector"`
	Hash     string             `json:"hash"`
	Used     pgtype.Timestamptz `json:"used"`
	Created  pgtype.Timestamptz `json:"created"`
}
