// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AcceptTicket = `-- name: AcceptTicket :exec
update tickets set acceptor = $1, accepted = now(), status = 'in work' where id = $2
`

type AcceptTicketParams struct {
	Acceptor pgtype.UUID `json:"acceptor"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) AcceptTicket(ctx context.Context, arg AcceptTicketParams) error {
	_, err := q.db.Exec(ctx, AcceptTicket, arg.Acceptor, arg.ID)
	return err
}

const CloseTicket = `-- name: CloseTicket :exec
update tickets set status = 'closed', closed = now(), closer = $1, reason = $2 where id = $1
`

type CloseTicketParams struct {
	Closer NullTicketsCaller `json:"closer"`
	Reason pgtype.Text       `json:"reason"`
}

func (q *Queries) CloseTicket(ctx context.Context, arg CloseTicketParams) error {
	_, err := q.db.Exec(ctx, CloseTicket, arg.Closer, arg.Reason)
	return err
}

const CreateMessage = `-- name: CreateMessage :one
insert into project_messages (linked, author, parent, content) values ($1, $2, $3, $4) returning id, linked, author, parent, content, at, deleted
`

type CreateMessageParams struct {
	Linked  pgtype.UUID `json:"linked"`
	Author  pgtype.UUID `json:"author"`
	Parent  pgtype.UUID `json:"parent"`
	Content string      `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ProjectMessage, error) {
	row := q.db.QueryRow(ctx, CreateMessage,
		arg.Linked,
		arg.Author,
		arg.Parent,
		arg.Content,
	)
	var i ProjectMessage
	err := row.Scan(
		&i.ID,
		&i.Linked,
		&i.Author,
		&i.Parent,
		&i.Content,
		&i.At,
		&i.Deleted,
	)
	return i, err
}

const CreateProject = `-- name: CreateProject :one
insert into projects (author, title, description) values ($1, $2, $3) returning  id, author, title, description, category, status, impl_link, likes, at, updated, deleted
`

type CreateProjectParams struct {
	Author      pgtype.UUID `json:"author"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, CreateProject, arg.Author, arg.Title, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.ImplLink,
		&i.Likes,
		&i.At,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}

const CreateSession = `-- name: CreateSession :one
insert into sessions (owner, expires, device, hash) VALUES ($1, $2, $3, $4) returning id, owner, at, seen_at, expires, mfa, device, hash
`

type CreateSessionParams struct {
	Owner   pgtype.UUID        `json:"owner"`
	Expires pgtype.Timestamptz `json:"expires"`
	Device  DeviceT            `json:"device"`
	Hash    string             `json:"hash"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, CreateSession,
		arg.Owner,
		arg.Expires,
		arg.Device,
		arg.Hash,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.At,
		&i.SeenAt,
		&i.Expires,
		&i.Mfa,
		&i.Device,
		&i.Hash,
	)
	return i, err
}

const CreateSubmission = `-- name: CreateSubmission :one
insert into submissions (linked) VALUES ($1) returning id, linked, reason, approved
`

type CreateSubmissionRow struct {
	ID       pgtype.UUID `json:"id"`
	Linked   pgtype.UUID `json:"linked"`
	Reason   pgtype.Text `json:"reason"`
	Approved bool        `json:"approved"`
}

func (q *Queries) CreateSubmission(ctx context.Context, linked pgtype.UUID) (CreateSubmissionRow, error) {
	row := q.db.QueryRow(ctx, CreateSubmission, linked)
	var i CreateSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.Linked,
		&i.Reason,
		&i.Approved,
	)
	return i, err
}

const CreateTicket = `-- name: CreateTicket :one
insert into tickets (author, title, topic) VALUES ($1, $2, $3) returning id, author, acceptor, status, topic, title, created, accepted, closed, closer, reason
`

type CreateTicketParams struct {
	Author pgtype.UUID `json:"author"`
	Title  string      `json:"title"`
	Topic  string      `json:"topic"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, CreateTicket, arg.Author, arg.Title, arg.Topic)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Acceptor,
		&i.Status,
		&i.Topic,
		&i.Title,
		&i.Created,
		&i.Accepted,
		&i.Closed,
		&i.Closer,
		&i.Reason,
	)
	return i, err
}

const CreateTicketMessage = `-- name: CreateTicketMessage :one
insert into tickets_messages (ticket, author, content) VALUES ($1, $2, $3) returning id, ticket, author, content, created
`

type CreateTicketMessageParams struct {
	Ticket  pgtype.UUID `json:"ticket"`
	Author  pgtype.UUID `json:"author"`
	Content string      `json:"content"`
}

func (q *Queries) CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) (TicketsMessage, error) {
	row := q.db.QueryRow(ctx, CreateTicketMessage, arg.Ticket, arg.Author, arg.Content)
	var i TicketsMessage
	err := row.Scan(
		&i.ID,
		&i.Ticket,
		&i.Author,
		&i.Content,
		&i.Created,
	)
	return i, err
}

const CreateUser = `-- name: CreateUser :one
insert into users (username, email) VALUES ($1, $2) returning uid, username, email, joined
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Email,
		&i.Joined,
	)
	return i, err
}

const CreateUserDefaultRank = `-- name: CreateUserDefaultRank :one
insert into users_ranks (owner, rank, expires) values ($1, (select id from ranks where name = 'user'), null) returning (select name from ranks where id = users_ranks.rank), (select color from ranks where id = users_ranks.rank), (select weight from ranks where id = users_ranks.rank), expires
`

type CreateUserDefaultRankRow struct {
	Name    string             `json:"name"`
	Color   int64              `json:"color"`
	Weight  int32              `json:"weight"`
	Expires pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) CreateUserDefaultRank(ctx context.Context, owner pgtype.UUID) (CreateUserDefaultRankRow, error) {
	row := q.db.QueryRow(ctx, CreateUserDefaultRank, owner)
	var i CreateUserDefaultRankRow
	err := row.Scan(
		&i.Name,
		&i.Color,
		&i.Weight,
		&i.Expires,
	)
	return i, err
}

const CreateUserPreferences = `-- name: CreateUserPreferences :one
insert into users_preferences (owner) VALUES ($1) returning owner, display_name, description, avatar_hash, session_live
`

func (q *Queries) CreateUserPreferences(ctx context.Context, owner pgtype.UUID) (UsersPreference, error) {
	row := q.db.QueryRow(ctx, CreateUserPreferences, owner)
	var i UsersPreference
	err := row.Scan(
		&i.Owner,
		&i.DisplayName,
		&i.Description,
		&i.AvatarHash,
		&i.SessionLive,
	)
	return i, err
}

const CreateUserSecurity = `-- name: CreateUserSecurity :one
insert into users_security (owner, password) VALUES ($1, $2) returning owner, password, email_verified, totp_enabled, totp_secret, totp_confirmed, totp_pending, totp_pending_created, totp_last_step
`

type CreateUserSecurityParams struct {
	Owner    pgtype.UUID `json:"owner"`
	Password string      `json:"password"`
}

func (q *Queries) CreateUserSecurity(ctx context.Context, arg CreateUserSecurityParams) (UsersSecurity, error) {
	row := q.db.QueryRow(ctx, CreateUserSecurity, arg.Owner, arg.Password)
	var i UsersSecurity
	err := row.Scan(
		&i.Owner,
		&i.Password,
		&i.EmailVerified,
		&i.TotpEnabled,
		&i.TotpSecret,
		&i.TotpConfirmed,
		&i.TotpPending,
		&i.TotpPendingCreated,
		&i.TotpLastStep,
	)
	return i, err
}

const DeleteMessage = `-- name: DeleteMessage :exec
update project_messages set deleted = now() where id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteMessage, id)
	return err
}

const EndUserSecurityTotp = `-- name: EndUserSecurityTotp :exec
update users_security set totp_enabled = true, totp_secret = totp_pending, totp_confirmed = now(), totp_pending = null, totp_pending_created = null where owner = $1
`

func (q *Queries) EndUserSecurityTotp(ctx context.Context, owner pgtype.UUID) error {
	_, err := q.db.Exec(ctx, EndUserSecurityTotp, owner)
	return err
}

const ExpiredTickets = `-- name: ExpiredTickets :many
select ticket from tickets_messages group by ticket having max(created) < now() - $1::interval
`

func (q *Queries) ExpiredTickets(ctx context.Context, dollar_1 pgtype.Interval) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, ExpiredTickets, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var ticket pgtype.UUID
		if err := rows.Scan(&ticket); err != nil {
			return nil, err
		}
		items = append(items, ticket)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ExtendSession = `-- name: ExtendSession :exec
update sessions set expires = expires + $1 where id = $2
`

type ExtendSessionParams struct {
	Expires pgtype.Timestamptz `json:"expires"`
	ID      pgtype.UUID        `json:"id"`
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.Exec(ctx, ExtendSession, arg.Expires, arg.ID)
	return err
}

const GetUser = `-- name: GetUser :one
select uid, username, email, joined from users where uid = $1 limit 1
`

func (q *Queries) GetUser(ctx context.Context, uid pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, GetUser, uid)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Email,
		&i.Joined,
	)
	return i, err
}

const GetUserByUserMail = `-- name: GetUserByUserMail :one
select uid, username, email, joined from users where username = $1 or email = $1 limit 1
`

func (q *Queries) GetUserByUserMail(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByUserMail, username)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Email,
		&i.Joined,
	)
	return i, err
}

const GetUserId = `-- name: GetUserId :one
select uid from users where email = $1 OR username = $1 limit 1
`

func (q *Queries) GetUserId(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, GetUserId, email)
	var uid pgtype.UUID
	err := row.Scan(&uid)
	return uid, err
}

const GetUserPassword = `-- name: GetUserPassword :one
select password from users_security where owner = $1 limit 1
`

func (q *Queries) GetUserPassword(ctx context.Context, owner pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, GetUserPassword, owner)
	var password string
	err := row.Scan(&password)
	return password, err
}

const GetUserPreferences = `-- name: GetUserPreferences :one
select owner, display_name, description, avatar_hash, session_live from users_preferences where owner = $1 limit 1
`

func (q *Queries) GetUserPreferences(ctx context.Context, owner pgtype.UUID) (UsersPreference, error) {
	row := q.db.QueryRow(ctx, GetUserPreferences, owner)
	var i UsersPreference
	err := row.Scan(
		&i.Owner,
		&i.DisplayName,
		&i.Description,
		&i.AvatarHash,
		&i.SessionLive,
	)
	return i, err
}

const GetUserRanks = `-- name: GetUserRanks :many
select ranks.name, ranks.color, ranks.weight, users_ranks.expires from users_ranks join ranks on ranks.id = users_ranks.rank where users_ranks.owner = $1
`

type GetUserRanksRow struct {
	Name    string             `json:"name"`
	Color   int64              `json:"color"`
	Weight  int32              `json:"weight"`
	Expires pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) GetUserRanks(ctx context.Context, owner pgtype.UUID) ([]GetUserRanksRow, error) {
	rows, err := q.db.Query(ctx, GetUserRanks, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRanksRow
	for rows.Next() {
		var i GetUserRanksRow
		if err := rows.Scan(
			&i.Name,
			&i.Color,
			&i.Weight,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserRecoveryCodes = `-- name: GetUserRecoveryCodes :many
select owner, hash, used, created from users_security_codes where owner = $1
`

func (q *Queries) GetUserRecoveryCodes(ctx context.Context, owner pgtype.UUID) ([]UsersSecurityCode, error) {
	rows, err := q.db.Query(ctx, GetUserRecoveryCodes, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersSecurityCode
	for rows.Next() {
		var i UsersSecurityCode
		if err := rows.Scan(
			&i.Owner,
			&i.Hash,
			&i.Used,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserSecurity = `-- name: GetUserSecurity :one
select owner, password, email_verified, totp_enabled, totp_secret, totp_confirmed, totp_pending, totp_pending_created, totp_last_step from users_security where owner = $1 limit 1
`

func (q *Queries) GetUserSecurity(ctx context.Context, owner pgtype.UUID) (UsersSecurity, error) {
	row := q.db.QueryRow(ctx, GetUserSecurity, owner)
	var i UsersSecurity
	err := row.Scan(
		&i.Owner,
		&i.Password,
		&i.EmailVerified,
		&i.TotpEnabled,
		&i.TotpSecret,
		&i.TotpConfirmed,
		&i.TotpPending,
		&i.TotpPendingCreated,
		&i.TotpLastStep,
	)
	return i, err
}

const GetUsers = `-- name: GetUsers :many
select uid, username, email, joined from users limit $1 offset $2
`

type GetUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, GetUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uid,
			&i.Username,
			&i.Email,
			&i.Joined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertRecoveryCodesParams struct {
	Owner pgtype.UUID `json:"owner"`
	Hash  string      `json:"hash"`
}

const IsSessionValid = `-- name: IsSessionValid :one
select expires > now() and device = $1 and hash = $2 from sessions where id = $3
`

type IsSessionValidParams struct {
	Device DeviceT     `json:"device"`
	Hash   string      `json:"hash"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) IsSessionValid(ctx context.Context, arg IsSessionValidParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, IsSessionValid, arg.Device, arg.Hash, arg.ID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const IsTicketAccepted = `-- name: IsTicketAccepted :one
select (acceptor is not null)::boolean as is_accepted from tickets where id = $1
`

func (q *Queries) IsTicketAccepted(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, IsTicketAccepted, id)
	var is_accepted bool
	err := row.Scan(&is_accepted)
	return is_accepted, err
}

const IsTicketClosed = `-- name: IsTicketClosed :one
select (closed is not null)::boolean as is_closed from tickets where id = $1
`

func (q *Queries) IsTicketClosed(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, IsTicketClosed, id)
	var is_closed bool
	err := row.Scan(&is_closed)
	return is_closed, err
}

const IsUserBanned = `-- name: IsUserBanned :one
select exists (select 1 from users_bans where target = $1 and (expires is null or expires > now()))
`

func (q *Queries) IsUserBanned(ctx context.Context, target pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, IsUserBanned, target)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const IsUserExists = `-- name: IsUserExists :one
select exists (select 1 from users where username = $1 or email = $1)
`

func (q *Queries) IsUserExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, IsUserExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const MessageInfo = `-- name: MessageInfo :one
select id, linked, author, parent, content, at, deleted from project_messages where id = $1 limit 1
`

func (q *Queries) MessageInfo(ctx context.Context, id pgtype.UUID) (ProjectMessage, error) {
	row := q.db.QueryRow(ctx, MessageInfo, id)
	var i ProjectMessage
	err := row.Scan(
		&i.ID,
		&i.Linked,
		&i.Author,
		&i.Parent,
		&i.Content,
		&i.At,
		&i.Deleted,
	)
	return i, err
}

const MessagesList = `-- name: MessagesList :many
select id, linked, author, parent, content, at, deleted from project_messages where linked = $1 and deleted is null limit $2 offset $3
`

type MessagesListParams struct {
	Linked pgtype.UUID `json:"linked"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) MessagesList(ctx context.Context, arg MessagesListParams) ([]ProjectMessage, error) {
	rows, err := q.db.Query(ctx, MessagesList, arg.Linked, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMessage
	for rows.Next() {
		var i ProjectMessage
		if err := rows.Scan(
			&i.ID,
			&i.Linked,
			&i.Author,
			&i.Parent,
			&i.Content,
			&i.At,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OpenedTickets = `-- name: OpenedTickets :many
select id, author, acceptor, status, topic, title, created, accepted, closed, closer, reason from tickets where closed is not null and acceptor is null limit $1 offset $2
`

type OpenedTicketsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) OpenedTickets(ctx context.Context, arg OpenedTicketsParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, OpenedTickets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Acceptor,
			&i.Status,
			&i.Topic,
			&i.Title,
			&i.Created,
			&i.Accepted,
			&i.Closed,
			&i.Closer,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ProjectInfo = `-- name: ProjectInfo :one
select id, author, title, description, category, status, impl_link, likes, at, updated, deleted from projects where id = $1 limit 1
`

func (q *Queries) ProjectInfo(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, ProjectInfo, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.ImplLink,
		&i.Likes,
		&i.At,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}

const ProjectsList = `-- name: ProjectsList :many
select id, author, title, description, category, status, impl_link, likes, at, updated, deleted from projects limit $1 offset $2
`

type ProjectsListParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ProjectsList(ctx context.Context, arg ProjectsListParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, ProjectsList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Status,
			&i.ImplLink,
			&i.Likes,
			&i.At,
			&i.Updated,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RevokeSession = `-- name: RevokeSession :exec
update sessions set expires = now() where id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, RevokeSession, id)
	return err
}

const SessionInfo = `-- name: SessionInfo :one
select id, owner, at, seen_at, expires, mfa, device, hash from sessions where id = $1
`

func (q *Queries) SessionInfo(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, SessionInfo, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.At,
		&i.SeenAt,
		&i.Expires,
		&i.Mfa,
		&i.Device,
		&i.Hash,
	)
	return i, err
}

const SessionsByOwner = `-- name: SessionsByOwner :many
select id, owner, at, seen_at, expires, mfa, device, hash from sessions where owner = $1 limit $2 offset $3
`

type SessionsByOwnerParams struct {
	Owner  pgtype.UUID `json:"owner"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) SessionsByOwner(ctx context.Context, arg SessionsByOwnerParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, SessionsByOwner, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.At,
			&i.SeenAt,
			&i.Expires,
			&i.Mfa,
			&i.Device,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetProjectStatus = `-- name: SetProjectStatus :exec
update projects set status = $1, impl_link = $2 where id = $3
`

type SetProjectStatusParams struct {
	Status   ProjectsStatus `json:"status"`
	ImplLink pgtype.Text    `json:"impl_link"`
	ID       pgtype.UUID    `json:"id"`
}

func (q *Queries) SetProjectStatus(ctx context.Context, arg SetProjectStatusParams) error {
	_, err := q.db.Exec(ctx, SetProjectStatus, arg.Status, arg.ImplLink, arg.ID)
	return err
}

const SetSessionLastSeen = `-- name: SetSessionLastSeen :exec
update sessions set seen_at = now() where id = $1
`

func (q *Queries) SetSessionLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, SetSessionLastSeen, id)
	return err
}

const SetUserSecurityEmailVerified = `-- name: SetUserSecurityEmailVerified :exec
update users_security set email_verified = true where owner = $1
`

func (q *Queries) SetUserSecurityEmailVerified(ctx context.Context, owner pgtype.UUID) error {
	_, err := q.db.Exec(ctx, SetUserSecurityEmailVerified, owner)
	return err
}

const StartUserSecurityTotp = `-- name: StartUserSecurityTotp :exec
update users_security set owner = $1, totp_pending = $2, totp_pending_created = now() where owner = $1
`

type StartUserSecurityTotpParams struct {
	Owner       pgtype.UUID `json:"owner"`
	TotpPending pgtype.Text `json:"totp_pending"`
}

func (q *Queries) StartUserSecurityTotp(ctx context.Context, arg StartUserSecurityTotpParams) error {
	_, err := q.db.Exec(ctx, StartUserSecurityTotp, arg.Owner, arg.TotpPending)
	return err
}

const SubmissionInfo = `-- name: SubmissionInfo :one
select id, linked, approved, reason from submissions where id = $1 limit 1
`

func (q *Queries) SubmissionInfo(ctx context.Context, id pgtype.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, SubmissionInfo, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Linked,
		&i.Approved,
		&i.Reason,
	)
	return i, err
}

const SubmissionsList = `-- name: SubmissionsList :many
select id, linked, approved, reason from submissions limit $1 offset $2
`

type SubmissionsListParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) SubmissionsList(ctx context.Context, arg SubmissionsListParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, SubmissionsList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.Linked,
			&i.Approved,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TicketInfo = `-- name: TicketInfo :one
select id, author, acceptor, status, topic, title, created, accepted, closed, closer, reason from tickets where id = $1 limit 1
`

func (q *Queries) TicketInfo(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, TicketInfo, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Acceptor,
		&i.Status,
		&i.Topic,
		&i.Title,
		&i.Created,
		&i.Accepted,
		&i.Closed,
		&i.Closer,
		&i.Reason,
	)
	return i, err
}

const TicketMessages = `-- name: TicketMessages :many
select id, ticket, author, content, created from tickets_messages where ticket = $1 limit $2 offset $3
`

type TicketMessagesParams struct {
	Ticket pgtype.UUID `json:"ticket"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) TicketMessages(ctx context.Context, arg TicketMessagesParams) ([]TicketsMessage, error) {
	rows, err := q.db.Query(ctx, TicketMessages, arg.Ticket, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketsMessage
	for rows.Next() {
		var i TicketsMessage
		if err := rows.Scan(
			&i.ID,
			&i.Ticket,
			&i.Author,
			&i.Content,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TicketsByAuthor = `-- name: TicketsByAuthor :many
select id, author, acceptor, status, topic, title, created, accepted, closed, closer, reason from tickets where author = $1 limit $2 offset $3
`

type TicketsByAuthorParams struct {
	Author pgtype.UUID `json:"author"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) TicketsByAuthor(ctx context.Context, arg TicketsByAuthorParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, TicketsByAuthor, arg.Author, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Acceptor,
			&i.Status,
			&i.Topic,
			&i.Title,
			&i.Created,
			&i.Accepted,
			&i.Closed,
			&i.Closer,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateProjectDescription = `-- name: UpdateProjectDescription :exec
update projects set description = $1, updated = now() where id = $2
`

type UpdateProjectDescriptionParams struct {
	Description string      `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProjectDescription(ctx context.Context, arg UpdateProjectDescriptionParams) error {
	_, err := q.db.Exec(ctx, UpdateProjectDescription, arg.Description, arg.ID)
	return err
}

const UpdateUserAvatar = `-- name: UpdateUserAvatar :exec
update users_preferences set avatar_hash = $1 where owner = $2
`

type UpdateUserAvatarParams struct {
	AvatarHash pgtype.Text `json:"avatar_hash"`
	Owner      pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, UpdateUserAvatar, arg.AvatarHash, arg.Owner)
	return err
}

const UpdateUserDescription = `-- name: UpdateUserDescription :exec
update users_preferences set description = $1 where owner = $2
`

type UpdateUserDescriptionParams struct {
	Description string      `json:"description"`
	Owner       pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdateUserDescription(ctx context.Context, arg UpdateUserDescriptionParams) error {
	_, err := q.db.Exec(ctx, UpdateUserDescription, arg.Description, arg.Owner)
	return err
}

const UpdateUserDisplayName = `-- name: UpdateUserDisplayName :exec
update users_preferences set display_name = $1 where owner = $2
`

type UpdateUserDisplayNameParams struct {
	DisplayName string      `json:"display_name"`
	Owner       pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.Exec(ctx, UpdateUserDisplayName, arg.DisplayName, arg.Owner)
	return err
}

const UpdateUserPassword = `-- name: UpdateUserPassword :exec
update users_security set password = $1 where owner = $2
`

type UpdateUserPasswordParams struct {
	Password string      `json:"password"`
	Owner    pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, UpdateUserPassword, arg.Password, arg.Owner)
	return err
}

const UpdateUserSessionLive = `-- name: UpdateUserSessionLive :exec
update users_preferences set session_live = $1 where owner = $2
`

type UpdateUserSessionLiveParams struct {
	SessionLive int32       `json:"session_live"`
	Owner       pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdateUserSessionLive(ctx context.Context, arg UpdateUserSessionLiveParams) error {
	_, err := q.db.Exec(ctx, UpdateUserSessionLive, arg.SessionLive, arg.Owner)
	return err
}

const UseRecoveryCode = `-- name: UseRecoveryCode :exec
update users_security_codes set used = now() where hash = $1
`

func (q *Queries) UseRecoveryCode(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, UseRecoveryCode, hash)
	return err
}
