// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AcceptSubmission = `-- name: AcceptSubmission :exec
update submissions
set approved = true
where linked = $1
`

func (q *Queries) AcceptSubmission(ctx context.Context, linked pgtype.UUID) error {
	_, err := q.db.Exec(ctx, AcceptSubmission, linked)
	return err
}

const AcceptTicket = `-- name: AcceptTicket :exec
update tickets set acceptor = $1, accepted = now(), status = 'in work' where id = $2
`

type AcceptTicketParams struct {
	Acceptor pgtype.UUID `json:"acceptor"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) AcceptTicket(ctx context.Context, arg AcceptTicketParams) error {
	_, err := q.db.Exec(ctx, AcceptTicket, arg.Acceptor, arg.ID)
	return err
}

const ActionsByOwner = `-- name: ActionsByOwner :many
select id, owner, purpose, hash, at, expires, used from users_actions where owner = $1
`

func (q *Queries) ActionsByOwner(ctx context.Context, owner pgtype.UUID) ([]UsersAction, error) {
	rows, err := q.db.Query(ctx, ActionsByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersAction
	for rows.Next() {
		var i UsersAction
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Purpose,
			&i.Hash,
			&i.At,
			&i.Expires,
			&i.Used,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ActiveMaintenance = `-- name: ActiveMaintenance :one
select id, description, status, type, planned_start, planned_end, actual_start, actual_end, caller, created from maintenances where status = 'running' or (planned_start < now() and actual_end is not null) limit 1
`

func (q *Queries) ActiveMaintenance(ctx context.Context) (Maintenance, error) {
	row := q.db.QueryRow(ctx, ActiveMaintenance)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Status,
		&i.Type,
		&i.PlannedStart,
		&i.PlannedEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.Caller,
		&i.Created,
	)
	return i, err
}

const BanUser = `-- name: BanUser :exec
insert into users_bans (executor, target, reason, expires) values ($1, $2, $3, $4)
`

type BanUserParams struct {
	Executor pgtype.UUID        `json:"executor"`
	Target   pgtype.UUID        `json:"target"`
	Reason   string             `json:"reason"`
	Expires  pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.Exec(ctx, BanUser,
		arg.Executor,
		arg.Target,
		arg.Reason,
		arg.Expires,
	)
	return err
}

const CloseTicket = `-- name: CloseTicket :exec
update tickets
set status = 'closed',
    closed = now(),
    closer = $1,
    caller = $2,
    reason = $3
where id = $4
`

type CloseTicketParams struct {
	Closer pgtype.UUID       `json:"closer"`
	Caller NullTicketsCaller `json:"caller"`
	Reason pgtype.Text       `json:"reason"`
	ID     pgtype.UUID       `json:"id"`
}

func (q *Queries) CloseTicket(ctx context.Context, arg CloseTicketParams) error {
	_, err := q.db.Exec(ctx, CloseTicket,
		arg.Closer,
		arg.Caller,
		arg.Reason,
		arg.ID,
	)
	return err
}

const CreateAction = `-- name: CreateAction :one
insert into users_actions (owner, purpose, hash, expires) values ($1, $2, $3, $4) returning id, owner, purpose, hash, at, expires, used
`

type CreateActionParams struct {
	Owner   pgtype.UUID        `json:"owner"`
	Purpose string             `json:"purpose"`
	Hash    string             `json:"hash"`
	Expires pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) (UsersAction, error) {
	row := q.db.QueryRow(ctx, CreateAction,
		arg.Owner,
		arg.Purpose,
		arg.Hash,
		arg.Expires,
	)
	var i UsersAction
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Purpose,
		&i.Hash,
		&i.At,
		&i.Expires,
		&i.Used,
	)
	return i, err
}

const CreateFile = `-- name: CreateFile :one
insert into files (owner, purpose, mime_type, size, key, bucket)
values ($1, $2, $3, $4, $5, $6)
returning id, owner, purpose, mime_type, size, key, bucket, created_at
`

type CreateFileParams struct {
	Owner    pgtype.UUID `json:"owner"`
	Purpose  string      `json:"purpose"`
	MimeType string      `json:"mime_type"`
	Size     int64       `json:"size"`
	Key      string      `json:"key"`
	Bucket   string      `json:"bucket"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, CreateFile,
		arg.Owner,
		arg.Purpose,
		arg.MimeType,
		arg.Size,
		arg.Key,
		arg.Bucket,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Purpose,
		&i.MimeType,
		&i.Size,
		&i.Key,
		&i.Bucket,
		&i.CreatedAt,
	)
	return i, err
}

const CreateMaintenance = `-- name: CreateMaintenance :one
insert into maintenances (description, planned_start, planned_end, caller) values ($1, $2, $3, $4) returning id, description, status, type, planned_start, planned_end, actual_start, actual_end, caller, created
`

type CreateMaintenanceParams struct {
	Description  string             `json:"description"`
	PlannedStart pgtype.Timestamptz `json:"planned_start"`
	PlannedEnd   pgtype.Timestamptz `json:"planned_end"`
	Caller       pgtype.UUID        `json:"caller"`
}

func (q *Queries) CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) (Maintenance, error) {
	row := q.db.QueryRow(ctx, CreateMaintenance,
		arg.Description,
		arg.PlannedStart,
		arg.PlannedEnd,
		arg.Caller,
	)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Status,
		&i.Type,
		&i.PlannedStart,
		&i.PlannedEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.Caller,
		&i.Created,
	)
	return i, err
}

const CreateMessage = `-- name: CreateMessage :one
insert into project_messages (linked, author, parent, content) values ($1, $2, $3, $4) returning id, linked, author, parent, content, at, deleted
`

type CreateMessageParams struct {
	Linked  pgtype.UUID `json:"linked"`
	Author  pgtype.UUID `json:"author"`
	Parent  pgtype.UUID `json:"parent"`
	Content string      `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ProjectMessage, error) {
	row := q.db.QueryRow(ctx, CreateMessage,
		arg.Linked,
		arg.Author,
		arg.Parent,
		arg.Content,
	)
	var i ProjectMessage
	err := row.Scan(
		&i.ID,
		&i.Linked,
		&i.Author,
		&i.Parent,
		&i.Content,
		&i.At,
		&i.Deleted,
	)
	return i, err
}

const CreateProject = `-- name: CreateProject :one
insert into projects (author, title, description, category)
values ($1, $2, $3, $4)
returning id, author, title, description, category, status, impl_link, at, updated, deleted
`

type CreateProjectParams struct {
	Author      pgtype.UUID `json:"author"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, CreateProject,
		arg.Author,
		arg.Title,
		arg.Description,
		arg.Category,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.ImplLink,
		&i.At,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}

const CreateProjectLike = `-- name: CreateProjectLike :exec
insert into project_likes (project, author) values ($1, $2)
`

type CreateProjectLikeParams struct {
	Project pgtype.UUID `json:"project"`
	Author  pgtype.UUID `json:"author"`
}

func (q *Queries) CreateProjectLike(ctx context.Context, arg CreateProjectLikeParams) error {
	_, err := q.db.Exec(ctx, CreateProjectLike, arg.Project, arg.Author)
	return err
}

const CreateProjectLocation = `-- name: CreateProjectLocation :one
insert into project_location (id, city, lat, lot)
values ($1, $2, $3, $4)
returning id, city, lat, lot
`

type CreateProjectLocationParams struct {
	ID   pgtype.UUID `json:"id"`
	City string      `json:"city"`
	Lat  float64     `json:"lat"`
	Lot  float64     `json:"lot"`
}

func (q *Queries) CreateProjectLocation(ctx context.Context, arg CreateProjectLocationParams) (ProjectLocation, error) {
	row := q.db.QueryRow(ctx, CreateProjectLocation,
		arg.ID,
		arg.City,
		arg.Lat,
		arg.Lot,
	)
	var i ProjectLocation
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.Lat,
		&i.Lot,
	)
	return i, err
}

const CreateRank = `-- name: CreateRank :one
insert into ranks (name, description, color, weight, permissions) values ($1, $2, $3, $4, $5) returning id, name, description, color, weight, permissions, added_at
`

type CreateRankParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Color       int64  `json:"color"`
	Weight      int32  `json:"weight"`
	Permissions []byte `json:"permissions"`
}

func (q *Queries) CreateRank(ctx context.Context, arg CreateRankParams) (Rank, error) {
	row := q.db.QueryRow(ctx, CreateRank,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Weight,
		arg.Permissions,
	)
	var i Rank
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Weight,
		&i.Permissions,
		&i.AddedAt,
	)
	return i, err
}

const CreateSession = `-- name: CreateSession :one
insert into sessions (owner, expires, device, hash) VALUES ($1, $2, $3, $4) returning id, owner, at, seen_at, expires, mfa, device, hash
`

type CreateSessionParams struct {
	Owner   pgtype.UUID        `json:"owner"`
	Expires pgtype.Timestamptz `json:"expires"`
	Device  DeviceT            `json:"device"`
	Hash    string             `json:"hash"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, CreateSession,
		arg.Owner,
		arg.Expires,
		arg.Device,
		arg.Hash,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.At,
		&i.SeenAt,
		&i.Expires,
		&i.Mfa,
		&i.Device,
		&i.Hash,
	)
	return i, err
}

const CreateSubmission = `-- name: CreateSubmission :one
insert into submissions (linked) VALUES ($1) returning id, linked, reason, approved
`

type CreateSubmissionRow struct {
	ID       pgtype.UUID `json:"id"`
	Linked   pgtype.UUID `json:"linked"`
	Reason   pgtype.Text `json:"reason"`
	Approved bool        `json:"approved"`
}

func (q *Queries) CreateSubmission(ctx context.Context, linked pgtype.UUID) (CreateSubmissionRow, error) {
	row := q.db.QueryRow(ctx, CreateSubmission, linked)
	var i CreateSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.Linked,
		&i.Reason,
		&i.Approved,
	)
	return i, err
}

const CreateTicket = `-- name: CreateTicket :one
insert into tickets (author, title, topic)
VALUES ($1, $2, $3)
returning id, author, acceptor, status, topic, title, created, accepted, closed, closer, caller, reason
`

type CreateTicketParams struct {
	Author pgtype.UUID `json:"author"`
	Title  string      `json:"title"`
	Topic  string      `json:"topic"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, CreateTicket, arg.Author, arg.Title, arg.Topic)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Acceptor,
		&i.Status,
		&i.Topic,
		&i.Title,
		&i.Created,
		&i.Accepted,
		&i.Closed,
		&i.Closer,
		&i.Caller,
		&i.Reason,
	)
	return i, err
}

const CreateTicketMessage = `-- name: CreateTicketMessage :one
insert into tickets_messages (ticket, author, content) VALUES ($1, $2, $3) returning id, ticket, author, content, created
`

type CreateTicketMessageParams struct {
	Ticket  pgtype.UUID `json:"ticket"`
	Author  pgtype.UUID `json:"author"`
	Content string      `json:"content"`
}

func (q *Queries) CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) (TicketsMessage, error) {
	row := q.db.QueryRow(ctx, CreateTicketMessage, arg.Ticket, arg.Author, arg.Content)
	var i TicketsMessage
	err := row.Scan(
		&i.ID,
		&i.Ticket,
		&i.Author,
		&i.Content,
		&i.Created,
	)
	return i, err
}

const CreateUser = `-- name: CreateUser :one
insert into users (username, email) VALUES ($1, $2) returning uid, username, email, joined
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Email,
		&i.Joined,
	)
	return i, err
}

const CreateUserDefaultRank = `-- name: CreateUserDefaultRank :one
insert into users_ranks (owner, rank, expires) values ($1, (select id from ranks where name = 'user'), null) returning (select name from ranks where id = users_ranks.rank), (select color from ranks where id = users_ranks.rank), (select weight from ranks where id = users_ranks.rank), expires
`

type CreateUserDefaultRankRow struct {
	Name    string             `json:"name"`
	Color   int64              `json:"color"`
	Weight  int32              `json:"weight"`
	Expires pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) CreateUserDefaultRank(ctx context.Context, owner pgtype.UUID) (CreateUserDefaultRankRow, error) {
	row := q.db.QueryRow(ctx, CreateUserDefaultRank, owner)
	var i CreateUserDefaultRankRow
	err := row.Scan(
		&i.Name,
		&i.Color,
		&i.Weight,
		&i.Expires,
	)
	return i, err
}

const CreateUserPreferences = `-- name: CreateUserPreferences :one
insert into users_preferences (owner)
VALUES ($1)
returning owner, display_name, description, avatar_hash, session_live, language
`

func (q *Queries) CreateUserPreferences(ctx context.Context, owner pgtype.UUID) (UsersPreference, error) {
	row := q.db.QueryRow(ctx, CreateUserPreferences, owner)
	var i UsersPreference
	err := row.Scan(
		&i.Owner,
		&i.DisplayName,
		&i.Description,
		&i.AvatarHash,
		&i.SessionLive,
		&i.Language,
	)
	return i, err
}

const CreateUserSecurity = `-- name: CreateUserSecurity :one
insert into users_security (owner, password) VALUES ($1, $2) returning owner, password, email_verified, totp_enabled, totp_secret, totp_confirmed, totp_pending, totp_pending_created, totp_last_step
`

type CreateUserSecurityParams struct {
	Owner    pgtype.UUID `json:"owner"`
	Password string      `json:"password"`
}

func (q *Queries) CreateUserSecurity(ctx context.Context, arg CreateUserSecurityParams) (UsersSecurity, error) {
	row := q.db.QueryRow(ctx, CreateUserSecurity, arg.Owner, arg.Password)
	var i UsersSecurity
	err := row.Scan(
		&i.Owner,
		&i.Password,
		&i.EmailVerified,
		&i.TotpEnabled,
		&i.TotpSecret,
		&i.TotpConfirmed,
		&i.TotpPending,
		&i.TotpPendingCreated,
		&i.TotpLastStep,
	)
	return i, err
}

const DeleteMessage = `-- name: DeleteMessage :exec
update project_messages set deleted = now() where id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteMessage, id)
	return err
}

const DeleteProject = `-- name: DeleteProject :exec
update projects set deleted = now(), status = 'cancelled' where id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteProject, id)
	return err
}

const DeleteRank = `-- name: DeleteRank :exec
delete
from ranks
where id = $1
`

func (q *Queries) DeleteRank(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteRank, id)
	return err
}

const DenySubmission = `-- name: DenySubmission :exec
update submissions
set approved = false,
    reason   = $1
where linked = $2
`

type DenySubmissionParams struct {
	Reason pgtype.Text `json:"reason"`
	Linked pgtype.UUID `json:"linked"`
}

func (q *Queries) DenySubmission(ctx context.Context, arg DenySubmissionParams) error {
	_, err := q.db.Exec(ctx, DenySubmission, arg.Reason, arg.Linked)
	return err
}

const EndMaintenance = `-- name: EndMaintenance :exec
update maintenances set status = 'completed', actual_end = now() where id = $1
`

func (q *Queries) EndMaintenance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, EndMaintenance, id)
	return err
}

const EndUserSecurityTotp = `-- name: EndUserSecurityTotp :exec
update users_security set totp_enabled = true, totp_secret = totp_pending, totp_confirmed = now(), totp_pending = null, totp_pending_created = null where owner = $1
`

func (q *Queries) EndUserSecurityTotp(ctx context.Context, owner pgtype.UUID) error {
	_, err := q.db.Exec(ctx, EndUserSecurityTotp, owner)
	return err
}

const ExpiredTickets = `-- name: ExpiredTickets :many
select ticket from tickets_messages group by ticket having max(created) < now() - $1::interval
`

func (q *Queries) ExpiredTickets(ctx context.Context, dollar_1 pgtype.Interval) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, ExpiredTickets, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var ticket pgtype.UUID
		if err := rows.Scan(&ticket); err != nil {
			return nil, err
		}
		items = append(items, ticket)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ExtendSession = `-- name: ExtendSession :exec
update sessions set expires = expires + $1 where id = $2
`

type ExtendSessionParams struct {
	Expires pgtype.Timestamptz `json:"expires"`
	ID      pgtype.UUID        `json:"id"`
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.Exec(ctx, ExtendSession, arg.Expires, arg.ID)
	return err
}

const FindAction = `-- name: FindAction :one
select id, owner, purpose, hash, at, expires, used from users_actions where hash = $1 and purpose = $2 limit 1
`

type FindActionParams struct {
	Hash    string `json:"hash"`
	Purpose string `json:"purpose"`
}

func (q *Queries) FindAction(ctx context.Context, arg FindActionParams) (UsersAction, error) {
	row := q.db.QueryRow(ctx, FindAction, arg.Hash, arg.Purpose)
	var i UsersAction
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Purpose,
		&i.Hash,
		&i.At,
		&i.Expires,
		&i.Used,
	)
	return i, err
}

const GetFile = `-- name: GetFile :one
select id, owner, purpose, mime_type, size, key, bucket, created_at
from files
where id = $1
limit 1
`

func (q *Queries) GetFile(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, GetFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Purpose,
		&i.MimeType,
		&i.Size,
		&i.Key,
		&i.Bucket,
		&i.CreatedAt,
	)
	return i, err
}

const GetFilesByOwner = `-- name: GetFilesByOwner :many
select id, owner, purpose, mime_type, size, key, bucket, created_at
from files
where owner = $1
`

func (q *Queries) GetFilesByOwner(ctx context.Context, owner pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, GetFilesByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Purpose,
			&i.MimeType,
			&i.Size,
			&i.Key,
			&i.Bucket,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUser = `-- name: GetUser :one
select uid, username, email, joined from users where uid = $1 limit 1
`

func (q *Queries) GetUser(ctx context.Context, uid pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, GetUser, uid)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Email,
		&i.Joined,
	)
	return i, err
}

const GetUserByUserMail = `-- name: GetUserByUserMail :one
select uid, username, email, joined from users where username = $1 or email = $1 limit 1
`

func (q *Queries) GetUserByUserMail(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByUserMail, username)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Email,
		&i.Joined,
	)
	return i, err
}

const GetUserId = `-- name: GetUserId :one
select uid from users where email = $1 OR username = $1 limit 1
`

func (q *Queries) GetUserId(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, GetUserId, email)
	var uid pgtype.UUID
	err := row.Scan(&uid)
	return uid, err
}

const GetUserPassword = `-- name: GetUserPassword :one
select password from users_security where owner = $1 limit 1
`

func (q *Queries) GetUserPassword(ctx context.Context, owner pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, GetUserPassword, owner)
	var password string
	err := row.Scan(&password)
	return password, err
}

const GetUserPreferences = `-- name: GetUserPreferences :one
select owner, display_name, description, avatar_hash, session_live, language
from users_preferences
where owner = $1
limit 1
`

func (q *Queries) GetUserPreferences(ctx context.Context, owner pgtype.UUID) (UsersPreference, error) {
	row := q.db.QueryRow(ctx, GetUserPreferences, owner)
	var i UsersPreference
	err := row.Scan(
		&i.Owner,
		&i.DisplayName,
		&i.Description,
		&i.AvatarHash,
		&i.SessionLive,
		&i.Language,
	)
	return i, err
}

const GetUserRanks = `-- name: GetUserRanks :many
select ranks.id, ranks.name, ranks.color, ranks.weight, ranks.permissions, users_ranks.expires
from users_ranks
         join ranks on ranks.id = users_ranks.rank
where users_ranks.owner = $1
`

type GetUserRanksRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Color       int64              `json:"color"`
	Weight      int32              `json:"weight"`
	Permissions []byte             `json:"permissions"`
	Expires     pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) GetUserRanks(ctx context.Context, owner pgtype.UUID) ([]GetUserRanksRow, error) {
	rows, err := q.db.Query(ctx, GetUserRanks, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRanksRow
	for rows.Next() {
		var i GetUserRanksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Weight,
			&i.Permissions,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserRecoveryCodes = `-- name: GetUserRecoveryCodes :many
select owner, selector, hash, used, created
from users_security_codes
where owner = $1
`

func (q *Queries) GetUserRecoveryCodes(ctx context.Context, owner pgtype.UUID) ([]UsersSecurityCode, error) {
	rows, err := q.db.Query(ctx, GetUserRecoveryCodes, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersSecurityCode
	for rows.Next() {
		var i UsersSecurityCode
		if err := rows.Scan(
			&i.Owner,
			&i.Selector,
			&i.Hash,
			&i.Used,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserRecoveryCodesWithSelector = `-- name: GetUserRecoveryCodesWithSelector :one
select owner, selector, hash, used, created
from users_security_codes
where owner = $1
  and selector = $2
limit 1
`

type GetUserRecoveryCodesWithSelectorParams struct {
	Owner    pgtype.UUID `json:"owner"`
	Selector string      `json:"selector"`
}

func (q *Queries) GetUserRecoveryCodesWithSelector(ctx context.Context, arg GetUserRecoveryCodesWithSelectorParams) (UsersSecurityCode, error) {
	row := q.db.QueryRow(ctx, GetUserRecoveryCodesWithSelector, arg.Owner, arg.Selector)
	var i UsersSecurityCode
	err := row.Scan(
		&i.Owner,
		&i.Selector,
		&i.Hash,
		&i.Used,
		&i.Created,
	)
	return i, err
}

const GetUserSecurity = `-- name: GetUserSecurity :one
select owner, password, email_verified, totp_enabled, totp_secret, totp_confirmed, totp_pending, totp_pending_created, totp_last_step from users_security where owner = $1 limit 1
`

func (q *Queries) GetUserSecurity(ctx context.Context, owner pgtype.UUID) (UsersSecurity, error) {
	row := q.db.QueryRow(ctx, GetUserSecurity, owner)
	var i UsersSecurity
	err := row.Scan(
		&i.Owner,
		&i.Password,
		&i.EmailVerified,
		&i.TotpEnabled,
		&i.TotpSecret,
		&i.TotpConfirmed,
		&i.TotpPending,
		&i.TotpPendingCreated,
		&i.TotpLastStep,
	)
	return i, err
}

const GetUsers = `-- name: GetUsers :many
select uid, username, email, joined from users limit $1 offset $2
`

type GetUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, GetUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uid,
			&i.Username,
			&i.Email,
			&i.Joined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GlobalStats = `-- name: GlobalStats :one
select coalesce((select city from project_location where city is not null group by city order by count(*) desc limit 1),'')::text as most_popular_city,coalesce((select count(*) from project_location where city is not null group by city order by count(*) desc limit 1),0) as most_popular_city_projects_count,(select count(*) from project_likes) as likes_count,(select count(*) from projects where impl_link is not null and status='implemented') as implemented_count,(select count(*) from projects) as ideas_count,(select coalesce(avg(extract(epoch from (accepted-created))/3600),0)::double precision from tickets where accepted is not null) as avg_tickets_response
`

type GlobalStatsRow struct {
	MostPopularCity              string      `json:"most_popular_city"`
	MostPopularCityProjectsCount interface{} `json:"most_popular_city_projects_count"`
	LikesCount                   int64       `json:"likes_count"`
	ImplementedCount             int64       `json:"implemented_count"`
	IdeasCount                   int64       `json:"ideas_count"`
	AvgTicketsResponse           float64     `json:"avg_tickets_response"`
}

func (q *Queries) GlobalStats(ctx context.Context) (GlobalStatsRow, error) {
	row := q.db.QueryRow(ctx, GlobalStats)
	var i GlobalStatsRow
	err := row.Scan(
		&i.MostPopularCity,
		&i.MostPopularCityProjectsCount,
		&i.LikesCount,
		&i.ImplementedCount,
		&i.IdeasCount,
		&i.AvgTicketsResponse,
	)
	return i, err
}

const HasActiveMaintenance = `-- name: HasActiveMaintenance :one
select exists (select 1
               from maintenances
               where status = 'running' or (planned_start < now() and actual_end is not null))
`

func (q *Queries) HasActiveMaintenance(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, HasActiveMaintenance)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

type InsertRecoveryCodesParams struct {
	Owner    pgtype.UUID `json:"owner"`
	Selector string      `json:"selector"`
	Hash     string      `json:"hash"`
}

const IsActionValid = `-- name: IsActionValid :one
select (used is null and expires > now())::boolean as is_valid from users_actions where hash = $1 and purpose = $2 limit 1
`

type IsActionValidParams struct {
	Hash    string `json:"hash"`
	Purpose string `json:"purpose"`
}

func (q *Queries) IsActionValid(ctx context.Context, arg IsActionValidParams) (bool, error) {
	row := q.db.QueryRow(ctx, IsActionValid, arg.Hash, arg.Purpose)
	var is_valid bool
	err := row.Scan(&is_valid)
	return is_valid, err
}

const IsProjectExists = `-- name: IsProjectExists :one
select exists (select 1 from projects where id = $1)
`

func (q *Queries) IsProjectExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, IsProjectExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const IsProjectLikeExists = `-- name: IsProjectLikeExists :one
select exists (select 1 from project_likes where project = $1 and author = $2)
`

type IsProjectLikeExistsParams struct {
	Project pgtype.UUID `json:"project"`
	Author  pgtype.UUID `json:"author"`
}

func (q *Queries) IsProjectLikeExists(ctx context.Context, arg IsProjectLikeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, IsProjectLikeExists, arg.Project, arg.Author)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const IsRankExists = `-- name: IsRankExists :one
select exists (select 1 from ranks where name = $1)
`

func (q *Queries) IsRankExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, IsRankExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const IsSessionCompleteMFA = `-- name: IsSessionCompleteMFA :one
select not (users_security.totp_enabled is true and sessions.mfa is not true) from sessions join users_security on users_security.owner = sessions.owner where sessions.id = $1
`

func (q *Queries) IsSessionCompleteMFA(ctx context.Context, id pgtype.UUID) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, IsSessionCompleteMFA, id)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const IsSessionValid = `-- name: IsSessionValid :one
select expires > now() and device = $1 and hash = $2 from sessions where id = $3
`

type IsSessionValidParams struct {
	Device DeviceT     `json:"device"`
	Hash   string      `json:"hash"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) IsSessionValid(ctx context.Context, arg IsSessionValidParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, IsSessionValid, arg.Device, arg.Hash, arg.ID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const IsSubmissionReviewed = `-- name: IsSubmissionReviewed :one
select approved <> false
from submissions
where linked = $1
`

func (q *Queries) IsSubmissionReviewed(ctx context.Context, linked pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, IsSubmissionReviewed, linked)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const IsTicketAccepted = `-- name: IsTicketAccepted :one
select (acceptor is not null)::boolean as is_accepted from tickets where id = $1
`

func (q *Queries) IsTicketAccepted(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, IsTicketAccepted, id)
	var is_accepted bool
	err := row.Scan(&is_accepted)
	return is_accepted, err
}

const IsTicketClosed = `-- name: IsTicketClosed :one
select (closed is not null)::boolean as is_closed from tickets where id = $1
`

func (q *Queries) IsTicketClosed(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, IsTicketClosed, id)
	var is_closed bool
	err := row.Scan(&is_closed)
	return is_closed, err
}

const IsUserBanned = `-- name: IsUserBanned :one
select exists (select 1 from users_bans where target = $1 and (expires is null or expires > now()))
`

func (q *Queries) IsUserBanned(ctx context.Context, target pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, IsUserBanned, target)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const IsUserExists = `-- name: IsUserExists :one
select exists (select 1 from users where username = $1 or email = $1)
`

func (q *Queries) IsUserExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, IsUserExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const MaintenancesHistory = `-- name: MaintenancesHistory :many
select id, description, status, type, planned_start, planned_end, actual_start, actual_end, caller, created from maintenances limit $1 offset $2
`

type MaintenancesHistoryParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) MaintenancesHistory(ctx context.Context, arg MaintenancesHistoryParams) ([]Maintenance, error) {
	rows, err := q.db.Query(ctx, MaintenancesHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Maintenance
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Status,
			&i.Type,
			&i.PlannedStart,
			&i.PlannedEnd,
			&i.ActualStart,
			&i.ActualEnd,
			&i.Caller,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MessageAuthor = `-- name: MessageAuthor :one
select author
from project_messages
where id = $1
limit 1
`

func (q *Queries) MessageAuthor(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, MessageAuthor, id)
	var author pgtype.UUID
	err := row.Scan(&author)
	return author, err
}

const MessageInfo = `-- name: MessageInfo :one
select id, linked, author, parent, content, at, deleted from project_messages where id = $1 limit 1
`

func (q *Queries) MessageInfo(ctx context.Context, id pgtype.UUID) (ProjectMessage, error) {
	row := q.db.QueryRow(ctx, MessageInfo, id)
	var i ProjectMessage
	err := row.Scan(
		&i.ID,
		&i.Linked,
		&i.Author,
		&i.Parent,
		&i.Content,
		&i.At,
		&i.Deleted,
	)
	return i, err
}

const MessagesList = `-- name: MessagesList :many
select id, linked, author, parent, content, at, deleted from project_messages where linked = $1 and deleted is null limit $2 offset $3
`

type MessagesListParams struct {
	Linked pgtype.UUID `json:"linked"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) MessagesList(ctx context.Context, arg MessagesListParams) ([]ProjectMessage, error) {
	rows, err := q.db.Query(ctx, MessagesList, arg.Linked, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMessage
	for rows.Next() {
		var i ProjectMessage
		if err := rows.Scan(
			&i.ID,
			&i.Linked,
			&i.Author,
			&i.Parent,
			&i.Content,
			&i.At,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MessagesListWithDeleted = `-- name: MessagesListWithDeleted :many
select id, linked, author, parent, content, at, deleted
from project_messages
where linked = $1
limit $2 offset $3
`

type MessagesListWithDeletedParams struct {
	Linked pgtype.UUID `json:"linked"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) MessagesListWithDeleted(ctx context.Context, arg MessagesListWithDeletedParams) ([]ProjectMessage, error) {
	rows, err := q.db.Query(ctx, MessagesListWithDeleted, arg.Linked, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMessage
	for rows.Next() {
		var i ProjectMessage
		if err := rows.Scan(
			&i.ID,
			&i.Linked,
			&i.Author,
			&i.Parent,
			&i.Content,
			&i.At,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const PlannedMaintenance = `-- name: PlannedMaintenance :one
select planned_start, description
from maintenances
where status = 'expected'
limit 1
`

type PlannedMaintenanceRow struct {
	PlannedStart pgtype.Timestamptz `json:"planned_start"`
	Description  string             `json:"description"`
}

func (q *Queries) PlannedMaintenance(ctx context.Context) (PlannedMaintenanceRow, error) {
	row := q.db.QueryRow(ctx, PlannedMaintenance)
	var i PlannedMaintenanceRow
	err := row.Scan(&i.PlannedStart, &i.Description)
	return i, err
}

const ProjectAuthor = `-- name: ProjectAuthor :one
select author
from projects
where id = $1
limit 1
`

func (q *Queries) ProjectAuthor(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, ProjectAuthor, id)
	var author pgtype.UUID
	err := row.Scan(&author)
	return author, err
}

const ProjectCreationGraph = `-- name: ProjectCreationGraph :many
with period as (select case $1::text
                           when 'hourly' then date_trunc('hour', now()) - interval '23 hours'
                           when 'weekly' then date_trunc('week', now() - interval '1 month')
                           else date_trunc('day', now()) - interval '6 days'
                           end as start_at,
                       case $1::text
                           when 'hourly' then date_trunc('hour', now())
                           when 'weekly' then date_trunc('week', now())
                           else date_trunc('day', now())
                           end as end_at,
                       case $1::text
                           when 'hourly' then interval '1 hour'
                           when 'weekly' then interval '1 week'
                           else interval '1 day'
                           end as bucket_interval),
     series as (select generate_series(period.start_at, period.end_at, period.bucket_interval) as at,
                       period.bucket_interval
                from period),
     events as (select projects.at
                from projects
                         join project_location on project_location.id = projects.id
                         cross join period
                where projects.at >= period.start_at
                  and projects.at < period.end_at + period.bucket_interval
                  and ($2::text is null or project_location.city = $2::text))
select series.at::timestamptz   as at,
       count(events.at)::bigint as value
from series
         left join events on events.at >= series.at and events.at < series.at + series.bucket_interval
group by series.at
order by series.at
`

type ProjectCreationGraphParams struct {
	Separator string      `json:"separator"`
	City      pgtype.Text `json:"city"`
}

type ProjectCreationGraphRow struct {
	At    pgtype.Timestamptz `json:"at"`
	Value int64              `json:"value"`
}

func (q *Queries) ProjectCreationGraph(ctx context.Context, arg ProjectCreationGraphParams) ([]ProjectCreationGraphRow, error) {
	rows, err := q.db.Query(ctx, ProjectCreationGraph, arg.Separator, arg.City)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectCreationGraphRow
	for rows.Next() {
		var i ProjectCreationGraphRow
		if err := rows.Scan(&i.At, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ProjectDiscussionGraph = `-- name: ProjectDiscussionGraph :many
with period as (select case $1::text
                           when 'hourly' then date_trunc('hour', now()) - interval '23 hours'
                           when 'weekly' then date_trunc('week', now() - interval '1 month')
                           else date_trunc('day', now()) - interval '6 days'
                           end as start_at,
                       case $1::text
                           when 'hourly' then date_trunc('hour', now())
                           when 'weekly' then date_trunc('week', now())
                           else date_trunc('day', now())
                           end as end_at,
                       case $1::text
                           when 'hourly' then interval '1 hour'
                           when 'weekly' then interval '1 week'
                           else interval '1 day'
                           end as bucket_interval),
     series as (select generate_series(period.start_at, period.end_at, period.bucket_interval) as at,
                       period.bucket_interval
                from period),
     events as (select project_messages.at
                from project_messages
                         join projects on projects.id = project_messages.linked
                         join project_location on project_location.id = projects.id
                         cross join period
                where project_messages.deleted is null
                  and project_messages.at >= period.start_at
                  and project_messages.at < period.end_at + period.bucket_interval
                  and ($2::text is null or project_location.city = $2::text))
select series.at::timestamptz   as at,
       count(events.at)::bigint as value
from series
         left join events on events.at >= series.at and events.at < series.at + series.bucket_interval
group by series.at
order by series.at
`

type ProjectDiscussionGraphParams struct {
	Separator string      `json:"separator"`
	City      pgtype.Text `json:"city"`
}

type ProjectDiscussionGraphRow struct {
	At    pgtype.Timestamptz `json:"at"`
	Value int64              `json:"value"`
}

func (q *Queries) ProjectDiscussionGraph(ctx context.Context, arg ProjectDiscussionGraphParams) ([]ProjectDiscussionGraphRow, error) {
	rows, err := q.db.Query(ctx, ProjectDiscussionGraph, arg.Separator, arg.City)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectDiscussionGraphRow
	for rows.Next() {
		var i ProjectDiscussionGraphRow
		if err := rows.Scan(&i.At, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ProjectInfo = `-- name: ProjectInfo :one
select projects.id,
       projects.author,
       title,
       description,
       category,
       count(project_likes.project)::bigint as likes_count,
       status,
       impl_link,
       projects.at,
       updated,
       deleted
from projects
         left join project_likes on project_likes.project = projects.id
where projects.id = $1
group by projects.id, projects.author, title, description, category, status, impl_link, projects.at, updated, deleted
limit 1
`

type ProjectInfoRow struct {
	ID          pgtype.UUID        `json:"id"`
	Author      pgtype.UUID        `json:"author"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Category    string             `json:"category"`
	LikesCount  int64              `json:"likes_count"`
	Status      ProjectsStatus     `json:"status"`
	ImplLink    pgtype.Text        `json:"impl_link"`
	At          pgtype.Timestamptz `json:"at"`
	Updated     pgtype.Timestamptz `json:"updated"`
	Deleted     pgtype.Timestamptz `json:"deleted"`
}

func (q *Queries) ProjectInfo(ctx context.Context, id pgtype.UUID) (ProjectInfoRow, error) {
	row := q.db.QueryRow(ctx, ProjectInfo, id)
	var i ProjectInfoRow
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.LikesCount,
		&i.Status,
		&i.ImplLink,
		&i.At,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}

const ProjectLocationInfo = `-- name: ProjectLocationInfo :one
select id, city, lat, lot
from project_location
where id = $1
`

func (q *Queries) ProjectLocationInfo(ctx context.Context, id pgtype.UUID) (ProjectLocation, error) {
	row := q.db.QueryRow(ctx, ProjectLocationInfo, id)
	var i ProjectLocation
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.Lat,
		&i.Lot,
	)
	return i, err
}

const ProjectVotesGraph = `-- name: ProjectVotesGraph :many
with period as (select case $1::text
                           when 'hourly' then date_trunc('hour', now()) - interval '23 hours'
                           when 'weekly' then date_trunc('week', now() - interval '1 month')
                           else date_trunc('day', now()) - interval '6 days'
                           end as start_at,
                       case $1::text
                           when 'hourly' then date_trunc('hour', now())
                           when 'weekly' then date_trunc('week', now())
                           else date_trunc('day', now())
                           end as end_at,
                       case $1::text
                           when 'hourly' then interval '1 hour'
                           when 'weekly' then interval '1 week'
                           else interval '1 day'
                           end as bucket_interval),
     series as (select generate_series(period.start_at, period.end_at, period.bucket_interval) as at,
                       period.bucket_interval
                from period),
     events as (select project_likes.at
                from project_likes
                         join projects on projects.id = project_likes.project
                         join project_location on project_location.id = projects.id
                         cross join period
                where project_likes.at >= period.start_at
                  and project_likes.at < period.end_at + period.bucket_interval
                  and ($2::text is null or project_location.city = $2::text))
select series.at::timestamptz   as at,
       count(events.at)::bigint as value
from series
         left join events on events.at >= series.at and events.at < series.at + series.bucket_interval
group by series.at
order by series.at
`

type ProjectVotesGraphParams struct {
	Separator string      `json:"separator"`
	City      pgtype.Text `json:"city"`
}

type ProjectVotesGraphRow struct {
	At    pgtype.Timestamptz `json:"at"`
	Value int64              `json:"value"`
}

func (q *Queries) ProjectVotesGraph(ctx context.Context, arg ProjectVotesGraphParams) ([]ProjectVotesGraphRow, error) {
	rows, err := q.db.Query(ctx, ProjectVotesGraph, arg.Separator, arg.City)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectVotesGraphRow
	for rows.Next() {
		var i ProjectVotesGraphRow
		if err := rows.Scan(&i.At, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ProjectsList = `-- name: ProjectsList :many
select projects.id,
       projects.author,
       title,
       description,
       category,
       status,
       impl_link,
       count(project_likes.project)::bigint as likes_count,
       projects.at,
       updated,
       deleted
from projects
         left join project_likes
                   on project_likes.project = projects.id
where status <> 'reviewing'
  and status <> 'cancelled'
group by projects.id,
         projects.author,
         title,
         description,
         category,
         status,
         impl_link,
         projects.at,
         updated,
         deleted
limit $1 offset $2
`

type ProjectsListParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ProjectsListRow struct {
	ID          pgtype.UUID        `json:"id"`
	Author      pgtype.UUID        `json:"author"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Category    string             `json:"category"`
	Status      ProjectsStatus     `json:"status"`
	ImplLink    pgtype.Text        `json:"impl_link"`
	LikesCount  int64              `json:"likes_count"`
	At          pgtype.Timestamptz `json:"at"`
	Updated     pgtype.Timestamptz `json:"updated"`
	Deleted     pgtype.Timestamptz `json:"deleted"`
}

func (q *Queries) ProjectsList(ctx context.Context, arg ProjectsListParams) ([]ProjectsListRow, error) {
	rows, err := q.db.Query(ctx, ProjectsList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectsListRow
	for rows.Next() {
		var i ProjectsListRow
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Status,
			&i.ImplLink,
			&i.LikesCount,
			&i.At,
			&i.Updated,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ProjectsTop = `-- name: ProjectsTop :many
select p.id,
       p.author,
       p.title,
       p.description,
       p.category,
       count(l.project)::bigint as likes_count,
       p.status,
       p.impl_link,
       p.at,
       p.updated,
       p.deleted
from projects p
         join project_location pl on pl.id = p.id
         left join project_likes l on l.project = p.id
where p.status not in ('reviewing', 'cancelled', 'implemented')
  and pl.city = $1
group by p.id
order by count(l.project) desc, p.at desc
limit $2 offset $3
`

type ProjectsTopParams struct {
	City   string `json:"city"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ProjectsTopRow struct {
	ID          pgtype.UUID        `json:"id"`
	Author      pgtype.UUID        `json:"author"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Category    string             `json:"category"`
	LikesCount  int64              `json:"likes_count"`
	Status      ProjectsStatus     `json:"status"`
	ImplLink    pgtype.Text        `json:"impl_link"`
	At          pgtype.Timestamptz `json:"at"`
	Updated     pgtype.Timestamptz `json:"updated"`
	Deleted     pgtype.Timestamptz `json:"deleted"`
}

func (q *Queries) ProjectsTop(ctx context.Context, arg ProjectsTopParams) ([]ProjectsTopRow, error) {
	rows, err := q.db.Query(ctx, ProjectsTop, arg.City, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectsTopRow
	for rows.Next() {
		var i ProjectsTopRow
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.LikesCount,
			&i.Status,
			&i.ImplLink,
			&i.At,
			&i.Updated,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const QuestionsGraph = `-- name: QuestionsGraph :many
with period as (select case $1::text
                           when 'hourly' then date_trunc('hour', now()) - interval '23 hours'
                           when 'weekly' then date_trunc('week', now() - interval '1 month')
                           else date_trunc('day', now()) - interval '6 days'
                           end as start_at,
                       case $1::text
                           when 'hourly' then date_trunc('hour', now())
                           when 'weekly' then date_trunc('week', now())
                           else date_trunc('day', now())
                           end as end_at,
                       case $1::text
                           when 'hourly' then interval '1 hour'
                           when 'weekly' then interval '1 week'
                           else interval '1 day'
                           end as bucket_interval),
     series as (select generate_series(period.start_at, period.end_at, period.bucket_interval) as at,
                       period.bucket_interval
                from period),
     events as (select tickets.created as at
                from tickets
                         cross join period
                where tickets.created >= period.start_at
                  and tickets.created < period.end_at + period.bucket_interval)
select series.at::timestamptz   as at,
       count(events.at)::bigint as value
from series
         left join events on events.at >= series.at and events.at < series.at + series.bucket_interval
group by series.at
order by series.at
`

type QuestionsGraphRow struct {
	At    pgtype.Timestamptz `json:"at"`
	Value int64              `json:"value"`
}

func (q *Queries) QuestionsGraph(ctx context.Context, separator string) ([]QuestionsGraphRow, error) {
	rows, err := q.db.Query(ctx, QuestionsGraph, separator)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionsGraphRow
	for rows.Next() {
		var i QuestionsGraphRow
		if err := rows.Scan(&i.At, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RankInfo = `-- name: RankInfo :one
select id, name, description, color, weight, permissions, added_at from ranks where name = $1 limit 1
`

func (q *Queries) RankInfo(ctx context.Context, name string) (Rank, error) {
	row := q.db.QueryRow(ctx, RankInfo, name)
	var i Rank
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Weight,
		&i.Permissions,
		&i.AddedAt,
	)
	return i, err
}

const RankInfoByID = `-- name: RankInfoByID :one
select id, name, description, color, weight, permissions, added_at from ranks where id = $1 limit 1
`

func (q *Queries) RankInfoByID(ctx context.Context, id pgtype.UUID) (Rank, error) {
	row := q.db.QueryRow(ctx, RankInfoByID, id)
	var i Rank
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Weight,
		&i.Permissions,
		&i.AddedAt,
	)
	return i, err
}

const RankUsers = `-- name: RankUsers :many
select owner from users_ranks join ranks on ranks.id = users_ranks.rank where ranks.name = $1
`

func (q *Queries) RankUsers(ctx context.Context, name string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, RankUsers, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var owner pgtype.UUID
		if err := rows.Scan(&owner); err != nil {
			return nil, err
		}
		items = append(items, owner)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RanksList = `-- name: RanksList :many
select id, name, description, color, weight, permissions, added_at from ranks limit $1 offset $2
`

type RanksListParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) RanksList(ctx context.Context, arg RanksListParams) ([]Rank, error) {
	rows, err := q.db.Query(ctx, RanksList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rank
	for rows.Next() {
		var i Rank
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Weight,
			&i.Permissions,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveProjectLike = `-- name: RemoveProjectLike :exec
delete from project_likes where project = $1 and author = $2
`

type RemoveProjectLikeParams struct {
	Project pgtype.UUID `json:"project"`
	Author  pgtype.UUID `json:"author"`
}

func (q *Queries) RemoveProjectLike(ctx context.Context, arg RemoveProjectLikeParams) error {
	_, err := q.db.Exec(ctx, RemoveProjectLike, arg.Project, arg.Author)
	return err
}

const ResetTotp = `-- name: ResetTotp :exec
update users_security
set totp_enabled         = false,
    totp_pending         = null,
    totp_confirmed       = null,
    totp_secret          = null,
    totp_last_step       = null,
    totp_pending_created = null
where owner = $1
`

func (q *Queries) ResetTotp(ctx context.Context, owner pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ResetTotp, owner)
	return err
}

const ResetTotpCodes = `-- name: ResetTotpCodes :exec
delete
from users_security_codes
where owner = $1
`

func (q *Queries) ResetTotpCodes(ctx context.Context, owner pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ResetTotpCodes, owner)
	return err
}

const RevokeRankFromUser = `-- name: RevokeRankFromUser :exec
update users_ranks set expires = now() from ranks where users_ranks.rank = ranks.id and ranks.name = $1 and users_ranks.owner = $2
`

type RevokeRankFromUserParams struct {
	Name  string      `json:"name"`
	Owner pgtype.UUID `json:"owner"`
}

func (q *Queries) RevokeRankFromUser(ctx context.Context, arg RevokeRankFromUserParams) error {
	_, err := q.db.Exec(ctx, RevokeRankFromUser, arg.Name, arg.Owner)
	return err
}

const RevokeSession = `-- name: RevokeSession :exec
update sessions set expires = now() where id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, RevokeSession, id)
	return err
}

const SessionInfo = `-- name: SessionInfo :one
select id, owner, at, seen_at, expires, mfa, device, hash from sessions where id = $1
`

func (q *Queries) SessionInfo(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, SessionInfo, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.At,
		&i.SeenAt,
		&i.Expires,
		&i.Mfa,
		&i.Device,
		&i.Hash,
	)
	return i, err
}

const SessionsByOwner = `-- name: SessionsByOwner :many
select id, owner, at, seen_at, expires, mfa, device, hash from sessions where owner = $1 limit $2 offset $3
`

type SessionsByOwnerParams struct {
	Owner  pgtype.UUID `json:"owner"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) SessionsByOwner(ctx context.Context, arg SessionsByOwnerParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, SessionsByOwner, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.At,
			&i.SeenAt,
			&i.Expires,
			&i.Mfa,
			&i.Device,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetProjectStatus = `-- name: SetProjectStatus :exec
update projects set status = $1, impl_link = $2 where id = $3
`

type SetProjectStatusParams struct {
	Status   ProjectsStatus `json:"status"`
	ImplLink pgtype.Text    `json:"impl_link"`
	ID       pgtype.UUID    `json:"id"`
}

func (q *Queries) SetProjectStatus(ctx context.Context, arg SetProjectStatusParams) error {
	_, err := q.db.Exec(ctx, SetProjectStatus, arg.Status, arg.ImplLink, arg.ID)
	return err
}

const SetSessionLastSeen = `-- name: SetSessionLastSeen :exec
update sessions set seen_at = now() where id = $1
`

func (q *Queries) SetSessionLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, SetSessionLastSeen, id)
	return err
}

const SetTotpLastSeen = `-- name: SetTotpLastSeen :exec
update users_security
set totp_last_step = $1
where owner = $2
`

type SetTotpLastSeenParams struct {
	TotpLastStep pgtype.Int8 `json:"totp_last_step"`
	Owner        pgtype.UUID `json:"owner"`
}

func (q *Queries) SetTotpLastSeen(ctx context.Context, arg SetTotpLastSeenParams) error {
	_, err := q.db.Exec(ctx, SetTotpLastSeen, arg.TotpLastStep, arg.Owner)
	return err
}

const SetUserSecurityEmailVerified = `-- name: SetUserSecurityEmailVerified :exec
update users_security set email_verified = true where owner = $1
`

func (q *Queries) SetUserSecurityEmailVerified(ctx context.Context, owner pgtype.UUID) error {
	_, err := q.db.Exec(ctx, SetUserSecurityEmailVerified, owner)
	return err
}

const StartMaintenance = `-- name: StartMaintenance :exec
update maintenances set status = 'running', actual_start = now() where id = $1
`

func (q *Queries) StartMaintenance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, StartMaintenance, id)
	return err
}

const StartUserSecurityTotp = `-- name: StartUserSecurityTotp :exec
update users_security set owner = $1, totp_pending = $2, totp_pending_created = now() where owner = $1
`

type StartUserSecurityTotpParams struct {
	Owner       pgtype.UUID `json:"owner"`
	TotpPending pgtype.Text `json:"totp_pending"`
}

func (q *Queries) StartUserSecurityTotp(ctx context.Context, arg StartUserSecurityTotpParams) error {
	_, err := q.db.Exec(ctx, StartUserSecurityTotp, arg.Owner, arg.TotpPending)
	return err
}

const SubmissionInfo = `-- name: SubmissionInfo :one
select id, linked, approved, reason from submissions where id = $1 limit 1
`

func (q *Queries) SubmissionInfo(ctx context.Context, id pgtype.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, SubmissionInfo, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Linked,
		&i.Approved,
		&i.Reason,
	)
	return i, err
}

const SubmissionsList = `-- name: SubmissionsList :many
select id, linked, approved, reason from submissions limit $1 offset $2
`

type SubmissionsListParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) SubmissionsList(ctx context.Context, arg SubmissionsListParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, SubmissionsList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.Linked,
			&i.Approved,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TicketInfo = `-- name: TicketInfo :one
select id,
       author,
       acceptor,
       status,
       topic,
       title,
       created,
       accepted,
       closed,
       closer,
       caller,
       reason
from tickets
where id = $1
limit 1
`

func (q *Queries) TicketInfo(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, TicketInfo, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Acceptor,
		&i.Status,
		&i.Topic,
		&i.Title,
		&i.Created,
		&i.Accepted,
		&i.Closed,
		&i.Closer,
		&i.Caller,
		&i.Reason,
	)
	return i, err
}

const TicketMessages = `-- name: TicketMessages :many
select id, ticket, author, content, created from tickets_messages where ticket = $1 limit $2 offset $3
`

type TicketMessagesParams struct {
	Ticket pgtype.UUID `json:"ticket"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) TicketMessages(ctx context.Context, arg TicketMessagesParams) ([]TicketsMessage, error) {
	rows, err := q.db.Query(ctx, TicketMessages, arg.Ticket, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketsMessage
	for rows.Next() {
		var i TicketsMessage
		if err := rows.Scan(
			&i.ID,
			&i.Ticket,
			&i.Author,
			&i.Content,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TicketOwner = `-- name: TicketOwner :one
select author
from tickets
where id = $1
limit 1
`

func (q *Queries) TicketOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, TicketOwner, id)
	var author pgtype.UUID
	err := row.Scan(&author)
	return author, err
}

const Tickets = `-- name: Tickets :many
select id,
       author,
       acceptor,
       status,
       topic,
       title,
       created,
       accepted,
       closed,
       closer,
       caller,
       reason
from tickets
limit $1 offset $2
`

type TicketsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) Tickets(ctx context.Context, arg TicketsParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, Tickets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Acceptor,
			&i.Status,
			&i.Topic,
			&i.Title,
			&i.Created,
			&i.Accepted,
			&i.Closed,
			&i.Closer,
			&i.Caller,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TicketsByAuthor = `-- name: TicketsByAuthor :many
select id,
       author,
       acceptor,
       status,
       topic,
       title,
       created,
       accepted,
       closed,
       closer,
       caller,
       reason
from tickets
where author = $1
limit $2 offset $3
`

type TicketsByAuthorParams struct {
	Author pgtype.UUID `json:"author"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) TicketsByAuthor(ctx context.Context, arg TicketsByAuthorParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, TicketsByAuthor, arg.Author, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Acceptor,
			&i.Status,
			&i.Topic,
			&i.Title,
			&i.Created,
			&i.Accepted,
			&i.Closed,
			&i.Closer,
			&i.Caller,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UnbanUser = `-- name: UnbanUser :exec
UPDATE users_bans SET remove = $1, expires = now() WHERE target = $2 AND (expires > now() OR expires IS NULL) AND remove IS NULL
`

type UnbanUserParams struct {
	Remove pgtype.UUID `json:"remove"`
	Target pgtype.UUID `json:"target"`
}

func (q *Queries) UnbanUser(ctx context.Context, arg UnbanUserParams) error {
	_, err := q.db.Exec(ctx, UnbanUser, arg.Remove, arg.Target)
	return err
}

const UpdateProjectDescription = `-- name: UpdateProjectDescription :exec
update projects set description = $1, updated = now() where id = $2
`

type UpdateProjectDescriptionParams struct {
	Description string      `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProjectDescription(ctx context.Context, arg UpdateProjectDescriptionParams) error {
	_, err := q.db.Exec(ctx, UpdateProjectDescription, arg.Description, arg.ID)
	return err
}

const UpdateRankColor = `-- name: UpdateRankColor :exec
update ranks set color = $1 where id = $2
`

type UpdateRankColorParams struct {
	Color int64       `json:"color"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRankColor(ctx context.Context, arg UpdateRankColorParams) error {
	_, err := q.db.Exec(ctx, UpdateRankColor, arg.Color, arg.ID)
	return err
}

const UpdateRankDescription = `-- name: UpdateRankDescription :exec
update ranks set description = $1 where id = $2
`

type UpdateRankDescriptionParams struct {
	Description string      `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRankDescription(ctx context.Context, arg UpdateRankDescriptionParams) error {
	_, err := q.db.Exec(ctx, UpdateRankDescription, arg.Description, arg.ID)
	return err
}

const UpdateRankName = `-- name: UpdateRankName :exec
update ranks set name = $1 where id = $2
`

type UpdateRankNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRankName(ctx context.Context, arg UpdateRankNameParams) error {
	_, err := q.db.Exec(ctx, UpdateRankName, arg.Name, arg.ID)
	return err
}

const UpdateRankPermissions = `-- name: UpdateRankPermissions :exec
update ranks set permissions = $1 where id = $2
`

type UpdateRankPermissionsParams struct {
	Permissions []byte      `json:"permissions"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRankPermissions(ctx context.Context, arg UpdateRankPermissionsParams) error {
	_, err := q.db.Exec(ctx, UpdateRankPermissions, arg.Permissions, arg.ID)
	return err
}

const UpdateRankWeight = `-- name: UpdateRankWeight :exec
update ranks set weight = $1 where id = $2
`

type UpdateRankWeightParams struct {
	Weight int32       `json:"weight"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRankWeight(ctx context.Context, arg UpdateRankWeightParams) error {
	_, err := q.db.Exec(ctx, UpdateRankWeight, arg.Weight, arg.ID)
	return err
}

const UpdateUserAvatar = `-- name: UpdateUserAvatar :exec
update users_preferences set avatar_hash = $1 where owner = $2
`

type UpdateUserAvatarParams struct {
	AvatarHash pgtype.Text `json:"avatar_hash"`
	Owner      pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, UpdateUserAvatar, arg.AvatarHash, arg.Owner)
	return err
}

const UpdateUserDescription = `-- name: UpdateUserDescription :exec
update users_preferences set description = $1 where owner = $2
`

type UpdateUserDescriptionParams struct {
	Description string      `json:"description"`
	Owner       pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdateUserDescription(ctx context.Context, arg UpdateUserDescriptionParams) error {
	_, err := q.db.Exec(ctx, UpdateUserDescription, arg.Description, arg.Owner)
	return err
}

const UpdateUserDisplayName = `-- name: UpdateUserDisplayName :exec
update users_preferences set display_name = $1 where owner = $2
`

type UpdateUserDisplayNameParams struct {
	DisplayName string      `json:"display_name"`
	Owner       pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.Exec(ctx, UpdateUserDisplayName, arg.DisplayName, arg.Owner)
	return err
}

const UpdateUserLanguage = `-- name: UpdateUserLanguage :exec
update users_preferences
set language = $1
where owner = $2
`

type UpdateUserLanguageParams struct {
	Language PreferencesLanguages `json:"language"`
	Owner    pgtype.UUID          `json:"owner"`
}

func (q *Queries) UpdateUserLanguage(ctx context.Context, arg UpdateUserLanguageParams) error {
	_, err := q.db.Exec(ctx, UpdateUserLanguage, arg.Language, arg.Owner)
	return err
}

const UpdateUserPassword = `-- name: UpdateUserPassword :exec
update users_security set password = $1 where owner = $2
`

type UpdateUserPasswordParams struct {
	Password string      `json:"password"`
	Owner    pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, UpdateUserPassword, arg.Password, arg.Owner)
	return err
}

const UpdateUserSessionLive = `-- name: UpdateUserSessionLive :exec
update users_preferences set session_live = $1 where owner = $2
`

type UpdateUserSessionLiveParams struct {
	SessionLive int32       `json:"session_live"`
	Owner       pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdateUserSessionLive(ctx context.Context, arg UpdateUserSessionLiveParams) error {
	_, err := q.db.Exec(ctx, UpdateUserSessionLive, arg.SessionLive, arg.Owner)
	return err
}

const UseAction = `-- name: UseAction :exec
update users_actions set used = now() where hash = $1 and purpose = $2
`

type UseActionParams struct {
	Hash    string `json:"hash"`
	Purpose string `json:"purpose"`
}

func (q *Queries) UseAction(ctx context.Context, arg UseActionParams) error {
	_, err := q.db.Exec(ctx, UseAction, arg.Hash, arg.Purpose)
	return err
}

const UseRecoveryCode = `-- name: UseRecoveryCode :exec
update users_security_codes
set used = now()
where selector = $1
`

func (q *Queries) UseRecoveryCode(ctx context.Context, selector string) error {
	_, err := q.db.Exec(ctx, UseRecoveryCode, selector)
	return err
}
