// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/city_ideas/v1/cities/v1/domain.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type City struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_At          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *City) Reset() {
	*x = City{}
	mi := &file_xyz_city_ideas_v1_cities_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_cities_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *City) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *City) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *City) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_At
	}
	return nil
}

func (x *City) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *City) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *City) SetAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_At = v
}

func (x *City) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *City) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *City) HasAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_At != nil
}

func (x *City) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *City) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *City) ClearAt() {
	x.xxx_hidden_At = nil
}

type City_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   *string
	Name *string
	At   *timestamppb.Timestamp
}

func (b0 City_builder) Build() *City {
	m0 := &City{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_At = b.At
	return m0
}

type CreateCityRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateCityRequest) Reset() {
	*x = CreateCityRequest{}
	mi := &file_xyz_city_ideas_v1_cities_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCityRequest) ProtoMessage() {}

func (x *CreateCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_cities_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateCityRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *CreateCityRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CreateCityRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateCityRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type CreateCityRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 CreateCityRequest_builder) Build() *CreateCityRequest {
	m0 := &CreateCityRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type ListResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_List *[]*City               `protobuf:"bytes,1,rep,name=list"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_xyz_city_ideas_v1_cities_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_cities_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListResponse) GetList() []*City {
	if x != nil {
		if x.xxx_hidden_List != nil {
			return *x.xxx_hidden_List
		}
	}
	return nil
}

func (x *ListResponse) SetList(v []*City) {
	x.xxx_hidden_List = &v
}

type ListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	List []*City
}

func (b0 ListResponse_builder) Build() *ListResponse {
	m0 := &ListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_List = &b.List
	return m0
}

var File_xyz_city_ideas_v1_cities_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_cities_v1_domain_proto_rawDesc = "" +
	"\n" +
	"(xyz/city_ideas/v1/cities/v1/domain.proto\x12\x1bxyz.city_ideas.v1.cities.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n" +
	"\x04City\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"'\n" +
	"\x11CreateCityRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"E\n" +
	"\fListResponse\x125\n" +
	"\x04list\x18\x01 \x03(\v2!.xyz.city_ideas.v1.cities.v1.CityR\x04listBEZCgithub.com/aesterial/cityideas/backend/internal/api/v1/cities/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_cities_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_xyz_city_ideas_v1_cities_v1_domain_proto_goTypes = []any{
	(*City)(nil),                  // 0: xyz.city_ideas.v1.cities.v1.City
	(*CreateCityRequest)(nil),     // 1: xyz.city_ideas.v1.cities.v1.CreateCityRequest
	(*ListResponse)(nil),          // 2: xyz.city_ideas.v1.cities.v1.ListResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_xyz_city_ideas_v1_cities_v1_domain_proto_depIdxs = []int32{
	3, // 0: xyz.city_ideas.v1.cities.v1.City.at:type_name -> google.protobuf.Timestamp
	0, // 1: xyz.city_ideas.v1.cities.v1.ListResponse.list:type_name -> xyz.city_ideas.v1.cities.v1.City
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_cities_v1_domain_proto_init() }
func file_xyz_city_ideas_v1_cities_v1_domain_proto_init() {
	if File_xyz_city_ideas_v1_cities_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_cities_v1_domain_proto_rawDesc), len(file_xyz_city_ideas_v1_cities_v1_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_city_ideas_v1_cities_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_cities_v1_domain_proto_depIdxs,
		MessageInfos:      file_xyz_city_ideas_v1_cities_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_city_ideas_v1_cities_v1_domain_proto = out.File
	file_xyz_city_ideas_v1_cities_v1_domain_proto_goTypes = nil
	file_xyz_city_ideas_v1_cities_v1_domain_proto_depIdxs = nil
}
