// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz.city_ideas.v1/tickets/v1/domain.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Waiting Status = 0
	Status_Closed  Status = 1
	Status_InWork  Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Waiting",
		1: "Closed",
		2: "InWork",
	}
	Status_value = map[string]int32{
		"Waiting": 0,
		"Closed":  1,
		"InWork":  2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_xyz_city_ideas_v1_tickets_v1_domain_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_xyz_city_ideas_v1_tickets_v1_domain_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Closer int32

const (
	Closer_System Closer = 0
	Closer_User   Closer = 1
	Closer_Staff  Closer = 2
)

// Enum value maps for Closer.
var (
	Closer_name = map[int32]string{
		0: "System",
		1: "User",
		2: "Staff",
	}
	Closer_value = map[string]int32{
		"System": 0,
		"User":   1,
		"Staff":  2,
	}
)

func (x Closer) Enum() *Closer {
	p := new(Closer)
	*p = x
	return p
}

func (x Closer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Closer) Descriptor() protoreflect.EnumDescriptor {
	return file_xyz_city_ideas_v1_tickets_v1_domain_proto_enumTypes[1].Descriptor()
}

func (Closer) Type() protoreflect.EnumType {
	return &file_xyz_city_ideas_v1_tickets_v1_domain_proto_enumTypes[1]
}

func (x Closer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Ticket struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_AuthorId    *string                `protobuf:"bytes,2,opt,name=author_id,json=authorId"`
	xxx_hidden_Acceptor    *string                `protobuf:"bytes,3,opt,name=acceptor"`
	xxx_hidden_Status      Status                 `protobuf:"varint,4,opt,name=status,enum=xyz.city_ideas.v1.tickets.v1.Status"`
	xxx_hidden_Topic       *string                `protobuf:"bytes,5,opt,name=topic"`
	xxx_hidden_Title       *string                `protobuf:"bytes,6,opt,name=title"`
	xxx_hidden_Created     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created"`
	xxx_hidden_Accepted    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=accepted"`
	xxx_hidden_Closed      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=closed"`
	xxx_hidden_Closer      Closer                 `protobuf:"varint,10,opt,name=closer,enum=xyz.city_ideas.v1.tickets.v1.Closer"`
	xxx_hidden_Reason      *string                `protobuf:"bytes,11,opt,name=reason"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_xyz_city_ideas_v1_tickets_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_tickets_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Ticket) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Ticket) GetAuthorId() string {
	if x != nil {
		if x.xxx_hidden_AuthorId != nil {
			return *x.xxx_hidden_AuthorId
		}
		return ""
	}
	return ""
}

func (x *Ticket) GetAcceptor() string {
	if x != nil {
		if x.xxx_hidden_Acceptor != nil {
			return *x.xxx_hidden_Acceptor
		}
		return ""
	}
	return ""
}

func (x *Ticket) GetStatus() Status {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_Status
		}
	}
	return Status_Waiting
}

func (x *Ticket) GetTopic() string {
	if x != nil {
		if x.xxx_hidden_Topic != nil {
			return *x.xxx_hidden_Topic
		}
		return ""
	}
	return ""
}

func (x *Ticket) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *Ticket) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Created
	}
	return nil
}

func (x *Ticket) GetAccepted() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Accepted
	}
	return nil
}

func (x *Ticket) GetClosed() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Closed
	}
	return nil
}

func (x *Ticket) GetCloser() Closer {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 9) {
			return x.xxx_hidden_Closer
		}
	}
	return Closer_System
}

func (x *Ticket) GetReason() string {
	if x != nil {
		if x.xxx_hidden_Reason != nil {
			return *x.xxx_hidden_Reason
		}
		return ""
	}
	return ""
}

func (x *Ticket) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 11)
}

func (x *Ticket) SetAuthorId(v string) {
	x.xxx_hidden_AuthorId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 11)
}

func (x *Ticket) SetAcceptor(v string) {
	x.xxx_hidden_Acceptor = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *Ticket) SetStatus(v Status) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *Ticket) SetTopic(v string) {
	x.xxx_hidden_Topic = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 11)
}

func (x *Ticket) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 11)
}

func (x *Ticket) SetCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Created = v
}

func (x *Ticket) SetAccepted(v *timestamppb.Timestamp) {
	x.xxx_hidden_Accepted = v
}

func (x *Ticket) SetClosed(v *timestamppb.Timestamp) {
	x.xxx_hidden_Closed = v
}

func (x *Ticket) SetCloser(v Closer) {
	x.xxx_hidden_Closer = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 11)
}

func (x *Ticket) SetReason(v string) {
	x.xxx_hidden_Reason = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 11)
}

func (x *Ticket) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Ticket) HasAuthorId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Ticket) HasAcceptor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Ticket) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Ticket) HasTopic() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Ticket) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Ticket) HasCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Created != nil
}

func (x *Ticket) HasAccepted() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Accepted != nil
}

func (x *Ticket) HasClosed() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Closed != nil
}

func (x *Ticket) HasCloser() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *Ticket) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *Ticket) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Ticket) ClearAuthorId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AuthorId = nil
}

func (x *Ticket) ClearAcceptor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Acceptor = nil
}

func (x *Ticket) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Status = Status_Waiting
}

func (x *Ticket) ClearTopic() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Topic = nil
}

func (x *Ticket) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Title = nil
}

func (x *Ticket) ClearCreated() {
	x.xxx_hidden_Created = nil
}

func (x *Ticket) ClearAccepted() {
	x.xxx_hidden_Accepted = nil
}

func (x *Ticket) ClearClosed() {
	x.xxx_hidden_Closed = nil
}

func (x *Ticket) ClearCloser() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Closer = Closer_System
}

func (x *Ticket) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_Reason = nil
}

type Ticket_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       *string
	AuthorId *string
	Acceptor *string
	Status   *Status
	Topic    *string
	Title    *string
	Created  *timestamppb.Timestamp
	Accepted *timestamppb.Timestamp
	Closed   *timestamppb.Timestamp
	Closer   *Closer
	Reason   *string
}

func (b0 Ticket_builder) Build() *Ticket {
	m0 := &Ticket{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 11)
		x.xxx_hidden_Id = b.Id
	}
	if b.AuthorId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 11)
		x.xxx_hidden_AuthorId = b.AuthorId
	}
	if b.Acceptor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_Acceptor = b.Acceptor
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_Status = *b.Status
	}
	if b.Topic != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 11)
		x.xxx_hidden_Topic = b.Topic
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 11)
		x.xxx_hidden_Title = b.Title
	}
	x.xxx_hidden_Created = b.Created
	x.xxx_hidden_Accepted = b.Accepted
	x.xxx_hidden_Closed = b.Closed
	if b.Closer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 11)
		x.xxx_hidden_Closer = *b.Closer
	}
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 11)
		x.xxx_hidden_Reason = b.Reason
	}
	return m0
}

type Message struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Ticket      *string                `protobuf:"bytes,2,opt,name=ticket"`
	xxx_hidden_Author      *string                `protobuf:"bytes,3,opt,name=author"`
	xxx_hidden_Content     *string                `protobuf:"bytes,4,opt,name=content"`
	xxx_hidden_Created     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_xyz_city_ideas_v1_tickets_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_tickets_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Message) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Message) GetTicket() string {
	if x != nil {
		if x.xxx_hidden_Ticket != nil {
			return *x.xxx_hidden_Ticket
		}
		return ""
	}
	return ""
}

func (x *Message) GetAuthor() string {
	if x != nil {
		if x.xxx_hidden_Author != nil {
			return *x.xxx_hidden_Author
		}
		return ""
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		if x.xxx_hidden_Content != nil {
			return *x.xxx_hidden_Content
		}
		return ""
	}
	return ""
}

func (x *Message) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Created
	}
	return nil
}

func (x *Message) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Message) SetTicket(v string) {
	x.xxx_hidden_Ticket = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Message) SetAuthor(v string) {
	x.xxx_hidden_Author = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Message) SetContent(v string) {
	x.xxx_hidden_Content = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Message) SetCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Created = v
}

func (x *Message) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Message) HasTicket() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Message) HasAuthor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Message) HasContent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Message) HasCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Created != nil
}

func (x *Message) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Message) ClearTicket() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ticket = nil
}

func (x *Message) ClearAuthor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Author = nil
}

func (x *Message) ClearContent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Content = nil
}

func (x *Message) ClearCreated() {
	x.xxx_hidden_Created = nil
}

type Message_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Ticket  *string
	Author  *string
	Content *string
	Created *timestamppb.Timestamp
}

func (b0 Message_builder) Build() *Message {
	m0 := &Message{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Ticket != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Ticket = b.Ticket
	}
	if b.Author != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Author = b.Author
	}
	if b.Content != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Content = b.Content
	}
	x.xxx_hidden_Created = b.Created
	return m0
}

type CreateTicketRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Topic       *string                `protobuf:"bytes,1,opt,name=topic"`
	xxx_hidden_Title       *string                `protobuf:"bytes,2,opt,name=title"`
	xxx_hidden_Message     *string                `protobuf:"bytes,3,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateTicketRequest) Reset() {
	*x = CreateTicketRequest{}
	mi := &file_xyz_city_ideas_v1_tickets_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketRequest) ProtoMessage() {}

func (x *CreateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_city_ideas_v1_tickets_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateTicketRequest) GetTopic() string {
	if x != nil {
		if x.xxx_hidden_Topic != nil {
			return *x.xxx_hidden_Topic
		}
		return ""
	}
	return ""
}

func (x *CreateTicketRequest) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *CreateTicketRequest) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *CreateTicketRequest) SetTopic(v string) {
	x.xxx_hidden_Topic = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *CreateTicketRequest) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CreateTicketRequest) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CreateTicketRequest) HasTopic() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateTicketRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateTicketRequest) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateTicketRequest) ClearTopic() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Topic = nil
}

func (x *CreateTicketRequest) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

func (x *CreateTicketRequest) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Message = nil
}

type CreateTicketRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Topic   *string
	Title   *string
	Message *string
}

func (b0 CreateTicketRequest_builder) Build() *CreateTicketRequest {
	m0 := &CreateTicketRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Topic != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Topic = b.Topic
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Title = b.Title
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

var File_xyz_city_ideas_v1_tickets_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_tickets_v1_domain_proto_rawDesc = "" +
	"\n" +
	")xyz.city_ideas.v1/tickets/v1/domain.proto\x12\x1cxyz.city_ideas.v1.tickets.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x03\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x1a\n" +
	"\bacceptor\x18\x03 \x01(\tR\bacceptor\x12<\n" +
	"\x06status\x18\x04 \x01(\x0e2$.xyz.city_ideas.v1.tickets.v1.StatusR\x06status\x12\x14\n" +
	"\x05topic\x18\x05 \x01(\tR\x05topic\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x124\n" +
	"\acreated\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x126\n" +
	"\baccepted\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\baccepted\x122\n" +
	"\x06closed\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06closed\x12<\n" +
	"\x06closer\x18\n" +
	" \x01(\x0e2$.xyz.city_ideas.v1.tickets.v1.CloserR\x06closer\x12\x16\n" +
	"\x06reason\x18\v \x01(\tR\x06reason\"\x99\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06ticket\x18\x02 \x01(\tR\x06ticket\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x124\n" +
	"\acreated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\"[\n" +
	"\x13CreateTicketRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*-\n" +
	"\x06Status\x12\v\n" +
	"\aWaiting\x10\x00\x12\n" +
	"\n" +
	"\x06Closed\x10\x01\x12\n" +
	"\n" +
	"\x06InWork\x10\x02*)\n" +
	"\x06Closer\x12\n" +
	"\n" +
	"\x06System\x10\x00\x12\b\n" +
	"\x04User\x10\x01\x12\t\n" +
	"\x05Staff\x10\x02BFZDgithub.com/aesterial/cityideas/backend/internal/api/v1/tickets/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_tickets_v1_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_xyz_city_ideas_v1_tickets_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_xyz_city_ideas_v1_tickets_v1_domain_proto_goTypes = []any{
	(Status)(0),                   // 0: xyz.city_ideas.v1.tickets.v1.Status
	(Closer)(0),                   // 1: xyz.city_ideas.v1.tickets.v1.Closer
	(*Ticket)(nil),                // 2: xyz.city_ideas.v1.tickets.v1.Ticket
	(*Message)(nil),               // 3: xyz.city_ideas.v1.tickets.v1.Message
	(*CreateTicketRequest)(nil),   // 4: xyz.city_ideas.v1.tickets.v1.CreateTicketRequest
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_xyz_city_ideas_v1_tickets_v1_domain_proto_depIdxs = []int32{
	0, // 0: xyz.city_ideas.v1.tickets.v1.Ticket.status:type_name -> xyz.city_ideas.v1.tickets.v1.Status
	5, // 1: xyz.city_ideas.v1.tickets.v1.Ticket.created:type_name -> google.protobuf.Timestamp
	5, // 2: xyz.city_ideas.v1.tickets.v1.Ticket.accepted:type_name -> google.protobuf.Timestamp
	5, // 3: xyz.city_ideas.v1.tickets.v1.Ticket.closed:type_name -> google.protobuf.Timestamp
	1, // 4: xyz.city_ideas.v1.tickets.v1.Ticket.closer:type_name -> xyz.city_ideas.v1.tickets.v1.Closer
	5, // 5: xyz.city_ideas.v1.tickets.v1.Message.created:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_tickets_v1_domain_proto_init() }
func file_xyz_city_ideas_v1_tickets_v1_domain_proto_init() {
	if File_xyz_city_ideas_v1_tickets_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_tickets_v1_domain_proto_rawDesc), len(file_xyz_city_ideas_v1_tickets_v1_domain_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_city_ideas_v1_tickets_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_tickets_v1_domain_proto_depIdxs,
		EnumInfos:         file_xyz_city_ideas_v1_tickets_v1_domain_proto_enumTypes,
		MessageInfos:      file_xyz_city_ideas_v1_tickets_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_city_ideas_v1_tickets_v1_domain_proto = out.File
	file_xyz_city_ideas_v1_tickets_v1_domain_proto_goTypes = nil
	file_xyz_city_ideas_v1_tickets_v1_domain_proto_depIdxs = nil
}
