// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz.city_ideas.v1/tickets/v1/service.proto

package v1

import (
	_ "github.com/aesterial/cityideas/backend/internal/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xyz_city_ideas_v1_tickets_v1_service_proto protoreflect.FileDescriptor

const file_xyz_city_ideas_v1_tickets_v1_service_proto_rawDesc = "" +
	"\n" +
	"*xyz.city_ideas.v1/tickets/v1/service.proto\x12\x1cxyz.city_ideas.v1.tickets.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dxyz.city_ideas.v1/types.proto\x1a)xyz.city_ideas.v1/tickets/v1/domain.proto2r\n" +
	"\rTicketService\x12a\n" +
	"\x06Create\x121.xyz.city_ideas.v1.tickets.v1.CreateTicketRequest\x1a$.xyz.city_ideas.v1.tickets.v1.TicketBFZDgithub.com/aesterial/cityideas/backend/internal/api/v1/tickets/v1;v1b\beditionsp\xe8\a"

var file_xyz_city_ideas_v1_tickets_v1_service_proto_goTypes = []any{
	(*CreateTicketRequest)(nil), // 0: xyz.city_ideas.v1.tickets.v1.CreateTicketRequest
	(*Ticket)(nil),              // 1: xyz.city_ideas.v1.tickets.v1.Ticket
}
var file_xyz_city_ideas_v1_tickets_v1_service_proto_depIdxs = []int32{
	0, // 0: xyz.city_ideas.v1.tickets.v1.TicketService.Create:input_type -> xyz.city_ideas.v1.tickets.v1.CreateTicketRequest
	1, // 1: xyz.city_ideas.v1.tickets.v1.TicketService.Create:output_type -> xyz.city_ideas.v1.tickets.v1.Ticket
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_city_ideas_v1_tickets_v1_service_proto_init() }
func file_xyz_city_ideas_v1_tickets_v1_service_proto_init() {
	if File_xyz_city_ideas_v1_tickets_v1_service_proto != nil {
		return
	}
	file_xyz_city_ideas_v1_tickets_v1_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_city_ideas_v1_tickets_v1_service_proto_rawDesc), len(file_xyz_city_ideas_v1_tickets_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_city_ideas_v1_tickets_v1_service_proto_goTypes,
		DependencyIndexes: file_xyz_city_ideas_v1_tickets_v1_service_proto_depIdxs,
	}.Build()
	File_xyz_city_ideas_v1_tickets_v1_service_proto = out.File
	file_xyz_city_ideas_v1_tickets_v1_service_proto_goTypes = nil
	file_xyz_city_ideas_v1_tickets_v1_service_proto_depIdxs = nil
}
